Repository stfc/PSyclone, pull requests merged in 2019-03, with the labels that each got.

#293 #292 add RegionTransform.valid_node_types and check in validate
  changelog
  psyclone.pdf
  src/psyclone/tests/gocean1p0_transformations_test.py
  src/psyclone/transformations.py
Labels: under review

#299 Method to generate C and OpenCL for selected PSyIR nodes
  changelog
  psyclone.pdf
  src/psyclone/gocean1p0.py
  src/psyclone/psyGen.py
  src/psyclone/tests/gocean1p0_opencl_test.py
  src/psyclone/tests/psyGen_test.py
Labels: ready for review

#301 Add an extras_require section to simplify doc and test dependency installation
  README.md
  doc/README
  doc/README.md
  doc/getting_going.rst
  setup.py
Labels: reviewed with actions

#218 Initial PSYKE support
  changelog
  doc/dynamo0p3.rst
  doc/examples.rst
  doc/gocean1p0.rst
  doc/index.rst
  doc/psyke.rst
  doc/transformations.rst
  examples/check_examples
  examples/dynamo/README
  examples/dynamo/eg12/colouring_and_omp.py
  examples/dynamo/eg12/dg_matrix_vector_kernel_mod.F90
  examples/dynamo/eg12/extract_kernel_with_transformations.py
  examples/dynamo/eg12/extract_nodes.py
  examples/dynamo/eg12/find_kernel.py
  examples/dynamo/eg12/gw_mixed_schur_preconditioner_alg_mod.x90
  examples/dynamo/eg12/matrix_vector_kernel_mod.F90
  psyclone.pdf
  src/psyclone/dynamo0p3.py
  src/psyclone/extractor.py
  src/psyclone/generator.py
  src/psyclone/psyGen.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/dynamo0p3_transformations_test.py
  src/psyclone/tests/extract_test.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/test_files/dynamo0p3/1_single_invoke.f90
  src/psyclone/tests/test_files/dynamo0p3/3.2_multi_functions_multi_named_invokes.f90
  src/psyclone/tests/test_files/dynamo0p3/4.7_multikernel_invokes.f90
  src/psyclone/tests/test_files/dynamo0p3/4.8_multikernel_invokes.f90
  src/psyclone/transformations.py
Labels: ready for review, under review

#328 Fix #327 (xpassing test)
  changelog
  src/psyclone/tests/gocean1p0_transformations_test.py
Labels: under review
