Repository stfc/PSyclone, pull requests merged in 2019-11, with the labels that each got.

#565 Add profile nodes after applying optimisation script (from issue #564)
  changelog
  doc/user_guide/profiling.rst
  psyclone.pdf
  src/psyclone/generator.py
  src/psyclone/psyGen.py
  src/psyclone/tests/profile_test.py
Labels: ready to be merged

#505 Add child indices to view method (for 303)
  changelog
  doc/developer_guide/developers.rst
  doc/user_guide/index.rst
  doc/user_guide/psyir.rst
  doc/user_guide/schedule_with_indices.png
  examples/dynamo/eg14/acc_parallel_dm.py
  psyclone.pdf
  src/psyclone/dynamo0p3.py
  src/psyclone/dynamo0p3_builtins.py
  src/psyclone/extractor.py
  src/psyclone/gocean1p0.py
  src/psyclone/nemo.py
  src/psyclone/profiler.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/backend/c.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/dynamo0p3_transformations_test.py
  src/psyclone/tests/extract_test.py
  src/psyclone/tests/gocean1p0_test.py
  src/psyclone/tests/gocean1p0_transformations_test.py
  src/psyclone/tests/nemo/nemo_psy_test.py
  src/psyclone/tests/nemo/transformations/openacc/data_directive_test.py
  src/psyclone/tests/nemo/transformations/openacc/parallel_directive_test.py
  src/psyclone/tests/nemo/transformations/openmp/openmp_test.py
  src/psyclone/tests/profile_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/backend/psyir_openmp_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#572 unicode fixes for broken tests (#571)
  changelog
  psyclone.pdf
  src/psyclone/dynamo0p3.py
  src/psyclone/dynamo0p3_builtins.py
  src/psyclone/f2pygen.py
  src/psyclone/gocean1p0.py
  src/psyclone/parse/kernel.py
Labels: ready to be merged

#524 472 sir scalars
  changelog
  doc/developer_guide/developers.rst
  examples/nemo/eg4/README.md
  examples/nemo/eg4/if_example.f90
  psyclone.pdf
  src/psyclone/psyir/backend/sir.py
  src/psyclone/tests/psyir/backend/sir_test.py
Labels: under review

#574 fix for profiling with builtins (for #567)
  changelog
  psyclone.pdf
  src/psyclone/profiler.py
  src/psyclone/tests/profile_test.py
Labels: ready to be merged

#576 Install examples when using pip (#530)
  MANIFEST.in
  changelog
  doc/user_guide/examples.rst
  doc/user_guide/getting_going.rst
  psyclone.pdf
  setup.py
Labels: under review

#563 Add support for processing KIND parameters (#375)
  src/psyclone/psyGen.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/gocean1p0_opencl_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
Labels: under review

#579 Issue 509. Update User's Guide entry page
  changelog
  doc/user_guide/conf.py
  doc/user_guide/dynamo0p1.rst
  doc/user_guide/index.rst
  psyclone.pdf
Labels: ready to be merged

#581 Fortran backend precision support (#578)
  changelog
  psyclone.pdf
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/test_files/dynamo0p3/testkern_any_space_1_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/testkern_any_space_2_mod.f90
Labels: ready for review

#562 473 fix dag
  changelog
  psyclone.pdf
  src/psyclone/psyGen.py
  src/psyclone/tests/gocean1p0_test.py
  src/psyclone/tests/psyGen_test.py
Labels: ready to be merged

#535 (Towards 150) implements support for parsing of ref elem meta-data
  changelog
  psyclone.pdf
  src/psyclone/dynamo0p3.py
  src/psyclone/parse/kernel.py
  src/psyclone/tests/dynamo0p3_lma_test.py
  src/psyclone/tests/dynamo0p3_ref_elem_test.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/parse/kernel_test.py
Labels: ready to be merged

#516 [PSyIR] Add support for the WHERE construct (for #497)
  changelog
  doc/developer_guide/developers.rst
  psyclone.pdf
  src/psyclone/psyGen.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/extract_test.py
  src/psyclone/tests/nemo/transformations/openacc/kernels_directive_test.py
  src/psyclone/tests/nemo/transformations/profiling/nemo_profile_test.py
  src/psyclone/tests/profile_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/frontend/where_handler_test.py
  src/psyclone/tests/transformations_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#545 #543 and #544 Parameter attributes and resolution of deferred types
  changelog
  doc/developer_guide/developers.rst
  doc/user_guide/psyir.rst
  psyclone.pdf
  src/psyclone/generator.py
  src/psyclone/gocean1p0.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/backend/c.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/backend/opencl.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/symbols/__init__.py
  src/psyclone/psyir/symbols/containersymbol.py
  src/psyclone/psyir/symbols/datasymbol.py
  src/psyclone/psyir/symbols/symbol.py
  src/psyclone/psyir/symbols/symboltable.py
  src/psyclone/tests/dynamo0p3_transformations_test.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/gocean1p0_opencl_test.py
  src/psyclone/tests/kernel_transformation_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/backend/c_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/backend/opencl_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/symbols/containersymbol_test.py
  src/psyclone/tests/psyir/symbols/datasymbol_test.py
  src/psyclone/tests/psyir/symbols/symboltable_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#559 483 create inlined kernel
  changelog
  psyclone.pdf
  src/psyclone/nemo.py
  src/psyclone/psyGen.py
  src/psyclone/tests/nemo/nemo_parse_test.py
  src/psyclone/tests/nemo/nemo_psy_test.py
  src/psyclone/tests/nemo/test_files/explicit_do_two_loops.f90
  src/psyclone/tests/nemo/transformations/loops/loop_test.py
  src/psyclone/tests/nemo/transformations/openacc/data_directive_test.py
  src/psyclone/tests/nemo/transformations/openmp/openmp_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/backend/psyir_openmp_test.py
  src/psyclone/tests/utilities.py
  src/psyclone/tests/utilities_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#580 Add Schedules to ExtractNode and ProfileNode (for #542)
  changelog
  doc/user_guide/dag.png
  doc/user_guide/profiling.rst
  doc/user_guide/psy_layer.rst
  doc/user_guide/psyke.rst
  psyclone.pdf
  src/psyclone/extractor.py
  src/psyclone/profiler.py
  src/psyclone/psyGen.py
  src/psyclone/tests/extract_test.py
  src/psyclone/tests/profile_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#573 fix pytest strings (#438)
  changelog
  psyclone.pdf
  setup.py
  src/psyclone/tests/config_test.py
  src/psyclone/tests/core/access_info_test.py
  src/psyclone/tests/core/access_type_test.py
  src/psyclone/tests/dependency_test.py
  src/psyclone/tests/dynamo0p3_basis_test.py
  src/psyclone/tests/dynamo0p3_builtins_test.py
  src/psyclone/tests/dynamo0p3_cma_test.py
  src/psyclone/tests/dynamo0p3_lma_test.py
  src/psyclone/tests/dynamo0p3_multigrid_test.py
  src/psyclone/tests/dynamo0p3_quadrature_test.py
  src/psyclone/tests/dynamo0p3_stubgen_test.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/dynamo0p3_transformations_test.py
  src/psyclone/tests/extract_test.py
  src/psyclone/tests/f2pygen_test.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/gocean0p1_transformations_test.py
  src/psyclone/tests/gocean1p0_config_test.py
  src/psyclone/tests/gocean1p0_opencl_test.py
  src/psyclone/tests/gocean1p0_test.py
  src/psyclone/tests/gocean1p0_transformations_test.py
  src/psyclone/tests/kernel_transformation_test.py
  src/psyclone/tests/nemo/nemo_config_test.py
  src/psyclone/tests/nemo/nemo_psy_test.py
  src/psyclone/tests/nemo/transformations/loops/loop_test.py
  src/psyclone/tests/nemo/transformations/openacc/data_directive_test.py
  src/psyclone/tests/nemo/transformations/openacc/kernels_directive_test.py
  src/psyclone/tests/nemo/transformations/openacc/loop_directive_test.py
  src/psyclone/tests/nemo/transformations/openmp/openmp_test.py
  src/psyclone/tests/parse/kernel_test.py
  src/psyclone/tests/parse/parse_test.py
  src/psyclone/tests/profile_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/backend/c_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/backend/opencl_test.py
  src/psyclone/tests/psyir/backend/visitor_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/tools/dependency_tools_test.py
  src/psyclone/tests/stubgen_test.py
  src/psyclone/tests/transformations_test.py
  src/psyclone/tests/utilities_test.py
Labels: ready to be merged

#416 Support for non-ascii chars in PSy layer (for 408)
  .travis.yml
  changelog
  src/psyclone/generator.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/nemo/nemo_gen_test.py
  src/psyclone/tests/nemo/test_files/utf_char.f90
  src/psyclone/tests/test_files/gocean1p0/kernel_utf_char_mod.f90
  src/psyclone/tests/test_files/gocean1p0/test29_utf_chars.f90
Labels: ready to be merged

#591 584 allow for deferred interface
  changelog
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/backend/opencl.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/symbols/__init__.py
  src/psyclone/psyir/symbols/datasymbol.py
  src/psyclone/psyir/symbols/symboltable.py
  src/psyclone/tests/gocean1p0_opencl_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/backend/opencl_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/symbols/containersymbol_test.py
  src/psyclone/tests/psyir/symbols/datasymbol_test.py
  src/psyclone/tests/psyir/symbols/symboltable_test.py
Labels: ready to be merged

#602 Add include_self arg to ancestor() (for #597)
  changelog
  src/psyclone/psyGen.py
  src/psyclone/tests/extract_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/transformations.py
Labels: ready to be merged
