Repository stfc/PSyclone, pull requests merged in 2019-04, with the labels that each got.

#325 #321 add rules section to Kernel Transformations
  doc/transformations.rst
Labels: ready for review

#335 Fix pytest deprecated
  changelog
  psyclone.pdf
  src/psyclone/tests/conftest.py
  src/psyclone/tests/gocean1p0_opencl_test.py
  src/psyclone/tests/gocean1p0_transformations_test.py
  src/psyclone/tests/psyclone_test_utils.py
  src/psyclone/tests/utilities_test.py
Labels: enhancement, reviewed with actions

#318 Update Schedule hierarchy
  changelog
  doc/conf.py
  doc/developers.rst
  doc/distributed_memory.rst
  doc/dynamo0p3_topclasses.dot
  doc/dynamo0p3_topclasses.png
  doc/dynamo0p3_topclasses.svg
  doc/examples.rst
  doc/getting_going.rst
  doc/nemo.rst
  doc/profiling.rst
  doc/psy_layer.rst
  doc/transformations.rst
  psyclone.pdf
  src/psyclone/dynamo0p1.py
  src/psyclone/dynamo0p3.py
  src/psyclone/gocean0p1.py
  src/psyclone/gocean1p0.py
  src/psyclone/nemo.py
  src/psyclone/profiler.py
  src/psyclone/psyGen.py
  src/psyclone/tests/dynamo0p3_haloex_test.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/dynamo0p3_transformations_test.py
  src/psyclone/tests/extract_test.py
  src/psyclone/tests/gocean1p0_opencl_test.py
  src/psyclone/tests/gocean1p0_test.py
  src/psyclone/tests/gocean1p0_transformations_test.py
  src/psyclone/tests/nemo/nemo_psy_test.py
  src/psyclone/tests/profile_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/transformations.py
Labels: ready for review

#333 issue #332. Fix algorithm argument parsing
  changelog
  psyclone.pdf
  src/psyclone/parse/algorithm.py
  src/psyclone/tests/parse/algorithm_test.py
Labels: ready for review

#330 issue #317. use can not be added to a function.
  changelog
  doc/developers.rst
  psyclone.pdf
  src/psyclone/algGen.py
  src/psyclone/tests/alggen_test.py
Labels: under review

#341 337 fix match error in the algorithm layer
  src/psyclone/parse/algorithm.py
  src/psyclone/tests/parse/algorithm_test.py
Labels: under review

#306 Re-factor the handling of kernel/kernel-stub arguments
  doc/developers.rst
  src/psyclone/dynamo0p3.py
  src/psyclone/dynamo0p3_builtins.py
  src/psyclone/psyGen.py
  src/psyclone/tests/dynamo0p3_basis_test.py
  src/psyclone/tests/dynamo0p3_builtins_test.py
  src/psyclone/tests/dynamo0p3_cma_test.py
  src/psyclone/tests/dynamo0p3_haloex_test.py
  src/psyclone/tests/dynamo0p3_lma_test.py
  src/psyclone/tests/dynamo0p3_multigrid_test.py
  src/psyclone/tests/dynamo0p3_quadrature_test.py
  src/psyclone/tests/dynamo0p3_stubgen_test.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/psyGen_test.py
Labels: under review

#331 issue #319. Case insensitive match for kernel file names.
  changelog
  psyclone.pdf
  src/psyclone/parse/kernel.py
  src/psyclone/tests/parse/kernel_test.py
Labels: under review

#300 Issue #256 (partially) Add Return Stmt and UnaryOperations to PSyIR
  src/psyclone/psyGen.py
  src/psyclone/tests/nemo/nemo_psy_test.py
  src/psyclone/tests/psyGen_test.py
Labels: under review

#349 Fix handling of unicode characters in source (py36 and below).
  src/psyclone/parse/utils.py
  src/psyclone/tests/parse/utils_test.py
Labels: bug, under review

#334 issue #320. Remove gui code.
  README.uml
  changelog
  doc/dynamo0p3_topclasses.dot
  doc/dynamo0p3_topclasses.png
  doc/dynamo0p3_topclasses.svg
  psyclone.pdf
  src/psyclone/gui.py
  src/psyclone/psyGen.py
Labels: under review

#343 Add gocean examples of kernels with use statements
  changelog
  doc/examples.rst
  examples/check_examples
  examples/gocean/README
  examples/gocean/eg4/README
  examples/gocean/eg4/acc_transform.py
  examples/gocean/eg4/alg.f90
  examples/gocean/eg4/another_mod.f90
  examples/gocean/eg4/data_mod.f90
  examples/gocean/eg4/kern_call_kern_mod.f90
  examples/gocean/eg4/kern_nested_use_mod.f90
  examples/gocean/eg4/kern_use_var_mod.f90
  psyclone.pdf
Labels: in progress

#352 Make kernel parse-tree search case insensitive
  src/psyclone/parse/kernel.py
  src/psyclone/tests/parse/kernel_test.py
Labels: bug, ready for review

#338 Issue #336 Improve fparser to PSyIR array declarations processing
  changelog
  src/psyclone/psyGen.py
  src/psyclone/tests/psyGen_test.py
Labels: under review
