Repository stfc/PSyclone, pull requests merged in 2019-08, with the labels that each got.

#424 Variable Access API
  changelog
  doc/developer_guide/developers.rst
  examples/.gitignore
  psyclone.pdf
  src/psyclone/core/access_info.py
  src/psyclone/core/access_type.py
  src/psyclone/core/tests/access_info_test.py
  src/psyclone/core/tests/access_type_test.py
  src/psyclone/dynamo0p3.py
  src/psyclone/gocean1p0.py
  src/psyclone/nemo.py
  src/psyclone/psyGen.py
  src/psyclone/tests/dependency_test.py
  src/psyclone/tests/extract_test.py
  src/psyclone/tests/gocean1p0_opencl_test.py
  src/psyclone/tests/gocean1p0_test.py
  src/psyclone/tests/gocean1p0_transformations_test.py
  src/psyclone/tests/nemo/transformations/openmp/openmp_test.py
  src/psyclone/tests/profile_test.py
  src/psyclone/tests/test_files/gocean1p0/kernel_scalar_float.f90
Labels: bug, enhancement, under review

#464 Interface coding style
  changelog
  doc/developer_guide/_static/theme_overrides.css
  doc/developer_guide/coding-style.rst
  doc/developer_guide/conf.py
  doc/developer_guide/developers.rst
  doc/developer_guide/index.rst
  doc/developer_guide/interface_example.py
  psyclone.pdf
Labels: enhancement, under review

#454 New simplify walk
  changelog
  examples/.gitignore
  examples/dynamo/eg12/find_kernel.py
  examples/nemo/eg1/runme_openmp.py
  examples/nemo/eg2/omp_levels_trans.py
  examples/nemo/eg2/runme_openmp.py
  examples/nemo/eg3/kernel_utils.py
  examples/nemo/eg3/kernels_trans.py
  psyclone.pdf
  src/psyclone/dynamo0p3.py
  src/psyclone/gocean1p0.py
  src/psyclone/nemo.py
  src/psyclone/profiler.py
  src/psyclone/psyGen.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/dynamo0p3_transformations_test.py
  src/psyclone/tests/extract_test.py
  src/psyclone/tests/kernel_transformation_test.py
  src/psyclone/tests/nemo/nemo_psy_test.py
  src/psyclone/tests/nemo/transformations/loops/loop_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#400 Towards #385. PSyIR Fortran front-end Do_Constructs handler.
  .gitignore
  changelog
  doc/developer_guide/developers.rst
  examples/dynamo/eg12/colouring_and_omp.py
  examples/dynamo/eg3/colouring_and_omp.py
  examples/dynamo/eg9/colouring_and_omp.py
  examples/dynamo/scripts/colouring_and_omp.py
  examples/gocean/eg1/runme_loop_fuse.py
  examples/gocean/eg1/runme_openacc.py
  examples/gocean/eg1/runme_openmp.py
  examples/transformations/inline/module_inline_example.py
  psyclone.pdf
  src/psyclone/dynamo0p1.py
  src/psyclone/dynamo0p3.py
  src/psyclone/dynamo0p3_builtins.py
  src/psyclone/extractor.py
  src/psyclone/gocean0p1.py
  src/psyclone/gocean1p0.py
  src/psyclone/nemo.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/tests/dependency_test.py
  src/psyclone/tests/dynamo0p3_builtins_test.py
  src/psyclone/tests/dynamo0p3_lma_test.py
  src/psyclone/tests/dynamo0p3_quadrature_test.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/dynamo0p3_transformations_test.py
  src/psyclone/tests/extract_test.py
  src/psyclone/tests/gocean0p1_test.py
  src/psyclone/tests/gocean0p1_transformations_test.py
  src/psyclone/tests/gocean1p0_opencl_test.py
  src/psyclone/tests/gocean1p0_stencil_test.py
  src/psyclone/tests/gocean1p0_test.py
  src/psyclone/tests/gocean1p0_transformations_test.py
  src/psyclone/tests/kernel_transformation_test.py
  src/psyclone/tests/nemo/nemo_psy_test.py
  src/psyclone/tests/nemo/transformations/loops/loop_test.py
  src/psyclone/tests/nemo/transformations/openacc/data_directive_test.py
  src/psyclone/tests/nemo/transformations/openmp/openmp_test.py
  src/psyclone/tests/profile_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/transformations_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#469 Remove duplicate operator tests in LFRic API
  changelog
  src/psyclone/tests/dynamo0p3_lma_test.py
  src/psyclone/tests/dynamo0p3_test.py
Labels: ready for review

#479 Fix link to GungHo
  doc/user_guide/introduction.rst
Labels: under review
