Repository stfc/PSyclone, pull requests merged in 2019-06, with the labels that each got.

#389 Nemo config
  changelog
  config/psyclone.cfg
  doc/user_guide/api.rst
  doc/user_guide/configuration.rst
  psyclone.pdf
  src/psyclone/configuration.py
  src/psyclone/nemo.py
  src/psyclone/tests/nemo/nemo_config_test.py
  src/psyclone/transformations.py
Labels: enhancement, under review

#394 Fix graphviz detection
  changelog
  psyclone.pdf
  src/psyclone/tests/conftest.py
Labels: bug, under review

#387 Issue #249. OCLTrans() generates OpenCL kernels (also fixes fparser2 stmt_fns)
  changelog
  doc/developer_guide/developers.rst
  doc/user_guide/examples.rst
  doc/user_guide/transformations.rst
  examples/gocean/README
  examples/gocean/eg3/README
  examples/gocean/eg3/alg.f90
  examples/gocean/eg3/compute_cu_mod.f90
  examples/gocean/eg3/compute_h_mod.f90
  examples/gocean/eg3/compute_z_mod.f90
  psyclone.pdf
  setup.cfg
  src/psyclone/psyGen.py
  src/psyclone/tests/gocean1p0_opencl_test.py
  src/psyclone/tests/gocean1p0_transformations_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyclone_test_utils.py
  src/psyclone/tests/test_files/gocean1p0/boundary_conditions_ne_offset_mod.f90
  src/psyclone/tests/test_files/gocean1p0/kernel_scalar_int.f90
  src/psyclone/tests/test_files/gocean1p0/time_smooth_mod.f90
  src/psyclone/transformations.py
Labels: ready for review

#403 Autoapi reference guide
  changelog
  doc/developer_guide/conf.py
  doc/reference_guide/doxygen.config
  doc/reference_guide/pip_requirements.txt
  doc/reference_guide/source/conf.py
  doc/reference_guide/source/index.rst
  doc/user_guide/conf.py
  setup.py
  src/psyclone/dynamo0p3.py
Labels: under review

#404 Re-jig the Kernel class hierarchy (for #364)
  changelog
  doc/developer_guide/developers.rst
  doc/user_guide/nemo.rst
  doc/user_guide/profiling.rst
  doc/user_guide/psy_layer.rst
  doc/user_guide/psyke.rst
  examples/dynamo/README
  examples/dynamo/eg12/extract_kernel_with_transformations.py
  examples/dynamo/eg13/kernel_constants.py
  examples/dynamo/scripts/redundant_dofs.py
  examples/dynamo/scripts/redundant_setval_c.py
  examples/gocean/eg1/runme.py
  examples/gocean/eg1/runme_dag.py
  examples/gocean/eg2/acc_transform.py
  examples/gocean/eg4/acc_transform.py
  psyclone.pdf
  src/psyclone/dynamo0p1.py
  src/psyclone/dynamo0p3.py
  src/psyclone/gocean0p1.py
  src/psyclone/gocean1p0.py
  src/psyclone/nemo.py
  src/psyclone/parse/algorithm.py
  src/psyclone/psyGen.py
  src/psyclone/tests/dynamo0p3_cma_test.py
  src/psyclone/tests/dynamo0p3_quadrature_test.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/dynamo0p3_transformations_test.py
  src/psyclone/tests/gocean1p0_config_test.py
  src/psyclone/tests/gocean1p0_test.py
  src/psyclone/tests/kernel_transformation_test.py
  src/psyclone/tests/nemo/nemo_psy_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyclone_test_utils.py
  src/psyclone/transformations.py
Labels: under review

#297 Improved profiling support
  changelog
  doc/user_guide/profiling.rst
  lib/profiling/Makefile
  lib/profiling/README
  lib/profiling/dl_timer/Makefile
  lib/profiling/drhook/Makefile
  lib/profiling/drhook/drhook.f90
  lib/profiling/simple_timing/Makefile
  lib/profiling/template/Makefile
  psyclone.pdf
Labels: enhancement, ready for review

#413 Issue #441. Add methods for semantic navigation
  changelog
  doc/developer_guide/developers.rst
  psyclone.pdf
  src/psyclone/psyGen.py
  src/psyclone/tests/psyGen_test.py
Labels: ready for review

#376 issue 368 fortran kernel gen
  changelog
  doc/developer_guide/developers.rst
  examples/check_examples
  examples/dynamo/eg13/kernel_constants.py
  examples/dynamo/scripts/kernel_print.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/__init__.py
  src/psyclone/psyir/backend/__init__.py
  src/psyclone/psyir/backend/base.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/backend/base_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
Labels: under review
