Repository stfc/PSyclone, pull requests merged in 2019-10, with the labels that each got.

#511 Turn tests into a python module
  .gitignore
  changelog
  doc/developer_guide/developers.rst
  doc/developer_guide/system_specific_setup.rst
  doc/user_guide/getting_going.rst
  psyclone.pdf
  setup.py
  src/psyclone/core/tests/conftest.py
  src/psyclone/tests/__init__.py
  src/psyclone/tests/conftest.py
  src/psyclone/tests/core/access_info_test.py
  src/psyclone/tests/core/access_type_test.py
  src/psyclone/tests/dependency_test.py
  src/psyclone/tests/dynamo0p3_basis_test.py
  src/psyclone/tests/dynamo0p3_build.py
  src/psyclone/tests/dynamo0p3_builtins_test.py
  src/psyclone/tests/dynamo0p3_cma_test.py
  src/psyclone/tests/dynamo0p3_haloex_test.py
  src/psyclone/tests/dynamo0p3_lma_test.py
  src/psyclone/tests/dynamo0p3_multigrid_test.py
  src/psyclone/tests/dynamo0p3_quadrature_test.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/dynamo0p3_transformations_test.py
  src/psyclone/tests/extract_test.py
  src/psyclone/tests/f2pygen_test.py
  src/psyclone/tests/gocean1p0_build.py
  src/psyclone/tests/gocean1p0_config_test.py
  src/psyclone/tests/gocean1p0_opencl_test.py
  src/psyclone/tests/gocean1p0_stencil_test.py
  src/psyclone/tests/gocean1p0_test.py
  src/psyclone/tests/gocean1p0_transformations_test.py
  src/psyclone/tests/kernel_transformation_test.py
  src/psyclone/tests/profile_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/__init__.py
  src/psyclone/tests/psyir/backend/__init__.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/utilities.py
  src/psyclone/tests/utilities_test.py
Labels: ready to be merged

#517 sir if statements 513
  changelog
  doc/developer_guide/developers.rst
  examples/check_examples
  examples/nemo/README
  examples/nemo/README.md
  examples/nemo/eg4/README.md
  examples/nemo/eg4/if_example.f90
  psyclone.pdf
  src/psyclone/psyir/backend/sir.py
  src/psyclone/tests/psyir/backend/sir_test.py
Labels: ready to be merged

#522 For #519 - fix for adding profiling around a select case construct.
  changelog
  src/psyclone/profiler.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/nemo/transformations/profiling/nemo_profile_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/transformations.py
Labels: under review

#528 #484 first stab at CONTRIBUTING
  CONTRIBUTING.md
Labels: under review

#531 Add any_space_10 (for #455)
  changelog
  doc/user_guide/built_ins.rst
  doc/user_guide/dynamo0p3.rst
  psyclone.pdf
  src/psyclone/dynamo0p3.py
Labels: ready to be merged

#360 Document the rules for reference element properties (part of #150)
  changelog
  doc/user_guide/dynamo0p3.rst
  psyclone.pdf
Labels: ready to be merged

#518 393 container node
  changelog
  doc/developer_guide/developers.rst
  src/psyclone/gocean1p0.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/kernel_transformation_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#485 Dependency tools
  changelog
  doc/developer_guide/coding-style.rst
  doc/developer_guide/developers.rst
  psyclone.pdf
  src/psyclone/core/access_info.py
  src/psyclone/nemo.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/tools/__init__.py
  src/psyclone/psyir/tools/dependency_tools.py
  src/psyclone/tests/core/access_info_test.py
  src/psyclone/tests/dependency_test.py
  src/psyclone/tests/nemo/transformations/openmp/openmp_test.py
  src/psyclone/tests/psyir/tools/dependency_tools_test.py
Labels: ready to be merged

#515 Psyir support directives
  changelog
  psyclone.pdf
  setup.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/backend/base.py
  src/psyclone/psyir/backend/c.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/tests/.pylintrc
  src/psyclone/tests/config_test.py
  src/psyclone/tests/core/__init__.py
  src/psyclone/tests/core/access_info_test.py
  src/psyclone/tests/dynamo0p3_multigrid_test.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/gocean1p0_config_test.py
  src/psyclone/tests/gocean1p0_opencl_test.py
  src/psyclone/tests/nemo/.pylintrc
  src/psyclone/tests/nemo/__init__.py
  src/psyclone/tests/nemo/nemo_config_test.py
  src/psyclone/tests/parse/__init__.py
  src/psyclone/tests/parse/algorithm_test.py
  src/psyclone/tests/parse/parse_test.py
  src/psyclone/tests/profile_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/backend/c_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/backend/psyir_openmp_test.py
  src/psyclone/tests/psyir/backend/sir_test.py
  src/psyclone/tests/psyir/frontend/__init__.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/utilities.py
  src/psyclone/tests/utilities_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#534 container to fortran (#520)
  changelog
  psyclone.pdf
  src/psyclone/psyGen.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/tests/kernel_transformation_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/backend/psyir_openmp_test.py
Labels: ready to be merged

#548 Convert all README files in lib folder to Markdown and format properly.
  lib/README.md
  lib/profiling/README.md
  lib/profiling/dl_timer/README.md
  lib/profiling/nvidia/README.md
  lib/profiling/simple_timing/README
  lib/profiling/simple_timing/README.md
  lib/profiling/template/README.md
Labels: ready to be merged

#551 Fix test files path in builtins documentation file.
  changelog
  doc/user_guide/built_ins.rst
  psyclone.pdf
Labels: ready to be merged

#553 Rename base.py import psyclone.psyir.backend to visitor.py.
  changelog
  doc/developer_guide/developers.rst
  psyclone.pdf
  src/psyclone/psyir/backend/c.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/backend/opencl.py
  src/psyclone/psyir/backend/sir.py
  src/psyclone/psyir/backend/visitor.py
  src/psyclone/tests/psyir/backend/c_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/backend/opencl_test.py
  src/psyclone/tests/psyir/backend/sir_test.py
  src/psyclone/tests/psyir/backend/visitor_test.py
Labels: ready to be merged

#556 478 options for transformations
  changelog
  doc/user_guide/transformations.rst
  examples/.gitignore
  examples/dynamo/eg11/async_script.py
  examples/dynamo/eg13/kernel_constants.py
  examples/dynamo/eg6/omp_reprod_script.py
  examples/dynamo/eg8/redundant_script.py
  examples/dynamo/scripts/redundant_dofs.py
  examples/dynamo/scripts/redundant_setval_c.py
  examples/gocean/eg1/runme_openacc.py
  examples/gocean/eg2/acc_transform.py
  examples/gocean/eg4/acc_transform.py
  examples/nemo/eg3/kernel_utils.py
  examples/transformations/inline/module_inline_example.py
  psyclone.pdf
  src/psyclone/psyGen.py
  src/psyclone/tests/dynamo0p3_haloex_test.py
  src/psyclone/tests/dynamo0p3_transformations_test.py
  src/psyclone/tests/gocean1p0_transformations_test.py
  src/psyclone/tests/kernel_transformation_test.py
  src/psyclone/tests/nemo/transformations/openacc/data_directive_test.py
  src/psyclone/tests/nemo/transformations/openacc/kernels_directive_test.py
  src/psyclone/tests/nemo/transformations/openacc/loop_directive_test.py
  src/psyclone/tests/nemo/transformations/profiling/nemo_profile_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/transformations_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#558 #557 Removed 'code creation' code from visitor into the C and Fortran…
  changelog
  src/psyclone/psyir/backend/c.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/backend/visitor.py
Labels: ready to be merged, under review
