Repository stfc/PSyclone, pull requests merged in 2019-05, with the labels that each got.

#367 362 determine kernel args
  examples/check_examples
  examples/dynamo/README
  examples/dynamo/code/dg_matrix_vector_kernel_mod.F90
  examples/dynamo/code/gw_mixed_schur_preconditioner_alg_mod.x90
  examples/dynamo/code/matrix_vector_kernel_mod.F90
  examples/dynamo/eg12/find_kernel.py
  examples/dynamo/eg13/kernel_constants.py
  src/psyclone/dynamo0p3.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/dynamo0p3_transformations_test.py
  src/psyclone/tests/test_files/dynamo0p3/testkern_multi_anyw2.f90
  src/psyclone/transformations.py
Labels: ready for review

#347 Issue #256 (partially). fparser2ASTProcessor support for If Constructs
  changelog
  doc/developers.rst
  examples/nemo/eg3/kernel_utils.py
  psyclone.pdf
  src/psyclone/nemo.py
  src/psyclone/psyGen.py
  src/psyclone/tests/nemo/nemo_psy_test.py
  src/psyclone/tests/nemo/nemo_transform_test.py
  src/psyclone/tests/nemo/transformations/openacc/kernels_directive_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/transformations.py
Labels: under review

#365 Use PSyIR to identify NemoKernel (#361)
  changelog
  doc/examples.rst
  doc/nemo.rst
  psyclone.pdf
  src/psyclone/nemo.py
  src/psyclone/psyGen.py
  src/psyclone/tests/nemo/nemo_psy_test.py
  src/psyclone/tests/nemo/transformations/loops/loop_test.py
  src/psyclone/tests/nemo/transformations/openacc/data_directive_test.py
  src/psyclone/tests/nemo/transformations/openmp/openmp_test.py
  src/psyclone/tests/transformations_test.py
  src/psyclone/transformations.py
Labels: under review

#374 issue #369. Add constants to PSyIR symbol table
  changelog
  doc/developer_guide/developers.rst
  psyclone.pdf
  src/psyclone/psyGen.py
  src/psyclone/tests/dynamo0p3_transformations_test.py
  src/psyclone/tests/gocean1p0_opencl_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/transformations.py
Labels: under review

#383 Pylint Fixes
  changelog
  doc/developer_guide/developers.rst
  doc/user_guide/api.rst
  psyclone.pdf
  src/psyclone/alg_gen.py
  src/psyclone/expression.py
  src/psyclone/generator.py
  src/psyclone/line_length.py
  src/psyclone/profiler.py
  src/psyclone/psyGen.py
  src/psyclone/tests/.pylintrc
  src/psyclone/tests/alggen_test.py
  src/psyclone/tests/dynamo0p3_basis_test.py
  src/psyclone/tests/expression_test.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/gocean0p1_test.py
  src/psyclone/tests/gocean1p0_test.py
  src/psyclone/tests/profile_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/virtual_utils.py
Labels: enhancement, under review

#384 Support case default (towards #354)
  changelog
  doc/developer_guide/system_specific_setup.rst
  psyclone.pdf
  src/psyclone/psyGen.py
  src/psyclone/tests/psyGen_test.py
Labels: under review

#366 Add symbols from module use statements to the SymbolTable (for #323)
  changelog
  examples/gocean/eg4/data_mod.f90
  examples/gocean/eg4/kern_use_var_mod.f90
  psyclone.pdf
  setup.cfg
  src/psyclone/psyGen.py
  src/psyclone/tests/.pylintrc
  src/psyclone/tests/dynamo0p3_transformations_test.py
  src/psyclone/tests/gocean1p0_opencl_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/transformations.py
Labels: under review

#379 Issue #339. Make operators more robust and support some intrinsics
  changelog
  psyclone.pdf
  src/psyclone/psyGen.py
  src/psyclone/tests/psyGen_test.py
Labels: under review
