Repository stfc/PSyclone, pull requests merged in 2020-11, with the labels that each got.

#956 #955 Change directory structure to work better with inheritance.
  changelog
  doc/developer_guide/psy_data.rst
  doc/user_guide/examples.rst
  doc/user_guide/psyke.rst
  examples/gocean/eg6/Makefile
  lib/extract/netcdf/dl_esm_inf/Makefile
  lib/extract/netcdf/dl_esm_inf/README.md
  lib/extract/netcdf/dl_esm_inf/doxyfile
  lib/extract/netcdf/dl_esm_inf/kernel_data_netcdf.f90
  psyclone.pdf
Labels: PSyData, ready to be merged

#943 GOcean OpenCL generates an in-kernel boundary mask to fix arbitrary problem sizes issues (closes #923)
  changelog
  config/psyclone.cfg
  doc/user_guide/gocean1p0.rst
  doc/user_guide/transformations.rst
  psyclone.pdf
  src/psyclone/configuration.py
  src/psyclone/gocean1p0.py
  src/psyclone/psyGen.py
  src/psyclone/tests/gocean1p0_config_test.py
  src/psyclone/tests/gocean1p0_opencl_test.py
Labels: ready for review, ready to be merged

#953 Correct RegionTrans.validate to always work on list of nodes (closes #952)
  changelog
  src/psyclone/psyir/transformations/region_trans.py
  src/psyclone/tests/psyir/transformations/region_trans_test.py
  src/psyclone/tests/psyir/transformations/transformations_test.py
Labels: ready to be merged, tutorial

#965 Create python-package.yml
  .github/workflows/python-package.yml
  changelog
  src/psyclone/dynamo0p3.py
Labels: ready to be merged

#975 972 - fix str(err) -> str(err.value)
  changelog
  psyclone.pdf
  src/psyclone/tests/psyir/symbols/datatype_test.py
  src/psyclone/tests/psyir/symbols/typesymbol_test.py
Labels: bug, ready to be merged

#977 #976 Fix dimension parameter for jinja templates
  changelog
  lib/extract/netcdf/dl_esm_inf/Makefile
  lib/process.py
  lib/read_only/Makefile
  psyclone.pdf
Labels: PSyData, bug, ready to be merged

#981 (closes #980) mv jupyter tutorials and update various docs
  README.md
  changelog
  doc/developer_guide/index.rst
  doc/user_guide/tutorial.rst
  psyclone.pdf
  tutorial/notebooks/fparser2/parsing_fortran.ipynb
  tutorial/notebooks/introduction.ipynb
  tutorial/notebooks/nemo/nemo_example1.ipynb
  tutorial/notebooks/nemo/nemo_example2.ipynb
  tutorial/notebooks/nemo/nemo_example3.ipynb
  tutorial/notebooks/nemo/nemo_example4.ipynb
  tutorial/notebooks/psyir/psyir_example1.ipynb
  tutorial/notebooks/psyir/psyir_example2.ipynb
Labels: ready to be merged, tutorial

#958 Ensure OMP/ACC Loop checks for parent region in NEMO API (closes #957)
  changelog
  src/psyclone/psyGen.py
  src/psyclone/tests/domain/gocean/transformations/gocean1p0_transformations_test.py
  src/psyclone/tests/nemo/transformations/openacc/loop_directive_test.py
  src/psyclone/tests/nemo/transformations/openmp/openmp_test.py
Labels: bug, ready to be merged, tutorial

#970 955 jinja for extraction
  changelog
  doc/developer_guide/psy_data.rst
  lib/extract/netcdf/.gitignore
  lib/extract/netcdf/Makefile
  lib/extract/netcdf/dl_esm_inf/Makefile
  lib/extract/netcdf/dl_esm_inf/kernel_data_netcdf.f90
  lib/extract/netcdf/extract_netcdf_base.jinja
  lib/psy_data_base.jinja
  lib/read_only/read_only_base.jinja
  psyclone.pdf
Labels: GOcean, PSyData, ready to be merged, tutorial

#989 905 nan test
  changelog
  config/psyclone.cfg
  doc/user_guide/psy_data.rst
  lib/nan_test/.gitignore
  lib/nan_test/Makefile
  lib/nan_test/dl_esm_inf/Makefile
  lib/nan_test/dl_esm_inf/nan_test.f90
  lib/nan_test/lfric/.gitignore
  lib/nan_test/lfric/Makefile
  lib/nan_test/lfric/nan_test.jinja
  lib/nan_test/nan_test_base.jinja
  psyclone.pdf
  src/psyclone/psyir/nodes/__init__.py
  src/psyclone/psyir/nodes/nan_test_node.py
  src/psyclone/psyir/nodes/node.py
  src/psyclone/psyir/transformations/__init__.py
  src/psyclone/psyir/transformations/nan_test_trans.py
  src/psyclone/tests/psyir/transformations/nan_test.py
Labels: PSyData, ready to be merged, tutorial

#961 lfric distributed memory tutorial (closes issue #936)
  .github/workflows/python-package.yml
  .travis.yml
  changelog
  tutorial/practicals/LFRic/Makefile
  tutorial/practicals/LFRic/distributed_memory/1_distributed_memory/Makefile
  tutorial/practicals/LFRic/distributed_memory/1_distributed_memory/README.md
  tutorial/practicals/LFRic/distributed_memory/1_distributed_memory/schedule.py
  tutorial/practicals/LFRic/distributed_memory/2_annexed_dofs/Makefile
  tutorial/practicals/LFRic/distributed_memory/2_annexed_dofs/README.md
  tutorial/practicals/LFRic/distributed_memory/2_annexed_dofs/psyclone.cfg
  tutorial/practicals/LFRic/distributed_memory/2_annexed_dofs/schedule.py
  tutorial/practicals/LFRic/distributed_memory/3_overlapping_comms/Makefile
  tutorial/practicals/LFRic/distributed_memory/3_overlapping_comms/README.md
  tutorial/practicals/LFRic/distributed_memory/3_overlapping_comms/psyclone.cfg
  tutorial/practicals/LFRic/distributed_memory/3_overlapping_comms/schedule.py
  tutorial/practicals/LFRic/distributed_memory/3_overlapping_comms/solutions/overlap_generic.py
  tutorial/practicals/LFRic/distributed_memory/3_overlapping_comms/solutions/overlap_specific.py
  tutorial/practicals/LFRic/distributed_memory/4_reductions/Makefile
  tutorial/practicals/LFRic/distributed_memory/4_reductions/README.md
  tutorial/practicals/LFRic/distributed_memory/4_reductions/helmholtz_solver_alg_mod.x90
  tutorial/practicals/LFRic/distributed_memory/4_reductions/schedule.py
  tutorial/practicals/LFRic/distributed_memory/code/apply_variable_hx_kernel_mod.F90
  tutorial/practicals/LFRic/distributed_memory/code/enforce_bc_kernel_mod.F90
  tutorial/practicals/LFRic/distributed_memory/code/helmholtz_solver_alg_mod.x90
  tutorial/practicals/LFRic/distributed_memory/code/scaled_matrix_vector_kernel_mod.F90
Labels: LFRic, ready to be merged, tutorial

#985 lfric shared mem tutorial [closes 979]
  changelog
  src/psyclone/psyGen.py
  src/psyclone/tests/psyGen_test.py
  tutorial/practicals/LFRic/single_node/1_openmp/Makefile
  tutorial/practicals/LFRic/single_node/1_openmp/README.md
  tutorial/practicals/LFRic/single_node/1_openmp/helmholtz_solver_alg_mod.x90
  tutorial/practicals/LFRic/single_node/1_openmp/omp_script.py
  tutorial/practicals/LFRic/single_node/1_openmp/psyclone.cfg
  tutorial/practicals/LFRic/single_node/1_openmp/solutions/omp_script.py
  tutorial/practicals/LFRic/single_node/2_openacc/Makefile
  tutorial/practicals/LFRic/single_node/2_openacc/README.md
  tutorial/practicals/LFRic/single_node/2_openacc/acc_parallel.py
  tutorial/practicals/LFRic/single_node/2_openacc/solutions/acc_parallel.py
  tutorial/practicals/LFRic/single_node/3_sequential/Makefile
  tutorial/practicals/LFRic/single_node/3_sequential/README.md
  tutorial/practicals/LFRic/single_node/3_sequential/example_alg.x90
  tutorial/practicals/LFRic/single_node/3_sequential/kernel_constants.py
  tutorial/practicals/LFRic/single_node/3_sequential/loop_fuse.py
  tutorial/practicals/LFRic/single_node/3_sequential/matvec_opt.py
  tutorial/practicals/LFRic/single_node/code/apply_variable_hx_kernel_mod.F90
  tutorial/practicals/LFRic/single_node/code/enforce_bc_kernel_mod.F90
  tutorial/practicals/LFRic/single_node/code/helmholtz_solver_alg_mod.x90
  tutorial/practicals/LFRic/single_node/code/scaled_matrix_vector_kernel_mod.F90
Labels: ready to be merged, tutorial

#1007 Fix incorrect variable name in tutorial README file. (closes #1005)
  tutorial/practicals/LFRic/single_node/3_sequential/README.md
Labels: LFRic, ready for review, tutorial

#1000 988 add dependencies
  changelog
  psyclone.pdf
  tutorial/practicals/LFRic/building_code/3_time_evolution/gungho_lib/Makefile
  tutorial/practicals/LFRic/building_code/4_psydata/gungho_lib/Makefile
Labels: LFRic, bug, ready to be merged, tutorial
