Repository stfc/PSyclone, pull requests merged in 2020-10, with the labels that each got.

#914 Add section on Exceptions to coding-style (closes #897)
  changelog
  doc/developer_guide/coding-style.rst
  psyclone.pdf
Labels: ready to be merged

#878 832 2 use jinja for profile
  changelog
  doc/developer_guide/psy_data.rst
  examples/gocean/eg5/Makefile
  lib/process.py
  lib/profiling/dl_timer/Makefile
  lib/profiling/dl_timer/README.md
  lib/profiling/dl_timer/dl_timer.f90
  lib/profiling/drhook/Makefile
  lib/profiling/drhook/README.md
  lib/profiling/drhook/drhook_psy.f90
  lib/profiling/simple_timing/Makefile
  lib/profiling/simple_timing/README.md
  lib/profiling/simple_timing/simple_timing.f90
  lib/profiling/template/Makefile
  lib/profiling/template/README.md
  lib/profiling/template/dummy_lib.f90
  psyclone.pdf
Labels: enhancement, ready to be merged

#915 Create "use" statements for data structures in LFRic PSy modules only when needed (for #908)
  changelog
  src/psyclone/dynamo0p3.py
  src/psyclone/tests/dynamo0p3_test.py
Labels: LFRic, ready to be merged

#922 Fix pycodestyle errors (closes #921)
  changelog
  src/psyclone/psyir/tools/dependency_tools.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/psyir/backend/visitor_test.py
  src/psyclone/tests/psyir/nodes/container_test.py
  src/psyclone/tests/psyir/symbols/symbol_test.py
  src/psyclone/tests/test_files/dummy_transformations.py
  src/psyclone/tests/test_files/dynamo0p3/error.py
  src/psyclone/tests/test_files/dynamo0p3/null_trans.py
  src/psyclone/tests/test_files/dynamo0p3/runtime_error.py
Labels: ready to be merged

#899 Introduce Routine class and have KernelSchedule subclass it.
  changelog
  doc/developer_guide/psyir.rst
  doc/developer_guide/psyir_backends.rst
  doc/developer_guide/transformations.rst
  doc/user_guide/psyir.rst
  examples/psyir/create.py
  psyclone.pdf
  src/psyclone/gocean1p0.py
  src/psyclone/nemo.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/backend/opencl.py
  src/psyclone/psyir/backend/sir.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/__init__.py
  src/psyclone/psyir/nodes/container.py
  src/psyclone/psyir/nodes/kernel_schedule.py
  src/psyclone/psyir/nodes/routine.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/backend/opencl_test.py
  src/psyclone/tests/psyir/frontend/fparser2_container_test.py
  src/psyclone/tests/psyir/frontend/fparser2_fortran_use_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/nodes/container_test.py
  src/psyclone/tests/psyir/nodes/kernel_schedule_test.py
  src/psyclone/tests/psyir/nodes/node_test.py
  src/psyclone/tests/psyir/nodes/reference_test.py
  src/psyclone/tests/psyir/nodes/routine_test.py
  src/psyclone/tests/psyir/nodes/test_range.py
  src/psyclone/tests/psyir/symbols/symbol_test.py
  src/psyclone/tests/psyir/symbols/symboltable_test.py
  src/psyclone/tests/psyir/transformations/arrayrange2loop_trans_test.py
  src/psyclone/tests/psyir/transformations/intrinsics/abs2code_trans_test.py
  src/psyclone/tests/psyir/transformations/intrinsics/matmul2code_trans_test.py
  src/psyclone/tests/psyir/transformations/intrinsics/min2code_trans_test.py
  src/psyclone/tests/psyir/transformations/intrinsics/sign2code_trans_test.py
  src/psyclone/transformations.py
Labels: PSyIR, ready to be merged

#932 #931 Fix dependency testing by falling back to variable access info if no symbol table is found
  changelog
  psyclone.pdf
  src/psyclone/psyir/tools/dependency_tools.py
  src/psyclone/tests/psyir/tools/dependency_tools_test.py
Labels: bug, ready to be merged

#930 halo exchange fix (closes #885)
  changelog
  src/psyclone/dynamo0p3.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/dynamo0p3_test.py
Labels: LFRic, bug, ready to be merged

#919 ref guide warnings (closes #916)
  changelog
  doc/reference_guide/source/conf.py
  src/psyclone/domain/lfric/function_space.py
  src/psyclone/domain/lfric/lfric_arg_descriptor.py
  src/psyclone/dynamo0p3.py
  src/psyclone/psyir/nodes/node.py
Labels: ready to be merged

#938 fix test_lookup_2 error
  changelog
  psyclone.pdf
  src/psyclone/tests/psyir/symbols/symboltable_test.py
Labels: ready for review, ready to be merged

#940 add encoding for python2
  changelog
  psyclone.pdf
  src/psyclone/generator.py
Labels: bug, ready to be merged

#942 Forbid parallel loop from containing CodeBlock (closes #941)
  changelog
  src/psyclone/tests/psyir/transformations/transformations_test.py
  src/psyclone/transformations.py
Labels: PSyIR, bug, ready to be merged, tutorial
