Repository stfc/PSyclone, pull requests merged in 2020-04, with the labels that each got.

#709 698 add target to psydata
  doc/user_guide/psy_data.rst
  examples/gocean/eg6/test.x90
  lib/extract/dl_esm_inf/netcdf/kernel_data_netcdf.f90
  lib/profiling/dl_timer/dl_timer.f90
  lib/profiling/drhook/drhook_psy.f90
  lib/profiling/nvidia/nvtx_prof.f90
  lib/profiling/simple_timing/simple_timing.f90
  lib/profiling/template/dummy_lib.f90
  src/psyclone/psyir/nodes/psy_data_node.py
  src/psyclone/tests/nemo/transformations/profiling/nemo_profile_test.py
  src/psyclone/tests/psyir/nodes/psy_data_node_test.py
  src/psyclone/tests/psyir/transformations/profile_test.py
Labels: ready to be merged

#729 Intents(in) for LFRic objects (for #712)
  changelog
  doc/bibliography/references.bib
  doc/user_guide/dynamo0p3.rst
  examples/lfric/code/dg_matrix_vector_kernel_mod.F90
  examples/lfric/code/gw_mixed_schur_preconditioner_alg_mod.x90
  examples/lfric/code/matrix_vector_kernel_mod.F90
  examples/lfric/eg1/psykal_lite.F90
  examples/lfric/eg1/v3_kernel_mod.F90
  examples/lfric/eg1/v3_solver_kernel_mod.F90
  examples/lfric/eg11/scaled_matrix_vector_kernel_mod.F90
  examples/lfric/eg2/dynamo_algorithm_mod.F90
  examples/lfric/eg2/matrix_vector_kernel_mod.F90
  examples/lfric/eg2/psykal_lite.F90
  examples/lfric/eg2/solver_mod.F90
  examples/lfric/eg2/v1_kernel_mod.F90
  examples/lfric/eg2/v2_kernel_mod.F90
  examples/lfric/eg2/v3_rhs_kernel_mod.F90
  examples/lfric/eg2/v3_solver_kernel_mod.F90
  examples/lfric/eg3/matrix_vector_mm_mod.F90
  examples/lfric/eg3/solver_mod.x90
  examples/lfric/eg3/w3_solver_kernel_mod.F90
  examples/lfric/eg4/enforce_bc_kernel_mod.f90
  examples/lfric/eg4/matrix_vector_kernel_mod.F90
  examples/lfric/eg4/mm_diagonal_kernel_mod.F90
  examples/lfric/eg4/solver_mod.x90
  examples/lfric/eg5/alg.f90
  examples/lfric/eg5/conservative_flux_kernel_mod.F90
  examples/lfric/eg5/subgrid_coeffs_kernel_mod.F90
  examples/lfric/eg6/alg.x90
  examples/lfric/eg7/columnwise_op_app_kernel_mod.F90
  examples/lfric/eg7/columnwise_op_asm_kernel_mod.F90
  examples/lfric/eg7/columnwise_op_mul_kernel_mod.F90
  examples/lfric/eg7/matrix_vector_kernel_mod.F90
  examples/lfric/eg8/apply_variable_hx_kernel_mod.F90
  examples/lfric/eg8/enforce_bc_kernel_mod.F90
  examples/lfric/eg8/helmholtz_solver_alg_mod.x90
  examples/lfric/eg8/scaled_matrix_vector_kernel_mod.F90
  examples/lfric/eg9/advective_inc_alg_mod.x90
  examples/lfric/eg9/matrix_vector_kernel_mod.F90
  examples/lfric/eg9/rtheta_kernel_mod.F90
  examples/lfric/eg9/rtheta_wtheta_kernel_mod.F90
  examples/lfric/eg9/sample_poly_adv_kernel_mod.F90
  psyclone.pdf
  src/psyclone/dynamo0p3.py
  src/psyclone/tests/dynamo0p3_basis_test.py
  src/psyclone/tests/dynamo0p3_builtins_test.py
  src/psyclone/tests/dynamo0p3_cma_test.py
  src/psyclone/tests/dynamo0p3_lma_test.py
  src/psyclone/tests/dynamo0p3_multigrid_test.py
  src/psyclone/tests/dynamo0p3_quadrature_test.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/psyGen_test.py
Labels: LFRic, ready for review

#739 Document LFRic mesh properties that kernels can request (towards 18)
  changelog
  doc/user_guide/dynamo0p3.rst
  psyclone.pdf
Labels: LFRic, ready to be merged

#743 #740 rm old, duplicate quadrature_mod file
  changelog
  psyclone.pdf
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/quadrature_mod.f90
Labels: LFRic, ready to be merged

#734 Support Wchi space (for #539)
  changelog
  doc/user_guide/dynamo0p3.rst
  doc/user_guide/examples.rst
  examples/lfric/README.md
  examples/lfric/eg3/w3_solver_kernel_mod.F90
  psyclone.pdf
  src/psyclone/dynamo0p3.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/dynamo0p3_basis_test.py
  src/psyclone/tests/dynamo0p3_quadrature_test.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/test_files/dynamo0p3/1.5.1_single_invoke_write_multi_fs.f90
  src/psyclone/tests/test_files/dynamo0p3/1.5_single_invoke_fs.f90
  src/psyclone/tests/test_files/dynamo0p3/14.3_halo_readers_all_fs.f90
  src/psyclone/tests/test_files/dynamo0p3/testkern_fs_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/testkern_stencil_fs_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/testkern_write_w2broken_w1_mod.f90
  src/psyclone/transformations.py
Labels: LFRic, ready to be merged
