Repository stfc/PSyclone, pull requests merged in 2021-11, with the labels that each got.

#1460 (closes #1454) domain kernel ncells fix
  changelog
  doc/user_guide/dynamo0p3.rst
  psyclone.pdf
  src/psyclone/domain/lfric/arg_ordering.py
  src/psyclone/domain/lfric/kern_call_arg_list.py
  src/psyclone/domain/lfric/kern_stub_arg_list.py
  src/psyclone/domain/lfric/kernel_interface.py
  src/psyclone/domain/lfric/lfric_builtins.py
  src/psyclone/dynamo0p3.py
  src/psyclone/tests/domain/lfric/arg_ordering_test.py
  src/psyclone/tests/domain/lfric/kernel_interface_test.py
  src/psyclone/tests/domain/lfric/lfric_builtins_test.py
  src/psyclone/tests/domain/lfric/lfric_domain_kernels_test.py
  src/psyclone/tests/dynamo0p3_cma_test.py
  src/psyclone/tests/test_files/dynamo0p3/25.3_multikern_domain_cma.f90
Labels: under review, ready to be merged, LFRic

#1463 1461 verify loop type in dep tools
  changelog
  doc/developer_guide/modules.rst
  psyclone.pdf
  src/psyclone/configuration.py
  src/psyclone/domain/nemo/nemo_constants.py
  src/psyclone/nemo.py
  src/psyclone/psyir/tools/dependency_tools.py
  src/psyclone/tests/config_test.py
  src/psyclone/tests/domain/constants_test.py
  src/psyclone/tests/domain/nemo/nodes/nemo_loop_test.py
  src/psyclone/tests/psyir/tools/dependency_tools_test.py
Labels: enhancement, ready to be merged

#1473 (Closes #1423) Blocking Loop transformation
  changelog
  doc/user_guide/transformations.rst
  psyclone.pdf
  src/psyclone/psyir/nodes/loop.py
  src/psyclone/psyir/transformations/__init__.py
  src/psyclone/psyir/transformations/chunk_loop_trans.py
  src/psyclone/tests/psyir/nodes/loop_test.py
  src/psyclone/tests/psyir/transformations/chunk_loop_trans_test.py
Labels: ready to be merged

#1470 (closes #1459) Refactor OMPLoopTrans and add OMPTargetTrans
  changelog
  doc/user_guide/examples.rst
  doc/user_guide/transformations.rst
  examples/nemo/README.md
  examples/nemo/eg1/Makefile
  examples/nemo/eg1/README.md
  examples/nemo/eg1/openmp_gpu_trans.py
  examples/nemo/eg1/openmp_trans.py
  psyclone.pdf
  src/psyclone/psyir/nodes/omp_directives.py
  src/psyclone/tests/domain/gocean/transformations/gocean1p0_transformations_test.py
  src/psyclone/tests/psyir/nodes/omp_directives_test.py
  src/psyclone/tests/psyir/transformations/transformations_test.py
  src/psyclone/transformations.py
Labels: ready to be merged, PSyIR

#1452 1451 fix doctests
  .github/workflows/python-package.yml
  changelog
  doc/developer_guide/coding-style.rst
  doc/developer_guide/dependency.rst
  doc/developer_guide/interface_example.py
  doc/developer_guide/modules.rst
  doc/developer_guide/parsing.rst
  doc/developer_guide/psy_data.rst
  doc/developer_guide/transformations.rst
  doc/developer_guide/working_practises.rst
  psyclone.pdf
  src/psyclone/domain/nemo/transformations/create_nemo_invoke_schedule_trans.py
  src/psyclone/domain/nemo/transformations/create_nemo_kernel_trans.py
  src/psyclone/domain/nemo/transformations/create_nemo_loop_trans.py
  src/psyclone/domain/nemo/transformations/create_nemo_psy_trans.py
  src/psyclone/parse/algorithm.py
  src/psyclone/parse/kernel.py
  src/psyclone/psyir/nodes/loop.py
  src/psyclone/psyir/transformations/psy_data_trans.py
  src/psyclone/transformations.py
Labels: enhancement, in progress, ready to be merged

#1503 #1502 Fixed incorrect path in tutorial README.
  changelog
  psyclone.pdf
  tutorial/practicals/README.md
Labels: bug, under review, ready to be merged, tutorial

#1489 (Closes #1488) configure MD link checker to skip links to MO wiki
  changelog
  doc/developer_guide/working_practises.rst
  mlc_config.json
  psyclone.pdf
Labels: under review, ready to be merged

#1501 (Closes #1484) Remove Py2 from GHA and update documentation
  .github/workflows/python-package.yml
  changelog
  doc/developer_guide/coding-style.rst
  doc/developer_guide/working_practises.rst
  doc/user_guide/getting_going.rst
  psyclone.pdf
  setup.cfg
  setup.py
  src/psyclone/dynamo0p3.py
  src/psyclone/generator.py
  src/psyclone/psyir/tools/dependency_tools.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/exceptions_test.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/parse/algorithm_test.py
  src/psyclone/tests/parse/utils_test.py
  src/psyclone/tests/psyad/main_test.py
  src/psyclone/tests/psyir/nodes/bound_intrinsic_op_test.py
Labels: ready to be merged

#1476 (closes #1456) Updates to PSyAD test harness to allow for precision.
  changelog
  doc/psyad/user_guide/implementation.rst
  doc/psyad/user_guide/psyad_command.rst
  examples/psyad/Makefile
  src/psyclone/psyad/main.py
  src/psyclone/psyad/tl2ad.py
  src/psyclone/tests/psyad/main_test.py
  src/psyclone/tests/psyad/tl2ad_test.py
Labels: ready to be merged, adjoint

#1482 (closes #1481) Rename symbol_from_tag to find_or_create_tag and add find_or_create (by name)
  changelog
  doc/developer_guide/psyir_symbols.rst
  examples/gocean/eg1/Makefile
  psyclone.pdf
  src/psyclone/domain/gocean/transformations/gocean_move_iteration_boundaries_inside_kernel_trans.py
  src/psyclone/domain/lfric/kern_call_arg_list.py
  src/psyclone/domain/lfric/kernel_interface.py
  src/psyclone/domain/lfric/lfric_builtins.py
  src/psyclone/domain/nemo/transformations/nemo_arrayaccess2loop_trans.py
  src/psyclone/domain/nemo/transformations/nemo_arrayrange2loop_trans.py
  src/psyclone/dynamo0p3.py
  src/psyclone/gocean1p0.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/psy_data_node.py
  src/psyclone/psyir/symbols/symboltable.py
  src/psyclone/psyir/transformations/chunk_loop_trans.py
  src/psyclone/tests/nemo/transformations/profiling/nemo_profile_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/symbols/symboltable_test.py
  src/psyclone/tests/psyir/transformations/chunk_loop_trans_test.py
Labels: ready to be merged, PSyIR

#1521 (closes #1193) replace python 3.5 with 3.6 in GHA and update docs
  .github/workflows/python-package.yml
  changelog
  doc/developer_guide/working_practises.rst
  doc/user_guide/getting_going.rst
  psyclone.pdf
Labels: ready to be merged

#1512 (closes #1511 and #1516) Test utility compile_file moves to tmpdir before compiling
  changelog
  src/psyclone/tests/domain/gocean/transformations/gocean_opencl_trans_test.py
  src/psyclone/tests/gocean1p0_test.py
  src/psyclone/tests/utilities.py
Labels: bug, ready to be merged

#1531 #1338 Found an error in documentation of taskwait (wrong module import)
  changelog
  psyclone.pdf
  src/psyclone/psyir/transformations/omp_taskwait_trans.py
  src/psyclone/transformations.py
Labels: ready to be merged

#1498 Add SymPy to PSyclone
  changelog
  doc/developer_guide/dependency.rst
  doc/developer_guide/index.rst
  doc/developer_guide/psy_data.rst
  doc/developer_guide/sympy.rst
  doc/developer_guide/transformations.rst
  doc/user_guide/getting_going.rst
  doc/user_guide/system_specific_setup.rst
  psyclone.pdf
  setup.py
  src/psyclone/core/__init__.py
  src/psyclone/core/symbolic_maths.py
  src/psyclone/domain/common/algorithm/psyir.py
  src/psyclone/domain/nemo/transformations/nemo_arrayaccess2loop_trans.py
  src/psyclone/domain/nemo/transformations/nemo_loop_fuse.py
  src/psyclone/psyad/transformations/assignment_trans.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/backend/sympy_writer.py
  src/psyclone/psyir/nodes/literal.py
  src/psyclone/psyir/nodes/node.py
  src/psyclone/psyir/nodes/operation.py
  src/psyclone/psyir/nodes/reference.py
  src/psyclone/psyir/tools/dependency_tools.py
  src/psyclone/psyir/transformations/arrayrange2loop_trans.py
  src/psyclone/tests/core/symbolic_maths_test.py
  src/psyclone/tests/dependency_test.py
  src/psyclone/tests/domain/common/algorithm/alg_psyir_test.py
  src/psyclone/tests/psyad/transformations/test_assignment_trans.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/backend/sympy_writer_test.py
  src/psyclone/tests/psyir/nodes/literal_test.py
  src/psyclone/tests/psyir/transformations/arrayrange2loop_trans_test.py
  src/psyclone/tests/psyir/transformations/loop_fusion_test.py
Labels: enhancement, ready to be merged
