Repository stfc/PSyclone, pull requests merged in 2021-08, with the labels that each got.

#1353 1324 structure support for c
  changelog
  doc/developer_guide/psyir_symbols.rst
  src/psyclone/core/signature.py
  src/psyclone/psyir/backend/c.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/backend/language_writer.py
  src/psyclone/psyir/backend/opencl.py
  src/psyclone/psyir/backend/sir.py
  src/psyclone/psyir/backend/visitor.py
  src/psyclone/tests/core/signature_test.py
  src/psyclone/tests/gocean1p0_opencl_test.py
  src/psyclone/tests/psyir/backend/c_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/backend/language_writer_test.py
Labels: enhancement, ready to be merged

#1358 (Towards 1338) Implementation of the taskloop directive
  changelog
  doc/user_guide/transformations.rst
  src/psyclone/f2pygen.py
  src/psyclone/psyir/nodes/__init__.py
  src/psyclone/psyir/nodes/omp_directives.py
  src/psyclone/tests/psyir/nodes/omp_directives_test.py
  src/psyclone/tests/psyir/transformations/transformations_test.py
  src/psyclone/transformations.py
Labels: ready to be merged, Task-based

#1369 1367 support real constants arguments in gocean
  changelog
  src/psyclone/gocean1p0.py
  src/psyclone/psyir/nodes/literal.py
  src/psyclone/tests/gocean1p0_test.py
  src/psyclone/tests/psyir/nodes/literal_test.py
Labels: ready to be merged

#1362 (closes #1361) Fix PSyIRGen bug and add unit tests for the class
  changelog
  psyclone.pdf
  src/psyclone/f2pygen.py
  src/psyclone/tests/f2pygen_test.py
Labels: bug, ready to be merged

#1344 (closes #1309) fix bug in name comparison in backend
  changelog
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/frontend/fparser2_generate_psyir_test.py
  src/psyclone/tests/psyir/frontend/fparser2_module_handler_test.py
  src/psyclone/tests/psyir/frontend/fparser2_subroutine_handler_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
Labels: ready to be merged, NEMO, PSyIR

#1341 (towards 1134) Move OpenCL transformation to GOcean transformations folder
  changelog
  doc/developer_guide/transformations.rst
  doc/user_guide/transformations.rst
  examples/gocean/eg1/opencl_transformation.py
  examples/gocean/eg3/README.md
  examples/gocean/eg3/ocl_trans.py
  examples/gocean/eg4/README.md
  examples/gocean/eg4/ocl_transform.py
  psyclone.pdf
  src/psyclone/domain/gocean/transformations/__init__.py
  src/psyclone/domain/gocean/transformations/gocean_opencl_trans.py
  src/psyclone/gocean1p0.py
  src/psyclone/tests/domain/gocean/transformations/gocean1p0_transformations_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean_opencl_trans_test.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/transformations.py
Labels: ready to be merged, GOcean

#1368 (Towards 1338) Implementation of OpenMP taskwait directive
  changelog
  psyclone.pdf
  src/psyclone/f2pygen.py
  src/psyclone/psyir/nodes/__init__.py
  src/psyclone/psyir/nodes/omp_directives.py
  src/psyclone/tests/psyir/backend/psyir_openmp_test.py
  src/psyclone/tests/psyir/nodes/omp_directives_test.py
Labels: ready to be merged, Task-based

#1282 (closes #871) Provide GOcean infrastructure read/write routines when generating OpenACC
  changelog
  psyclone.pdf
  src/psyclone/gocean1p0.py
  src/psyclone/psyir/nodes/__init__.py
  src/psyclone/psyir/nodes/acc_directives.py
  src/psyclone/tests/domain/gocean/transformations/gocean1p0_transformations_test.py
  src/psyclone/tests/psyir/nodes/acc_directives_test.py
Labels: ready to be merged, GOcean
