Repository stfc/PSyclone, pull requests merged in 2022-01, with the labels that each got.

#1485 (Closes #1429) Adds functionality to update argument intents to psyad
  changelog
  doc/psyad/user_guide/implementation.rst
  doc/psyad/user_guide/psyad_command.rst
  examples/psyad/eg1/Makefile
  examples/psyad/eg1/testkern_mod.f90
  src/psyclone/psyad/adjoint_visitor.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/symbols/symbol.py
  src/psyclone/tests/psyad/adjoint_visitor_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/symbols/symbol_test.py
Labels: ready to be merged, PSyIR, adjoint

#1228 Make gocean api work with PSyIR version of the algorithm layer (towards #753)
  changelog
  src/psyclone/domain/common/algorithm/psyir.py
  src/psyclone/domain/common/transformations/invokecall_trans.py
  src/psyclone/domain/lfric/algorithm/psyir.py
  src/psyclone/domain/lfric/transformations/lfric_invokecall_trans.py
  src/psyclone/domain/nemo/transformations/create_nemo_kernel_trans.py
  src/psyclone/generator.py
  src/psyclone/psyir/nodes/reference.py
  src/psyclone/tests/domain/common/algorithm/alg_psyir_test.py
  src/psyclone/tests/domain/common/transformations/invokecall_trans_test.py
  src/psyclone/tests/domain/lfric/algorithm/lfric_alg_psyir_test.py
  src/psyclone/tests/domain/lfric/transformations/lfric_invokecall_trans_test.py
Labels: ready to be merged, GOcean, PSyIR

#1526 (closes #1430) Fix array ranges in adjoint transformation
  changelog
  examples/psyad/eg2/Makefile
  examples/psyad/eg2/tl_hydrostatic_kernel_mod.F90
  src/psyclone/psyad/transformations/assignment_trans.py
  src/psyclone/tests/psyad/transformations/test_assignment_trans.py
Labels: ready to be merged, adjoint

#1500 (closes #1487) Improve NEMO arrayrange2loop transformation
  src/psyclone/domain/nemo/transformations/nemo_arrayrange2loop_trans.py
  src/psyclone/psyir/nodes/operation.py
  src/psyclone/tests/domain/nemo/transformations/nemo_arrayrange2loop_trans_test.py
  src/psyclone/tests/nemo/test_files/implicit_do_hidden_accessor.f90
  src/psyclone/tests/nemo/test_files/implicit_do_structures.f90
  src/psyclone/tests/psyir/nodes/operation_test.py
Labels: ready to be merged, NEMO

#1541 (closes #1513) Add a 2D Loop Tiling transformation
  changelog
  doc/user_guide/transformations.rst
  psyclone.pdf
  src/psyclone/psyir/transformations/__init__.py
  src/psyclone/psyir/transformations/chunk_loop_trans.py
  src/psyclone/psyir/transformations/loop_swap_trans.py
  src/psyclone/psyir/transformations/loop_tiling_2d_trans.py
  src/psyclone/tests/psyir/transformations/chunk_loop_trans_test.py
  src/psyclone/tests/psyir/transformations/loop_swap_trans_test.py
  src/psyclone/tests/psyir/transformations/loop_tiling_2d_trans_test.py
Labels: ready to be merged

#1533 1523 Add SymPy symbols for Fortran names
  changelog
  doc/developer_guide/conf.py
  doc/developer_guide/sympy.rst
  doc/reference_guide/source/conf.py
  doc/user_guide/conf.py
  psyclone.pdf
  src/psyclone/core/symbolic_maths.py
  src/psyclone/psyir/backend/sympy_writer.py
  src/psyclone/psyir/nodes/array_mixin.py
  src/psyclone/psyir/nodes/member.py
  src/psyclone/psyir/nodes/reference.py
  src/psyclone/tests/core/symbolic_maths_test.py
  src/psyclone/tests/domain/common/algorithm/alg_psyir_test.py
  src/psyclone/tests/psyir/backend/sympy_writer_test.py
  src/psyclone/tests/psyir/nodes/array_of_structures_reference_test.py
  src/psyclone/tests/psyir/nodes/array_reference_test.py
  src/psyclone/tests/psyir/nodes/member_test.py
  src/psyclone/tests/psyir/nodes/reference_test.py
Labels: ready to be merged

#1518 (closes #1506) Bug fixes for WHEREs involving array members of derived types
  changelog
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/array_mixin.py
  src/psyclone/psyir/nodes/node.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/frontend/fparser2_where_handler_test.py
  src/psyclone/tests/psyir/nodes/array_member_test.py
  src/psyclone/tests/psyir/nodes/array_reference_test.py
  src/psyclone/tests/psyir/nodes/container_test.py
  src/psyclone/tests/psyir/nodes/node_test.py
Labels: ready to be merged
