Repository stfc/PSyclone, pull requests merged in 2022-09, with the labels that each got.

#1819 (Close #1815) Prevent OMPTargetDirectives with Codeblocks
  changelog
  doc/user_guide/transformations.rst
  examples/nemo/eg1/openmp_gpu_trans.py
  psyclone.pdf
  src/psyclone/psyir/nodes/omp_directives.py
  src/psyclone/psyir/transformations/__init__.py
  src/psyclone/psyir/transformations/omp_target_trans.py
  src/psyclone/psyir/transformations/region_trans.py
  src/psyclone/tests/psyir/nodes/omp_directives_test.py
  src/psyclone/tests/psyir/transformations/omp_target_trans_test.py
  src/psyclone/tests/psyir/transformations/transformations_test.py
  src/psyclone/transformations.py
Labels: bug, ready to be merged, PSyIR

#1830 (closes #1828) Fixes to enable explicit OpenACC Loop parallelism with UM
  changelog
  src/psyclone/psyir/nodes/acc_directives.py
  src/psyclone/tests/alggen_test.py
  src/psyclone/tests/domain/common/extract_driver_creator_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean1p0_transformations_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean_extract_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean_opencl_trans_test.py
  src/psyclone/tests/domain/lfric/conftest.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/dynamo0p3_basis_test.py
  src/psyclone/tests/dynamo0p3_cma_test.py
  src/psyclone/tests/dynamo0p3_haloex_test.py
  src/psyclone/tests/dynamo0p3_lma_test.py
  src/psyclone/tests/dynamo0p3_multigrid_test.py
  src/psyclone/tests/dynamo0p3_quadrature_test.py
  src/psyclone/tests/dynamo0p3_stubgen_test.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/gocean1p0_stencil_test.py
  src/psyclone/tests/gocean1p0_test.py
  src/psyclone/tests/lfric_ref_elem_test.py
  src/psyclone/tests/nemo/nemo_config_test.py
  src/psyclone/tests/nemo/transformations/profiling/nemo_profile_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/nodes/acc_directives_test.py
  src/psyclone/tests/psyir/transformations/intrinsics/minormax2code_trans_test.py
Labels: enhancement, under review

#1855 1840 fix da crash array without indices
  changelog
  src/psyclone/psyir/tools/dependency_tools.py
  src/psyclone/tests/psyir/tools/dependency_tools_test.py
Labels: bug, ready to be merged

#1827 Support for SIR intrinsics (closes #1826)
  changelog
  doc/user_guide/examples.rst
  doc/user_guide/transformations.rst
  examples/nemo/eg4/Makefile
  examples/nemo/eg4/README.md
  examples/nemo/eg4/sir_trans_loop.py
  examples/nemo/eg4/tra_adv_compute.F90
  psyclone.pdf
  src/psyclone/psyir/backend/sir.py
  src/psyclone/tests/psyir/backend/sir_test.py
Labels: ready to be merged, SIR

#1844 (towards #1823) Fix LFRic ModuleInline issues with repeated kernels
  changelog
  src/psyclone/dynamo0p3.py
  src/psyclone/psyGen.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/psyGen_test.py
Labels: ready to be merged, LFRic

#1846 Fix assorted docstrings
  changelog
  doc/developer_guide/transformations.rst
  doc/developer_guide/working_practises.rst
  psyclone.pdf
  src/psyclone/psyir/nodes/node.py
  src/psyclone/transformations.py
Labels: ready to be merged

#1836 dotproducttrans fix (closes #1834)
  changelog
  psyclone.pdf
  src/psyclone/psyir/nodes/array_mixin.py
  src/psyclone/tests/psyad/transformations/test_assignment_trans.py
  src/psyclone/tests/psyir/nodes/array_mixin_test.py
  src/psyclone/tests/psyir/transformations/intrinsics/dotproduct2code_trans_test.py
  src/psyclone/tests/psyir/transformations/reference2arrayrange_trans_test.py
Labels: ready to be merged, adjoint

#1871 #1870 Fix incorrect link.
  changelog
  doc/user_guide/psyke.rst
  psyclone.pdf
Labels: bug, ready to be merged

#1875 (Closes #1874) rm pytest-pep257 from setup.py
  changelog
  setup.py
Labels: ready to be merged

#1860 Fix config file search locations (should fix #1538)
  .readthedocs.yaml
  changelog
  psyclone.pdf
  src/psyclone/configuration.py
  src/psyclone/tests/config_test.py
Labels: ready to be merged

#1768 Sum2CodeTrans transformation (closes 1711)
  changelog
  doc/user_guide/transformations.rst
  psyclone.pdf
  src/psyclone/psyir/transformations/__init__.py
  src/psyclone/psyir/transformations/intrinsics/operator2code_trans.py
  src/psyclone/psyir/transformations/intrinsics/sum2code_trans.py
  src/psyclone/tests/psyir/transformations/intrinsics/matmul2code_trans_test.py
  src/psyclone/tests/psyir/transformations/intrinsics/operator2code_trans_test.py
  src/psyclone/tests/psyir/transformations/intrinsics/sum2code_trans_test.py
Labels: ready to be merged, NEMO, PSyIR

#1890 (close #1889) Add kernel_outputdir fixture in test_kernel_module_name test
  changelog
  src/psyclone/tests/psyir/transformations/kernel_transformation_test.py
Labels: ready to be merged

#1850 (Towards #1799) add support for querying datatype of PSyIR references.
  changelog
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/array_mixin.py
  src/psyclone/psyir/nodes/array_of_structures_reference.py
  src/psyclone/psyir/nodes/array_reference.py
  src/psyclone/psyir/nodes/reference.py
  src/psyclone/psyir/nodes/structure_reference.py
  src/psyclone/psyir/symbols/datatypes.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/nodes/array_mixin_test.py
  src/psyclone/tests/psyir/nodes/array_of_structures_reference_test.py
  src/psyclone/tests/psyir/nodes/array_reference_test.py
  src/psyclone/tests/psyir/nodes/assignment_test.py
  src/psyclone/tests/psyir/nodes/reference_test.py
  src/psyclone/tests/psyir/nodes/structure_reference_test.py
  src/psyclone/tests/psyir/symbols/datatype_test.py
Labels: enhancement, ready to be merged, PSyIR

#1880 Improve support for function calls in the PSyIR (closes 1865)
  changelog
  psyclone.pdf
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/psyir/frontend/fparser2_part_ref_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
Labels: ready to be merged, PSyIR, adjoint

#1894 (Closes #1893) allow for references to UnknownType in is_upper/lower_bound
  changelog
  src/psyclone/psyir/nodes/array_mixin.py
  src/psyclone/tests/psyir/nodes/array_mixin_test.py
Labels: bug, under review
