Repository stfc/PSyclone, pull requests merged in 2022-07, with the labels that each got.

#1776 (Closes #1775) fixes post_region_code_gen and improves test fixtures.
  changelog
  src/psyclone/configuration.py
  src/psyclone/psyir/nodes/directive.py
  src/psyclone/tests/conftest.py
  src/psyclone/tests/gocean1p0_config_test.py
  src/psyclone/tests/nemo/nemo_config_test.py
  src/psyclone/tests/psyir/nodes/directive_test.py
  src/psyclone/tests/psyir/nodes/omp_directives_test.py
Labels: ready to be merged

#1784 (towards #1779) Remove API bounds from Range2Loop transformations
  changelog
  psyclone.pdf
  src/psyclone/domain/nemo/transformations/nemo_arrayrange2loop_trans.py
  src/psyclone/tests/domain/nemo/transformations/nemo_allarrayrange2loop_trans_test.py
  src/psyclone/tests/domain/nemo/transformations/nemo_arrayrange2loop_trans_test.py
  src/psyclone/tests/domain/nemo/transformations/nemo_outerarrayrange2loop_trans_test.py
Labels: ready to be merged

#1785 (Closes #1771) Refactor algorithm-creation functionality.
  changelog
  src/psyclone/domain/lfric/algorithm/__init__.py
  src/psyclone/domain/lfric/algorithm/alg_gen.py
  src/psyclone/domain/lfric/algorithm/lfric_alg.py
  src/psyclone/kernel_tools.py
  src/psyclone/tests/domain/lfric/algorithm/lfric_alg_test.py
  src/psyclone/tests/kernel_tools_test.py
Labels: ready to be merged, LFRic

#1769 unsupported rhs form with literal (closes 1721)
  changelog
  examples/psyad/eg1/testkern_mod.f90
  psyclone.pdf
  src/psyclone/core/symbolic_maths.py
  src/psyclone/psyad/transformations/assignment_trans.py
  src/psyclone/psyad/transformations/preprocess.py
  src/psyclone/tests/core/symbolic_maths_test.py
  src/psyclone/tests/psyad/transformations/test_assignment_trans.py
  src/psyclone/tests/psyad/transformations/test_preprocess.py
  src/psyclone/tests/psyir/backend/sympy_writer_test.py
Labels: ready to be merged, adjoint

#1778 1751 induction variables
  changelog
  doc/developer_guide/dependency.rst
  doc/user_guide/transformations.rst
  psyclone.pdf
  src/psyclone/psyir/transformations/__init__.py
  src/psyclone/psyir/transformations/replace_induction_variables_trans.py
  src/psyclone/tests/psyir/transformations/replace_induction_variables_trans_test.py
Labels: enhancement, ready to be merged

#1795 psyad unary minus fix [closes 1583]
  changelog
  doc/bibliography/references.bib
  psyclone.pdf
  src/psyclone/psyad/transformations/assignment_trans.py
  src/psyclone/tests/psyad/transformations/test_assignment_trans.py
Labels: ready to be merged, adjoint

#1809 Fix code style issues
  changelog
  examples/nemo/scripts/kernels_trans.py
  psyclone.pdf
  src/psyclone/domain/nemo/transformations/nemo_arrayrange2loop_trans.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/domain/nemo/transformations/nemo_allarrayrange2loop_trans_test.py
Labels: ready to be merged

#1803 1797 psydata logical support
  changelog
  doc/developer_guide/psy_data.rst
  examples/lfric/eg17/full_example_extract/main.x90
  examples/lfric/eg17/full_example_extract/testkern_w0_kernel_mod.f90
  lib/extract/netcdf/Makefile
  lib/extract/netcdf/extract_netcdf_base.jinja
  lib/extract/netcdf/lfric/Makefile
  lib/extract/netcdf/read_kernel_data_mod.jinja
  lib/nan_test/lfric/Makefile
  lib/nan_test/nan_test_base.jinja
  lib/process.py
  lib/read_only/lfric/Makefile
  lib/read_only/read_only_base.jinja
  psyclone.pdf
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/Makefile
Labels: enhancement, ready to be merged, PSyData
