Repository stfc/PSyclone, pull requests merged in 2022-04, with the labels that each got.

#1628 psyad unsupported rhs of expression (closes #1491).
  changelog
  doc/psyad/user_guide/implementation.rst
  examples/psyad/eg2/tl_hydrostatic_kernel_mod.F90
  psyclone.pdf
  src/psyclone/core/symbolic_maths.py
  src/psyclone/psyad/tl2ad.py
  src/psyclone/psyad/transformations/preprocess.py
  src/psyclone/psyad/utils.py
  src/psyclone/tests/core/symbolic_maths_test.py
  src/psyclone/tests/psyad/transformations/test_preprocess.py
  src/psyclone/tests/psyad/utils_test.py
Labels: ready to be merged, adjoint

#1666 (Towards #1618) add transformation to convert InvokeCall to Call.
  changelog
  doc/developer_guide/coding-style.rst
  doc/developer_guide/interface_example.py
  doc/developer_guide/transformations.rst
  src/psyclone/domain/common/algorithm/psyir.py
  src/psyclone/domain/common/transformations/__init__.py
  src/psyclone/domain/common/transformations/alg_invoke_2_psy_call_trans.py
  src/psyclone/domain/common/transformations/alg_trans.py
  src/psyclone/domain/common/transformations/raise_call_2_invoke_trans.py
  src/psyclone/domain/lfric/transformations/__init__.py
  src/psyclone/domain/lfric/transformations/lfric_alg_invoke_2_psy_call_trans.py
  src/psyclone/domain/lfric/transformations/lfric_alg_trans.py
  src/psyclone/domain/lfric/transformations/lfric_raise_call_2_invoke_trans.py
  src/psyclone/generator.py
  src/psyclone/tests/domain/common/algorithm/alg_psyir_test.py
  src/psyclone/tests/domain/common/transformations/alg_invoke_2_psy_call_trans_test.py
  src/psyclone/tests/domain/common/transformations/alg_trans_test.py
  src/psyclone/tests/domain/common/transformations/raise_call_2_invoke_trans_test.py
  src/psyclone/tests/domain/lfric/algorithm/lfric_alg_psyir_test.py
  src/psyclone/tests/domain/lfric/transformations/lfric_alg_invoke_2_psy_call_trans_test.py
  src/psyclone/tests/domain/lfric/transformations/lfric_alg_trans_test.py
  src/psyclone/tests/domain/lfric/transformations/lfric_raise_call_2_invoke_trans_test.py
Labels: ready to be merged, GOcean, LFRic, PSyIR, adjoint

#1656 (Closes 1649) node equality
  changelog
  doc/developer_guide/psyir.rst
  doc/user_guide/psyir.rst
  psyclone.pdf
  src/psyclone/core/access_info.py
  src/psyclone/dynamo0p3.py
  src/psyclone/psyir/nodes/acc_directives.py
  src/psyclone/psyir/nodes/call.py
  src/psyclone/psyir/nodes/codeblock.py
  src/psyclone/psyir/nodes/container.py
  src/psyclone/psyir/nodes/extract_node.py
  src/psyclone/psyir/nodes/literal.py
  src/psyclone/psyir/nodes/loop.py
  src/psyclone/psyir/nodes/member.py
  src/psyclone/psyir/nodes/node.py
  src/psyclone/psyir/nodes/omp_directives.py
  src/psyclone/psyir/nodes/operation.py
  src/psyclone/psyir/nodes/psy_data_node.py
  src/psyclone/psyir/nodes/reference.py
  src/psyclone/psyir/nodes/routine.py
  src/psyclone/psyir/nodes/scoping_node.py
  src/psyclone/psyir/transformations/omp_taskwait_trans.py
  src/psyclone/tests/domain/gocean/goloop_test.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/domain/lfric/transformations/lfric_extract_test.py
  src/psyclone/tests/gocean1p0_test.py
  src/psyclone/tests/nemo/nemo_psy_test.py
  src/psyclone/tests/psyir/nodes/acc_directives_test.py
  src/psyclone/tests/psyir/nodes/call_test.py
  src/psyclone/tests/psyir/nodes/codeblock_test.py
  src/psyclone/tests/psyir/nodes/container_test.py
  src/psyclone/tests/psyir/nodes/extract_node_test.py
  src/psyclone/tests/psyir/nodes/literal_test.py
  src/psyclone/tests/psyir/nodes/loop_test.py
  src/psyclone/tests/psyir/nodes/member_test.py
  src/psyclone/tests/psyir/nodes/node_test.py
  src/psyclone/tests/psyir/nodes/omp_directives_test.py
  src/psyclone/tests/psyir/nodes/operation_test.py
  src/psyclone/tests/psyir/nodes/psy_data_node_test.py
  src/psyclone/tests/psyir/nodes/reference_test.py
  src/psyclone/tests/psyir/nodes/routine_test.py
  src/psyclone/tests/psyir/nodes/scoping_node_test.py
  src/psyclone/tests/psyir/nodes/structure_member_test.py
  src/psyclone/tests/psyir/nodes/structure_reference_test.py
  src/psyclone/tests/psyir/transformations/loop_swap_trans_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#1680 Tidy up code in various places to avoid redundancy and switch to f-strings
  changelog
  examples/nemo/scripts/kernels_trans.py
  psyclone.pdf
  src/psyclone/nemo.py
  src/psyclone/psyir/nodes/acc_directives.py
  src/psyclone/tests/domain/gocean/transformations/gocean1p0_transformations_test.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/psyir/nodes/acc_directives_test.py
  src/psyclone/transformations.py
Labels: enhancement, ready to be merged

#1639 Extend PSyIR to support named arguments (closes #1630)
  changelog
  doc/developer_guide/psyir.rst
  doc/user_guide/psyir.rst
  examples/psyir/create.py
  psyclone.pdf
  src/psyclone/domain/common/transformations/raise_call_2_invoke_trans.py
  src/psyclone/domain/lfric/transformations/lfric_raise_call_2_invoke_trans.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/call.py
  src/psyclone/psyir/nodes/operation.py
  src/psyclone/tests/domain/common/transformations/raise_call_2_invoke_trans_test.py
  src/psyclone/tests/domain/lfric/transformations/lfric_raise_call_2_invoke_trans_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/frontend/fparser2_call_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/nodes/call_test.py
  src/psyclone/tests/psyir/nodes/operation_test.py
Labels: ready to be merged, NEMO, PSyIR

#1682 r_tran mixed precision support (closes #1632)
  changelog
  doc/developer_guide/APIs.rst
  doc/developer_guide/parsing.rst
  doc/user_guide/dynamo0p3.rst
  examples/lfric/eg19/algorithm.x90
  psyclone.pdf
  src/psyclone/domain/lfric/lfric_constants.py
  src/psyclone/dynamo0p3.py
  src/psyclone/tests/domain/lfric/lfric_dynamopsy_test.py
  src/psyclone/tests/domain/lfric/lfric_integer_builtins_test.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/parse/algorithm_test.py
  src/psyclone/tests/test_files/dynamo0p3/26.6.3_mixed_precision_rtran_vector.f90
  src/psyclone/tests/test_files/dynamo0p3/26.8_mixed_precision_args.f90
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/constants_mod.F90
Labels: under review, ready to be merged, LFRic

#1678 1667 add openacc compilation
  changelog
  examples/lfric/README.md
  examples/lfric/eg14/.gitignore
  examples/lfric/eg14/Makefile
  examples/lfric/eg14/README.md
  examples/lfric/eg14/acc_kernels.py
  examples/lfric/eg14/main.x90
  examples/lfric/eg14/testkern_w0_kernel_mod.f90
  psyclone.pdf
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/reference_element_mod.F90
  tutorial/practicals/LFRic/building_code/README.md
Labels: ready to be merged

#1676 (Closes #1643) Extend Matmul2CodeTrans to support matrix-matrix
  changelog
  psyclone.pdf
  src/psyclone/psyir/transformations/intrinsics/matmul2code_trans.py
  src/psyclone/tests/psyir/transformations/intrinsics/matmul2code_trans_test.py
Labels: ready to be merged, PSyIR, adjoint

#1699 Fix failing dynamopsy test by specifying dm=true explicitly.
  changelog
  doc/developer_guide/working_practises.rst
  src/psyclone/tests/conftest.py
  src/psyclone/tests/domain/lfric/lfric_dynamopsy_test.py
Labels: ready to be merged
