Repository stfc/PSyclone, pull requests merged in 2022-10, with the labels that each got.

#1900 (Closes #1893) allow for Symbol in is_upper/lower_bound
  changelog
  src/psyclone/psyir/nodes/array_mixin.py
  src/psyclone/tests/psyir/nodes/array_mixin_test.py
Labels: ready to be merged, WW3

#1782 (Closes #1496) Updated branch adding PSyAD test harness support
  changelog
  doc/psyad/user_guide/implementation.rst
  doc/psyad/user_guide/introduction.rst
  doc/psyad/user_guide/psyad_command.rst
  examples/psyad/README.md
  examples/psyad/eg2/Makefile
  examples/psyad/eg2/README.md
  src/psyclone/domain/lfric/algorithm/__init__.py
  src/psyclone/domain/lfric/algorithm/lfric_alg.py
  src/psyclone/domain/lfric/kern_call_invoke_arg_list.py
  src/psyclone/domain/lfric/psyir.py
  src/psyclone/psyad/domain/common/__init__.py
  src/psyclone/psyad/domain/common/adjoint_utils.py
  src/psyclone/psyad/domain/lfric/__init__.py
  src/psyclone/psyad/domain/lfric/generate_lfric_adjoint_harness.py
  src/psyclone/psyad/main.py
  src/psyclone/psyad/tl2ad.py
  src/psyclone/tests/domain/lfric/algorithm/lfric_alg_test.py
  src/psyclone/tests/domain/lfric/lfric_builtins_test.py
  src/psyclone/tests/psyad/domain/lfric/test_generate_lfric_adjoint_harness.py
  src/psyclone/tests/psyad/main_test.py
  src/psyclone/tests/psyad/tl2ad_test.py
Labels: ready to be merged, adjoint

#1906 (Closes #1896) Fix bug for parameter arrays in HoistLocalArraysTrans
  changelog
  src/psyclone/psyir/transformations/hoist_local_arrays_trans.py
  src/psyclone/tests/psyir/transformations/hoist_local_arrays_trans_test.py
Labels: bug, ready to be merged, WW3

#1884 Add support for inlining functions (closes #1882)
  changelog
  psyclone.pdf
  src/psyclone/psyir/transformations/inline_trans.py
  src/psyclone/tests/psyir/transformations/inline_trans_test.py
Labels: ready to be merged, adjoint

#1899 (towards #1823) refactor KernelModuleInlineTrans
  changelog
  doc/user_guide/transformations.rst
  examples/gocean/eg4/acc_transform.py
  examples/lfric/eg2/module_inline_trans.py
  psyclone.pdf
  src/psyclone/domain/common/transformations/__init__.py
  src/psyclone/domain/common/transformations/kernel_module_inline_trans.py
  src/psyclone/domain/gocean/transformations/gocean_opencl_trans.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/nodes/reference.py
  src/psyclone/psyir/nodes/routine.py
  src/psyclone/psyir/symbols/symbol.py
  src/psyclone/psyir/symbols/symbol_table.py
  src/psyclone/tests/domain/common/transformations/kernel_module_inline_trans_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean1p0_transformations_test.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/f2pygen_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/nodes/reference_test.py
  src/psyclone/tests/psyir/symbols/symbol_table_test.py
  src/psyclone/tests/psyir/symbols/symbol_test.py
  src/psyclone/tests/psyir/transformations/kernel_transformation_test.py
  src/psyclone/transformations.py
Labels: ready to be merged, GOcean, LFRic

#1852 1750 access info options
  changelog
  doc/developer_guide/dependency.rst
  psyclone.pdf
  src/psyclone/core/access_info.py
  src/psyclone/domain/gocean/transformations/gocean_extract_trans.py
  src/psyclone/domain/lfric/transformations/lfric_extract_trans.py
  src/psyclone/psyir/nodes/assignment.py
  src/psyclone/psyir/nodes/extract_node.py
  src/psyclone/psyir/nodes/nan_test_node.py
  src/psyclone/psyir/nodes/operation.py
  src/psyclone/psyir/nodes/psy_data_node.py
  src/psyclone/psyir/nodes/read_only_verify_node.py
  src/psyclone/psyir/nodes/reference.py
  src/psyclone/psyir/tools/dependency_tools.py
  src/psyclone/psyir/transformations/extract_trans.py
  src/psyclone/psyir/transformations/nan_test_trans.py
  src/psyclone/psyir/transformations/profile_trans.py
  src/psyclone/psyir/transformations/psy_data_trans.py
  src/psyclone/psyir/transformations/read_only_verify_trans.py
  src/psyclone/tests/core/access_info_test.py
  src/psyclone/tests/psyir/nodes/operation_test.py
  src/psyclone/tests/psyir/nodes/psy_data_node_test.py
  src/psyclone/tests/psyir/nodes/reference_test.py
  src/psyclone/tests/psyir/tools/dependency_tools_test.py
  src/psyclone/tests/psyir/transformations/extract_test.py
  src/psyclone/tests/psyir/transformations/psy_data_trans_test.py
Labels: enhancement, ready to be merged

#1867 1861 improve test coverage standalone
  changelog
  doc/developer_guide/working_practises.rst
  src/psyclone/expression.py
  src/psyclone/gocean1p0.py
  src/psyclone/tests/config_test.py
  src/psyclone/tests/conftest.py
  src/psyclone/tests/domain/common/extract_driver_creator_test.py
  src/psyclone/tests/domain/gocean/gocean_build_test.py
  src/psyclone/tests/domain/gocean/goinvokeschedule_test.py
  src/psyclone/tests/domain/gocean/goloop_test.py
  src/psyclone/tests/domain/gocean/kernel/go_kernel_arg_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean_extract_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean_opencl_trans_test.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/expression_test.py
  src/psyclone/tests/gocean1p0_test.py
  src/psyclone/tests/gocean_build.py
  src/psyclone/tests/kernel_tools_test.py
  src/psyclone/tests/lfric_build.py
  src/psyclone/tests/psyir/nodes/node_test.py
  src/psyclone/tests/psyir/transformations/kernel_transformation_test.py
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/Makefile
  src/psyclone/tests/utilities.py
  src/psyclone/tests/utilities_test.py
Labels: enhancement, ready to be merged

#1924 (Closes #1923) rm broken reference to KernelTrans in Dev Guide
  changelog
  doc/developer_guide/modules.rst
  doc/reference_guide/doxygen.config
  doc/reference_guide/source/conf.py
  src/psyclone/domain/common/transformations/__init__.py
Labels: ready to be merged

#1913 (closes #1848) Fix issues with symbol_table resolve_imports method
  changelog
  psyclone.pdf
  src/psyclone/psyir/symbols/symbol_table.py
  src/psyclone/tests/psyir/symbols/symbol_table_test.py
Labels: ready to be merged
