Repository stfc/PSyclone, pull requests merged in 2022-06, with the labels that each got.

#1729 Minor fixes for mlc and a CI test + Improvements for a package's initialisation
  .github/workflows/mlc_config.json
  changelog
  psyclone.pdf
  src/psyclone/psyir/transformations/__init__.py
  src/psyclone/psyir/transformations/intrinsics/dotproduct2code_trans.py
  src/psyclone/psyir/transformations/loop_fuse_trans.py
  src/psyclone/tests/generator_test.py
Labels: ready to be merged

#1679 Add limit arg to ancestor() and tidy Node module
  changelog
  doc/user_guide/psyir.rst
  psyclone.pdf
  src/psyclone/psyir/nodes/node.py
  src/psyclone/tests/psyir/nodes/node_test.py
Labels: enhancement, ready to be merged, PSyIR

#1749 Update fparser version to 0.0.15 in setup.py (for #1748)
  changelog
  setup.py
Labels: bug, ready to be merged, Release

#1747 psyad ifs [closes 1720]
  changelog
  doc/psyad/user_guide/implementation.rst
  doc/psyad/user_guide/introduction.rst
  psyclone.pdf
  src/psyclone/psyad/adjoint_visitor.py
  src/psyclone/tests/psyad/adjoint_visitor_test.py
Labels: ready to be merged, adjoint

#1669 (Closes #450) remove set_dirty/clean from ACC regions.
  changelog
  doc/user_guide/examples.rst
  doc/user_guide/transformations.rst
  examples/lfric/README.md
  examples/lfric/code/dg_matrix_vector_kernel_mod.F90
  examples/lfric/eg14/.gitignore
  examples/lfric/eg14/Makefile
  examples/lfric/eg14/README.md
  examples/lfric/eg14/acc_kernels.py
  examples/lfric/eg14/acc_parallel.py
  examples/lfric/eg14/acc_parallel_dm.py
  examples/lfric/eg14/testkern_w0_kernel_mod.f90
  psyclone.pdf
  src/psyclone/domain/lfric/kern_call_acc_arg_list.py
  src/psyclone/domain/lfric/kern_call_arg_list.py
  src/psyclone/dynamo0p3.py
  src/psyclone/psyir/nodes/acc_directives.py
  src/psyclone/psyir/nodes/directive.py
  src/psyclone/psyir/nodes/loop.py
  src/psyclone/psyir/nodes/omp_directives.py
  src/psyclone/tests/domain/gocean/transformations/gocean1p0_transformations_test.py
  src/psyclone/tests/domain/lfric/lfric_field_codegen_test.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/psyir/nodes/acc_directives_test.py
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/field_mod.F90
  src/psyclone/transformations.py
Labels: ready to be merged, LFRic

#1745 (towards #1731) Split PSyLoop node from Loop
  changelog
  doc/developer_guide/psyir.rst
  psyclone.pdf
  src/psyclone/domain/common/psylayer/__init__.py
  src/psyclone/domain/common/psylayer/psyloop.py
  src/psyclone/domain/nemo/transformations/create_nemo_invoke_schedule_trans.py
  src/psyclone/domain/nemo/transformations/create_nemo_kernel_trans.py
  src/psyclone/dynamo0p3.py
  src/psyclone/gocean1p0.py
  src/psyclone/nemo.py
  src/psyclone/psyir/nodes/loop.py
  src/psyclone/psyir/transformations/chunk_loop_trans.py
  src/psyclone/psyir/transformations/loop_fuse_trans.py
  src/psyclone/psyir/transformations/loop_trans.py
  src/psyclone/tests/domain/common/psylayer/psyloop_test.py
  src/psyclone/tests/domain/gocean/goloop_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean1p0_transformations_test.py
  src/psyclone/tests/domain/lfric/lfric_loop_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/nodes/loop_test.py
  src/psyclone/tests/psyir/transformations/loop_fusion_test.py
  src/psyclone/tests/psyir/transformations/loop_trans_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#1758 #1741 Split the read functionality into a stand-alone module.
  changelog
  doc/developer_guide/psy_data.rst
  examples/gocean/eg5/extract/Makefile
  lib/extract/netcdf/.gitignore
  lib/extract/netcdf/Makefile
  lib/extract/netcdf/extract_netcdf_base.jinja
  lib/extract/netcdf/read_kernel_data_mod.jinja
  psyclone.pdf
  src/psyclone/domain/common/extract_driver_creator.py
  src/psyclone/tests/domain/common/extract_driver_creator_test.py
Labels: enhancement, ready to be merged

#1766 Test code errors found by modified fparser (closes 1764)
  changelog
  psyclone.pdf
  src/psyclone/tests/nemo/test_files/array_valued_function.f90
  src/psyclone/tests/test_files/dynamo0p3/26.6.2_mixed_precision_rsolver_vector.f90
  src/psyclone/tests/test_files/dynamo0p3/26.6.3_mixed_precision_rtran_vector.f90
  src/psyclone/tests/test_files/dynamo0p3/26.6_mixed_precision_solver_vector.f90
  src/psyclone/tests/test_files/dynamo0p3/26.7_mixed_precision_abstract_solver_vector.f90
Labels: bug, ready to be merged

#1759 Remove FFLAGS, and use F90FLAGS in linking
  changelog
  examples/gocean/eg1/Makefile
  examples/gocean/eg2/Makefile
  examples/gocean/eg3/Makefile
  examples/gocean/eg3/README.md
  examples/gocean/eg4/Makefile
  examples/gocean/eg4/alg_kern_use_var.f90
  examples/gocean/eg5/extract/Makefile
  examples/gocean/eg5/nan/Makefile
  examples/gocean/eg5/readonly/Makefile
  psyclone.pdf
Labels: enhancement, ready to be merged

#1700 Improvements to the NEMO processing scripts
  changelog
  examples/nemo/scripts/kernels_trans.py
  examples/nemo/scripts/process_nemo.py
  psyclone.pdf
Labels: under review

#1762 (Closes #1743) ensure i_def declared in PSyAD test harness
  changelog
  doc/user_guide/getting_going.rst
  src/psyclone/psyad/tl2ad.py
  src/psyclone/psyir/symbols/typed_symbol.py
  src/psyclone/tests/psyad/tl2ad_test.py
Labels: ready to be merged, adjoint

#1774 Fix error in test code (closes 1773)
  changelog
  psyclone.pdf
  src/psyclone/tests/test_files/dynamo0p3/12.2_enforce_bc_kernel.f90
Labels: bug, ready to be merged

#1767 1739 incorrect access info
  changelog
  psyclone.pdf
  src/psyclone/domain/lfric/kern_call_arg_list.py
  src/psyclone/tests/dependency_test.py
  src/psyclone/tests/test_files/dynamo0p3/27.access_tests.f90
Labels: bug, ready to be merged

#1763 Fix invalid adjoint names for subroutine and module (closes #1717)
  changelog
  doc/psyad/user_guide/implementation.rst
  psyclone.pdf
  src/psyclone/psyad/tl2ad.py
  src/psyclone/tests/psyad/main_test.py
  src/psyclone/tests/psyad/tl2ad_test.py
Labels: ready to be merged, adjoint
