Repository stfc/PSyclone, pull requests merged in 2023-08, with the labels that each got.

#2240 Tweak PSyclone's OpenACC example script for NEMO
  changelog
  examples/nemo/scripts/kernels_trans.py
Labels: ready to be merged

#2182 (Closes #2179) Fix LFRic eg14 and add compilation of tests and examples with nvfortran
  .github/workflows/compilation.yml
  changelog
  doc/developer_guide/working_practises.rst
  doc/user_guide/examples.rst
  doc/user_guide/transformations.rst
  examples/lfric/README.md
  examples/lfric/eg14/Makefile
  examples/lfric/eg14/README.md
  examples/lfric/eg14/acc_parallel.py
  examples/lfric/eg14/main.x90
  examples/lfric/eg14/other_alg_mod.x90
  lib/extract/netcdf/Makefile
  lib/extract/standalone/Makefile
  lib/nan_test/lfric/Makefile
  psyclone.pdf
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/Makefile
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/field/field_r32_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/field/field_r64_mod.f90
  src/psyclone/tests/utilities_test.py
Labels: ready to be merged, LFRic

#2250 (#Closes 1575 and 2248) Change to line length module to avoid line continuation before any code
  changelog
  psyclone.pdf
  src/psyclone/line_length.py
  src/psyclone/tests/line_length_test.py
Labels: ready to be merged

#2270 (Closes #1575) Remove indentation if no other way to output valid fortran line.
  changelog
  psyclone.pdf
  src/psyclone/line_length.py
  src/psyclone/tests/line_length_test.py
Labels: ready to be merged, WW3

#2259 Add `gang` and `vector` clauses for OpenACC `loop` directives
  changelog
  psyclone.pdf
  src/psyclone/psyir/nodes/acc_directives.py
  src/psyclone/tests/nemo/transformations/openacc/loop_directive_test.py
  src/psyclone/tests/psyir/backend/psyir_openacc_test.py
  src/psyclone/tests/psyir/nodes/acc_directives_test.py
  src/psyclone/transformations.py
Labels: enhancement, ready to be merged

#2276 (closes #2274) Fix new pycodestyle issues
  changelog
  src/psyclone/domain/lfric/kernel/lfric_kernel_metadata.py
  src/psyclone/domain/lfric/metadata_to_arguments_rules.py
  src/psyclone/psyad/transformations/assignment_trans.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/omp_directives.py
  src/psyclone/psyir/symbols/symbol_table.py
  src/psyclone/psyir/transformations/intrinsics/sum2code_trans.py
  src/psyclone/tests/domain/lfric/kernel/lfric_kernel_metadata_test.py
  src/psyclone/tests/domain/lfric/lfric_builtins_test.py
  src/psyclone/tests/f2pygen_test.py
  src/psyclone/tests/line_length_test.py
  src/psyclone/tests/parse/kernel_test.py
  src/psyclone/tests/psyir/frontend/fparser2_find_or_create_symbol_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/nodes/omp_clause_test.py
  src/psyclone/tests/psyir/symbols/symbol_table_test.py
  src/psyclone/tests/psyir/transformations/reference2arrayrange_trans_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#2291 (Closes #2290) Add the appropriate interface into `RoutineSymbol` when doing `KernelModuleInlineTrans`
  changelog
  psyclone.pdf
  src/psyclone/domain/common/transformations/kernel_module_inline_trans.py
  src/psyclone/tests/domain/common/transformations/kernel_module_inline_trans_test.py
Labels: ready to be merged

#2238 (closes #2234) Use a generic interface comparison to cannonicalise select-case when the type is not known
  .github/workflows/nemo_tests.yml
  changelog
  doc/developer_guide/psyir.rst
  src/psyclone/line_length.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/psyir/frontend/fparser2_select_case_test.py
Labels: ready to be merged

#2292 #2288 Fix doctest failures by creating html docs first.
  .github/workflows/python-package.yml
  changelog
  psyclone.pdf
Labels: bug, ready to be merged

#2260 #2245 Splitting LFRicLoopBounds from dynamo0p3.py
  changelog
  psyclone.pdf
  src/psyclone/domain/lfric/__init__.py
  src/psyclone/domain/lfric/lfric_invoke.py
  src/psyclone/domain/lfric/lfric_loop_bounds.py
  src/psyclone/dynamo0p3.py
  src/psyclone/tests/domain/lfric/lfric_loop_bounds_test.py
Labels: ready to be merged

#2241 2215 allow lambda in sympy
  changelog
  src/psyclone/psyir/backend/sympy_writer.py
  src/psyclone/psyir/tools/dependency_tools.py
  src/psyclone/tests/core/symbolic_maths_test.py
  src/psyclone/tests/psyir/backend/sympy_writer_test.py
  src/psyclone/tests/psyir/tools/dependency_tools_test.py
Labels: ready to be merged, PSyIR
