Repository stfc/PSyclone, pull requests merged in 2023-02, with the labels that each got.

#2030 #1529 update eg19 Makefile so that compilation works
  changelog
  examples/lfric/eg19/.gitignore
  examples/lfric/eg19/Makefile
Labels: ready for review, under review, LFRic

#2029 (Closes #1567) correct visibility of imported symbols
  changelog
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/psyad/domain/lfric/test_lfric_adjoint.py
  src/psyclone/tests/psyir/backend/fortran_gen_decls_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/backend/fortran_unknown_declns_test.py
  src/psyclone/tests/psyir/frontend/fparser2_derived_type_test.py
  src/psyclone/tests/psyir/frontend/fparser2_generate_psyir_test.py
  src/psyclone/tests/psyir/frontend/fparser2_module_handler_test.py
  src/psyclone/tests/psyir/frontend/fparser2_subroutine_handler_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
Labels: bug, ready to be merged, NEMO, NEMOVAR

#2024 1984 field arrays in builtins
  changelog
  psyclone.pdf
  src/psyclone/domain/lfric/lfric_builtins.py
  src/psyclone/tests/domain/lfric/lfric_builtins_test.py
  src/psyclone/tests/test_files/dynamo0p3/15.1.8_a_plus_X_builtin_array_of_fields.f90
Labels: ready to be merged

#1980 1978 update lfric infrastructure and psydata
  changelog
  examples/gocean/eg3/.gitignore
  examples/lfric/eg11/.gitignore
  examples/lfric/eg19/.gitignore
  examples/lfric/eg19/Makefile
  examples/nemo/eg3/.gitignore
  examples/psyad/eg1/.gitignore
  examples/psyad/eg2/.gitignore
  lib/extract/netcdf/extract_netcdf_base.jinja
  lib/extract/netcdf/lfric/Makefile
  lib/extract/netcdf/lfric/kernel_data_netcdf.jinja
  lib/extract/netcdf/read_kernel_data_mod.jinja
  lib/extract/standalone/extract_standalone_base.jinja
  lib/extract/standalone/lfric/.gitignore
  lib/extract/standalone/lfric/Makefile
  lib/extract/standalone/lfric/kernel_data_standalone.jinja
  lib/extract/standalone/read_kernel_data_mod.jinja
  lib/nan_test/lfric/.gitignore
  lib/nan_test/lfric/Makefile
  lib/nan_test/lfric/nan_test.jinja
  lib/nan_test/nan_test_base.jinja
  lib/psy_data_base.jinja
  lib/read_only/lfric/.gitignore
  lib/read_only/lfric/Makefile
  lib/read_only/lfric/read_only.jinja
  lib/read_only/read_only_base.jinja
  psyclone.pdf
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/dependency
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/field/field_mod.F90
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/field/field_r32_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/field/field_r64_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/scalar/scalar_mod.F90
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/scalar/scalar_r32_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/scalar/scalar_r64_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/utilities/mpi_mod.f90
Labels: under review, ready to be merged, LFRic, PSyData

#2034 (Closes #1864) Add support for operator args to adjoint test-harness generation
  changelog
  doc/psyad/user_guide/implementation.rst
  src/psyclone/domain/lfric/algorithm/lfric_alg.py
  src/psyclone/domain/lfric/kern_call_invoke_arg_list.py
  src/psyclone/dynamo0p3.py
  src/psyclone/psyad/domain/lfric/lfric_adjoint_harness.py
  src/psyclone/tests/domain/lfric/conftest.py
  src/psyclone/tests/domain/lfric/kern_call_invoke_arg_list_test.py
  src/psyclone/tests/psyad/domain/lfric/test_lfric_adjoint_harness.py
  src/psyclone/tests/test_files/dynamo0p3/setop_random_kernel_mod.f90
Labels: ready to be merged, adjoint

#2036 2033 new split variables access info on master
  changelog
  doc/developer_guide/coding-style.rst
  doc/developer_guide/dependency.rst
  src/psyclone/core/__init__.py
  src/psyclone/core/single_variable_access_info.py
  src/psyclone/core/variables_access_info.py
  src/psyclone/domain/lfric/arg_ordering.py
  src/psyclone/domain/lfric/kern_call_acc_arg_list.py
  src/psyclone/domain/lfric/kern_call_arg_list.py
  src/psyclone/domain/lfric/kern_call_invoke_arg_list.py
  src/psyclone/domain/lfric/kern_stub_arg_list.py
  src/psyclone/domain/lfric/kernel_interface.py
  src/psyclone/domain/lfric/lfric_builtins.py
  src/psyclone/dynamo0p3.py
  src/psyclone/gocean1p0.py
  src/psyclone/nemo.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/nodes/assignment.py
  src/psyclone/psyir/nodes/ifblock.py
  src/psyclone/psyir/nodes/loop.py
  src/psyclone/psyir/nodes/node.py
  src/psyclone/psyir/nodes/operation.py
  src/psyclone/psyir/nodes/reference.py
  src/psyclone/psyir/symbols/symbol.py
  src/psyclone/psyir/tools/dependency_tools.py
  src/psyclone/tests/core/single_variable_access_info_test.py
  src/psyclone/tests/core/variables_access_info_test.py
  src/psyclone/tests/domain/lfric/arg_ordering_test.py
  src/psyclone/tests/dynamo0p3_haloex_test.py
  src/psyclone/tests/psyir/nodes/reference_test.py
Labels: ready to be merged

#2056 (closes #2055) Fix Reference2ArrayRange bug with deallocate statements
  changelog
  psyclone.pdf
  src/psyclone/psyir/transformations/reference2arrayrange_trans.py
  src/psyclone/tests/psyir/transformations/reference2arrayrange_trans_test.py
Labels: bug, ready to be merged, NEMO

#2047 (closes #2046) Add return statement to the lower_to_language_level methods
  changelog
  psyclone.pdf
  src/psyclone/domain/gocean/kernel/psyir.py
  src/psyclone/domain/lfric/algorithm/psyir/lfric_kernel_functor.py
  src/psyclone/domain/lfric/kernel/psyir.py
  src/psyclone/domain/lfric/lfric_builtins.py
  src/psyclone/dynamo0p3.py
  src/psyclone/gocean1p0.py
  src/psyclone/nemo.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/backend/visitor.py
  src/psyclone/psyir/nodes/acc_directives.py
  src/psyclone/psyir/nodes/extract_node.py
  src/psyclone/psyir/nodes/nan_test_node.py
  src/psyclone/psyir/nodes/node.py
  src/psyclone/psyir/nodes/omp_directives.py
  src/psyclone/psyir/nodes/psy_data_node.py
  src/psyclone/psyir/nodes/read_only_verify_node.py
  src/psyclone/tests/domain/gocean/kernel/gocean_kern_psyir_test.py
  src/psyclone/tests/domain/lfric/builtins/setval_random_test.py
  src/psyclone/tests/domain/lfric/kernel/lfric_kern_psyir_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/backend/visitor_test.py
  src/psyclone/tests/psyir/nodes/node_test.py
Labels: ready to be merged, PSyIR

#1973 (Closes #1904) fix inlining bugs with complex access expressions
  changelog
  doc/developer_guide/transformations.rst
  src/psyclone/psyir/nodes/array_mixin.py
  src/psyclone/psyir/nodes/array_reference.py
  src/psyclone/psyir/nodes/member.py
  src/psyclone/psyir/nodes/reference.py
  src/psyclone/psyir/nodes/structure_reference.py
  src/psyclone/psyir/symbols/symbol_table.py
  src/psyclone/psyir/transformations/inline_trans.py
  src/psyclone/tests/psyir/nodes/array_mixin_test.py
  src/psyclone/tests/psyir/nodes/array_reference_test.py
  src/psyclone/tests/psyir/nodes/member_test.py
  src/psyclone/tests/psyir/symbols/symbol_table_test.py
  src/psyclone/tests/psyir/transformations/inline_trans_test.py
Labels: ready to be merged, LFRic, NEMO, adjoint
