Repository stfc/PSyclone, pull requests merged in 2023-03, with the labels that each got.

#2044 1295 fix code execution on import
  changelog
  doc/developer_guide/psyir.rst
  examples/lfric/eg12/find_kernel.py
  examples/lfric/eg16/create.py
  psyclone.pdf
  src/psyclone/.pylintrc
  src/psyclone/configuration.py
  src/psyclone/domain/lfric/__init__.py
  src/psyclone/domain/lfric/algorithm/lfric_alg.py
  src/psyclone/domain/lfric/kern_call_arg_list.py
  src/psyclone/domain/lfric/kern_call_invoke_arg_list.py
  src/psyclone/domain/lfric/kernel_interface.py
  src/psyclone/domain/lfric/lfric_builtins.py
  src/psyclone/domain/lfric/lfric_constants.py
  src/psyclone/domain/lfric/lfric_symbol_table.py
  src/psyclone/domain/lfric/lfric_types.py
  src/psyclone/domain/lfric/psyir.py
  src/psyclone/dynamo0p3.py
  src/psyclone/generator.py
  src/psyclone/kernel_tools.py
  src/psyclone/psyad/domain/lfric/lfric_adjoint_harness.py
  src/psyclone/psyad/main.py
  src/psyclone/tests/config_test.py
  src/psyclone/tests/conftest.py
  src/psyclone/tests/domain/lfric/kern_call_arg_list_test.py
  src/psyclone/tests/domain/lfric/kernel_interface_test.py
  src/psyclone/tests/domain/lfric/lfric_builtins_test.py
  src/psyclone/tests/domain/lfric/lfric_constants_test.py
  src/psyclone/tests/domain/lfric/lfric_field_mdata_test.py
  src/psyclone/tests/domain/lfric/lfric_psyir_test.py
  src/psyclone/tests/domain/lfric/lfric_symbol_table_test.py
  src/psyclone/tests/domain/lfric/lfric_types_test.py
  src/psyclone/tests/dynkern_test.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/kernel_tools_test.py
  src/psyclone/tests/psyad/main_test.py
Labels: bug, ready to be merged, LFRic

#2066 (closes 1587) fast debug string method
  changelog
  doc/user_guide/psyir.rst
  psyclone.pdf
  src/psyclone/core/signature.py
  src/psyclone/domain/common/transformations/raise_psyir_2_alg_trans.py
  src/psyclone/domain/nemo/transformations/create_nemo_kernel_trans.py
  src/psyclone/domain/nemo/transformations/nemo_arrayaccess2loop_trans.py
  src/psyclone/domain/nemo/transformations/nemo_arrayrange2loop_trans.py
  src/psyclone/domain/nemo/transformations/nemo_loop_fuse.py
  src/psyclone/psyGen.py
  src/psyclone/psyad/adjoint_visitor.py
  src/psyclone/psyad/transformations/adjoint_trans.py
  src/psyclone/psyad/transformations/assignment_trans.py
  src/psyclone/psyir/backend/debug_writer.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/backend/sympy_writer.py
  src/psyclone/psyir/backend/visitor.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/array_mixin.py
  src/psyclone/psyir/nodes/node.py
  src/psyclone/psyir/nodes/structure_reference.py
  src/psyclone/psyir/transformations/hoist_trans.py
  src/psyclone/psyir/transformations/inline_trans.py
  src/psyclone/psyir/transformations/intrinsics/dotproduct2code_trans.py
  src/psyclone/psyir/transformations/intrinsics/sum2code_trans.py
  src/psyclone/psyir/transformations/omp_taskwait_trans.py
  src/psyclone/psyir/transformations/reference2arrayrange_trans.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyad/adjoint_visitor_test.py
  src/psyclone/tests/psyad/transformations/test_adjoint_trans.py
  src/psyclone/tests/psyir/backend/debug_writer_test.py
  src/psyclone/tests/psyir/backend/sympy_writer_test.py
  src/psyclone/tests/psyir/nodes/node_test.py
  src/psyclone/tests/psyir/transformations/omp_taskloop_transformations_test.py
Labels: ready to be merged

#1914 (Closes #1891) Catch implicit subroutine args and abort
  changelog
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/psyir/frontend/fparser2_subroutine_handler_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
Labels: ready to be merged, NEMO

#2067 Fix new metadata bugs (towards #1618)
  changelog
  psyclone.pdf
  src/psyclone/domain/lfric/kernel/meta_funcs_arg_metadata.py
  src/psyclone/domain/lfric/lfric_constants.py
  src/psyclone/domain/lfric/lfric_types.py
  src/psyclone/tests/domain/lfric/kernel/lfric_kernel_metadata_test.py
  src/psyclone/tests/domain/lfric/kernel/meta_funcs_arg_metadata_test.py
  src/psyclone/tests/domain/lfric/kernel/scalar_arg_metadata_test.py
Labels: ready to be merged, LFRic

#2068 Add while loop functionality
  changelog
  doc/developer_guide/psyir.rst
  doc/user_guide/psyir.rst
  psyclone.pdf
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/__init__.py
  src/psyclone/psyir/nodes/node.py
  src/psyclone/psyir/nodes/while_loop.py
  src/psyclone/tests/nemo/nemo_psy_test.py
  src/psyclone/tests/nemo/test_files/do_while.f90
  src/psyclone/tests/psyir/frontend/fparser2_do_handler_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/nodes/while_loop_test.py
Labels: ready to be merged

#2072 Assortment of tweaks following #2068
  changelog
  psyclone.pdf
  src/psyclone/psyir/nodes/__init__.py
  src/psyclone/psyir/nodes/if_block.py
  src/psyclone/psyir/nodes/loop.py
  src/psyclone/psyir/nodes/omp_directives.py
  src/psyclone/tests/psyir/nodes/if_block_test.py
Labels: ready to be merged

#2061 (towards 598) OpenMP lowering infers firstprivate clause for some cases
  changelog
  psyclone.pdf
  src/psyclone/psyir/nodes/node.py
  src/psyclone/psyir/nodes/omp_clauses.py
  src/psyclone/psyir/nodes/omp_directives.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/psyir/nodes/omp_clause_test.py
  src/psyclone/tests/psyir/nodes/omp_directives_test.py
  src/psyclone/tests/psyir/transformations/transformations_test.py
Labels: ready to be merged

#2059 2057 extraction for nemo
  changelog
  doc/user_guide/examples.rst
  doc/user_guide/psyke.rst
  examples/nemo/README.md
  examples/nemo/eg5/.gitignore
  examples/nemo/eg5/Makefile
  examples/nemo/eg5/README.md
  examples/nemo/eg5/domain_setup.sh
  examples/nemo/eg5/extract_kernels.py
  lib/extract/netcdf/Makefile
  lib/extract/netcdf/extract_netcdf_base.jinja
  lib/extract/netcdf/nemo/Makefile
  lib/extract/netcdf/nemo/README.md
  lib/extract/netcdf/nemo/kernel_data_netcdf.f90
  lib/extract/standalone/Makefile
  lib/extract/standalone/nemo/Makefile
  lib/extract/standalone/nemo/README.md
  lib/extract/standalone/nemo/kernel_data_standalone.f90
  psyclone.pdf
  src/psyclone/psyir/transformations/extract_trans.py
  src/psyclone/tests/domain/gocean/transformations/gocean_extract_test.py
  src/psyclone/tests/nemo/transformations/nemo_extract_test.py
Labels: ready to be merged, NEMO, PSyData

#2025 1483 lfric extraction driver test merge psyir
  changelog
  doc/developer_guide/psy_data.rst
  doc/user_guide/psyke.rst
  examples/lfric/eg17/full_example_extract/.gitignore
  examples/lfric/eg17/full_example_extract/Makefile
  examples/lfric/eg17/full_example_extract/extract_transform.py
  examples/lfric/eg17/full_example_extract/main.x90
  examples/lfric/eg17/full_example_extract/testkern_w0_kernel_mod.f90
  psyclone.pdf
  src/psyclone/domain/common/extract_driver_creator.py
  src/psyclone/domain/lfric/__init__.py
  src/psyclone/domain/lfric/arg_ordering.py
  src/psyclone/domain/lfric/lfric_extract_driver_creator.py
  src/psyclone/domain/lfric/transformations/lfric_extract_trans.py
  src/psyclone/dynamo0p3.py
  src/psyclone/psyGen.py
  src/psyclone/tests/domain/lfric/arg_ordering_test.py
  src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
  src/psyclone/tests/domain/lfric/transformations/lfric_extract_test.py
Labels: enhancement, ready to be merged, LFRic, PSyIR
