Repository stfc/PSyclone, pull requests merged in 2023-05, with the labels that each got.

#2118 (Closes #2117) Ensure build flags passed to LFRic infrastructure
  changelog
  examples/lfric/eg11/Makefile
  examples/lfric/eg17/full_example/Makefile
  examples/lfric/eg17/full_example_extract/Makefile
  examples/lfric/eg17/full_example_netcdf/Makefile
  examples/lfric/eg19/Makefile
  lib/extract/netcdf/lfric/Makefile
  lib/extract/standalone/lfric/Makefile
  src/psyclone/tests/lfric_build.py
  src/psyclone/tests/lfric_build_test.py
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/Makefile
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/lfric_include_flags.inc
  src/psyclone/tests/utilities_test.py
Labels: under review, LFRic

#2086 (Closes #2013) Support logical, scalar arguments in psyad test-harness generation
  changelog
  doc/psyad/user_guide/implementation.rst
  doc/psyad/user_guide/psyad_command.rst
  src/psyclone/domain/lfric/kern_call_invoke_arg_list.py
  src/psyclone/psyad/domain/lfric/lfric_adjoint_harness.py
  src/psyclone/tests/domain/lfric/conftest.py
  src/psyclone/tests/domain/lfric/kern_call_invoke_arg_list_test.py
  src/psyclone/tests/psyad/domain/lfric/test_lfric_adjoint_harness.py
Labels: ready to be merged, adjoint

#2123 Provide alternative link for GOcean project
  doc/user_guide/conf.py
  doc/user_guide/introduction.rst
Labels: under review, GOcean

#2128 multi-quadrature bug (towards #1618)
  changelog
  psyclone.pdf
  src/psyclone/domain/lfric/transformations/lfric_alg_invoke_2_psy_call_trans.py
  src/psyclone/tests/domain/lfric/transformations/lfric_alg_invoke_2_psy_call_trans_test.py
Labels: bug, ready to be merged, LFRic

#967 Enable testing using a self-hosted runner.
  .github/workflows/compilation.yml
  .github/workflows/repo-sync.yml
  changelog
  doc/developer_guide/working_practises.rst
  psyclone.pdf
Labels: in progress, ready to be merged

#2084 (Closes #1801) support assumed-shape arrays with specified lower bound
  changelog
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/symbols/datatypes.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/symbols/datatype_test.py
  src/psyclone/tests/psyir/transformations/arrayrange2loop_trans_test.py
  src/psyclone/tests/psyir/transformations/inline_trans_test.py
Labels: ready to be merged, NEMO

#2129 algorithm arguments fix (towards #1618)
  changelog
  psyclone.pdf
  src/psyclone/domain/common/transformations/alg_invoke_2_psy_call_trans.py
  src/psyclone/tests/domain/common/transformations/alg_invoke_2_psy_call_trans_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean_alg_invoke_2_psy_call_trans_test.py
Labels: ready to be merged, LFRic

#2133 (Closes #2126) add YAML config files to fix RTD builds
  changelog
  doc/developer_guide/.readthedocs.yaml
  doc/psyad/user_guide/.readthedocs.yaml
  doc/reference_guide/.readthedocs.yaml
  doc/user_guide/.readthedocs.yaml
Labels: ready to be merged

#2092 (Closes #2008) Refactor symbol interfaces and add Static/SAVE support
  changelog
  doc/developer_guide/psyir_symbols.rst
  doc/user_guide/psyir.rst
  psyclone.pdf
  src/psyclone/domain/gocean/transformations/gocean_opencl_trans.py
  src/psyclone/gocean1p0.py
  src/psyclone/psyGen.py
  src/psyclone/psyad/adjoint_visitor.py
  src/psyclone/psyad/tl2ad.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/backend/opencl.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/routine.py
  src/psyclone/psyir/symbols/__init__.py
  src/psyclone/psyir/symbols/containersymbol.py
  src/psyclone/psyir/symbols/interfaces.py
  src/psyclone/psyir/symbols/symbol.py
  src/psyclone/psyir/symbols/symbol_table.py
  src/psyclone/psyir/transformations/hoist_local_arrays_trans.py
  src/psyclone/psyir/transformations/inline_trans.py
  src/psyclone/tests/domain/common/transformations/kernel_module_inline_trans_test.py
  src/psyclone/tests/domain/gocean/kernel/go_kernel_arg_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean_const_loop_bounds_trans_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean_opencl_trans_test.py
  src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
  src/psyclone/tests/domain/lfric/lfric_types_test.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/gocean1p0_test.py
  src/psyclone/tests/psyad/adjoint_visitor_test.py
  src/psyclone/tests/psyir/backend/fortran_gen_decls_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/backend/fortran_unknown_declns_test.py
  src/psyclone/tests/psyir/frontend/fparser2_fortran_use_test.py
  src/psyclone/tests/psyir/frontend/fparser2_intrinsic_handler_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/symbols/datasymbol_test.py
  src/psyclone/tests/psyir/symbols/datatype_test.py
  src/psyclone/tests/psyir/symbols/interfaces_test.py
  src/psyclone/tests/psyir/symbols/symbol_table_test.py
  src/psyclone/tests/psyir/symbols/symbol_test.py
  src/psyclone/tests/psyir/transformations/inline_trans_test.py
Labels: ready to be merged

#2089 (closes #2005) flatten use stmts
  changelog
  examples/psyir/modify.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/symbols/symbol_table.py
  src/psyclone/psyir/transformations/inline_trans.py
  src/psyclone/tests/psyir/backend/fortran_routine_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/nodes/scoping_node_test.py
  src/psyclone/tests/psyir/symbols/symbol_table_test.py
  src/psyclone/tests/psyir/transformations/inline_trans_test.py
Labels: ready to be merged

#2115 (Closes #2114) ensure allocate with type-spec becomes a CodeBlock
  changelog
  doc/developer_guide/psyir.rst
  psyclone.pdf
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/intrinsic_call.py
  src/psyclone/tests/domain/common/transformations/alg_invoke_2_psy_call_trans_test.py
  src/psyclone/tests/psyir/frontend/fparser2_alloc_handler_test.py
  src/psyclone/tests/psyir/nodes/intrinsic_call_test.py
  src/psyclone/tests/psyir/symbols/interfaces_test.py
Labels: ready to be merged, NEMO

#2130 add support for TINY and HUGE (towards issue #1161)
  changelog
  doc/developer_guide/psyir.rst
  psyclone.pdf
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/intrinsic_call.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/frontend/fparser2_intrinsic_handler_test.py
  src/psyclone/tests/psyir/nodes/intrinsic_call_test.py
Labels: ready to be merged, NEMO, PSyIR

#2095 #2091: renaming DynInvoke to LFRicInvoke
  changelog
  doc/developer_guide/APIs.rst
  doc/developer_guide/conf.py
  doc/developer_guide/psyir.rst
  doc/user_guide/dynamo0p3_topclasses.dot
  doc/user_guide/dynamo0p3_topclasses.svg
  psyclone.pdf
  src/psyclone/domain/lfric/__init__.py
  src/psyclone/domain/lfric/lfric_invoke.py
  src/psyclone/dynamo0p3.py
  src/psyclone/tests/domain/lfric/lfric_field_mdata_test.py
  src/psyclone/tests/domain/lfric/lfric_loop_bounds_test.py
  src/psyclone/tests/domain/lfric/lfric_scalar_mdata_test.py
  src/psyclone/tests/domain/lfric/transformations/lfric_extract_test.py
  src/psyclone/tests/dynamo0p3_test.py
Labels: under review, ready to be merged, LFRic

#2146 (Closes #2145) skip MyBinder in linkchecks
  .github/workflows/mlc_config.json
  changelog
  doc/developer_guide/conf.py
  doc/psyad/user_guide/conf.py
  doc/reference_guide/source/conf.py
  doc/user_guide/conf.py
  psyclone.pdf
Labels: ready to be merged

#2135 Improve PSyIR support for Fortran interfaces (towards #1618)
  changelog
  doc/developer_guide/psyir_symbols.rst
  psyclone.pdf
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/psyir/frontend/fparser2_interface_block_test.py
Labels: ready to be merged, LFRic, PSyIR

#2150 (Towards #2132) change private repo to be in stfc organisation.
  .github/workflows/compilation.yml
  .github/workflows/python-package.yml
  .github/workflows/repo-sync.yml
  changelog
  doc/developer_guide/.readthedocs.yaml
  doc/reference_guide/.readthedocs.yaml
  doc/user_guide/.readthedocs.yaml
  psyclone.pdf
Labels: enhancement, ready to be merged
