Repository stfc/PSyclone, pull requests merged in 2024-11, with the labels that each got.

#2685 (Closes #2027) fix for ArrayMixin._effective_shape bug
  changelog
  examples/nemo/scripts/omp_cpu_trans.py
  examples/nemo/scripts/utils.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/array_mixin.py
  src/psyclone/psyir/nodes/structure_reference.py
  src/psyclone/psyir/transformations/arrayassignment2loops_trans.py
  src/psyclone/psyir/transformations/inline_trans.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/frontend/fparser2_where_handler_test.py
  src/psyclone/tests/psyir/nodes/array_mixin_test.py
  src/psyclone/tests/psyir/nodes/array_reference_test.py
  src/psyclone/tests/psyir/nodes/structure_reference_test.py
  src/psyclone/tests/psyir/transformations/arrayassignment2loops_trans_test.py
  src/psyclone/tests/psyir/transformations/inline_trans_test.py
Labels: bug, ready to be merged, PSyIR, NG-ARCH

#2749 (Closes 2311) Add functionality to derive module and subroutine names of adjoint test from filename for LFRic API
  changelog
  examples/psyad/eg2/Makefile
  examples/psyad/eg2/README.md
  psyclone.pdf
  src/psyclone/psyad/domain/lfric/lfric_adjoint_harness.py
  src/psyclone/psyad/main.py
  src/psyclone/psyad/tl2ad.py
  src/psyclone/tests/psyad/domain/lfric/test_lfric_adjoint_harness.py
  src/psyclone/tests/psyad/main_test.py
  src/psyclone/tests/psyad/tl2ad_test.py
Labels: ready to be merged, adjoint

#2763 Handle inconsistent OpenACC loop clauses
  changelog
  psyclone.pdf
  src/psyclone/psyir/nodes/acc_directives.py
  src/psyclone/tests/psyir/backend/psyir_openacc_test.py
  src/psyclone/tests/psyir/nodes/acc_directives_test.py
Labels: ready to be merged, NG-ARCH

#2734 (Towards #2704) 2704 access improvements
  changelog
  doc/developer_guide/dependency.rst
  psyclone.pdf
  src/psyclone/dynamo0p3.py
  src/psyclone/psyir/nodes/reference.py
  src/psyclone/psyir/tools/__init__.py
  src/psyclone/psyir/tools/definition_use_chains.py
  src/psyclone/tests/psyir/nodes/reference_test.py
  src/psyclone/tests/psyir/tools/definition_use_chains_forward_dependence_test.py
Labels: ready to be merged

#2767 (Closes #2755) Bug fix for psyad failing to transform array assignment
  changelog
  doc/developer_guide/index.rst
  doc/developer_guide/system_specific_setup.rst
  src/psyclone/psyad/tl2ad.py
  src/psyclone/psyad/transformations/preprocess.py
  src/psyclone/psyir/nodes/array_mixin.py
  src/psyclone/tests/psyad/tl2ad_test.py
  src/psyclone/tests/psyad/transformations/test_preprocess.py
  src/psyclone/tests/psyir/nodes/array_mixin_test.py
Labels: bug, under review, Release, adjoint

#2785 (Towards #759) extend fparser2 frontend to populate partial_datatype for OPTIONAL
  changelog
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
Labels: enhancement, ready to be merged

#2789 2778 removed old todos
  changelog
  examples/gocean/eg5/extract/extract_transform.py
  examples/gocean/eg5/extract/main.f90
  examples/lfric/eg17/full_example_extract/extract_transform.py
  psyclone.pdf
  src/psyclone/tests/domain/gocean/transformations/gocean_extract_test.py
Labels: ready to be merged

#2769 (Closes #2768) Improve robustness of Sign2Code and Abs2Code transformations
  changelog
  psyclone.pdf
  src/psyclone/parse/algorithm.py
  src/psyclone/psyad/domain/lfric/lfric_adjoint_harness.py
  src/psyclone/psyir/backend/c.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/transformations/intrinsics/abs2code_trans.py
  src/psyclone/psyir/transformations/intrinsics/intrinsic2code_trans.py
  src/psyclone/psyir/transformations/intrinsics/sign2code_trans.py
  src/psyclone/tests/psyir/backend/c_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/transformations/intrinsics/sign2code_trans_test.py
Labels: ready to be merged, PSyIR, Release

#2697 (towards #2671) Parallel array privatisation
  .github/workflows/nemo_tests.yml
  .github/workflows/nemo_v5_tests.yml
  changelog
  examples/nemo/scripts/KGOs/run.stat.bench.gfortran.small.100steps
  examples/nemo/scripts/KGOs/run.stat.bench.nvhpc.small.100steps
  examples/nemo/scripts/KGOs/run.stat.bench.oneapi.small.100steps
  examples/nemo/scripts/Makefile
  examples/nemo/scripts/compare_ouput.py
  examples/nemo/scripts/omp_cpu_trans.py
  examples/nemo/scripts/omp_gpu_trans.py
  examples/nemo/scripts/passthrough.py
  examples/nemo/scripts/utils.py
  psyclone.pdf
  src/psyclone/generator.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/loop.py
  src/psyclone/psyir/nodes/node.py
  src/psyclone/psyir/nodes/omp_directives.py
  src/psyclone/psyir/symbols/datatypes.py
  src/psyclone/psyir/symbols/symbol_table.py
  src/psyclone/psyir/transformations/arrayassignment2loops_trans.py
  src/psyclone/psyir/transformations/hoist_local_arrays_trans.py
  src/psyclone/psyir/transformations/omp_target_trans.py
  src/psyclone/psyir/transformations/parallel_loop_trans.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/psyir/nodes/loop_test.py
  src/psyclone/tests/psyir/nodes/node_test.py
  src/psyclone/tests/psyir/nodes/omp_directives_test.py
  src/psyclone/tests/psyir/symbols/datatype_test.py
  src/psyclone/tests/psyir/tools/dependency_tools_test.py
  src/psyclone/tests/psyir/transformations/arrayassignment2loops_trans_test.py
  src/psyclone/tests/psyir/transformations/hoist_local_arrays_trans_test.py
  src/psyclone/tests/psyir/transformations/omp_target_trans_test.py
  src/psyclone/tests/psyir/transformations/parallel_loop_trans_test.py
Labels: ready to be merged, NEMO, Release, NG-ARCH

#2803 2796 fix profile nodes inside of lfric loops
  changelog
  psyclone.pdf
  src/psyclone/domain/lfric/lfric_loop.py
  src/psyclone/psyir/nodes/loop.py
  src/psyclone/psyir/nodes/psy_data_node.py
  src/psyclone/tests/psyir/nodes/psy_data_node_test.py
Labels: ready to be merged, Release

#2628 (Closes #2624) Add `FortranWriter().schedule_node()`.
  changelog
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/tests/psyir/backend/fortran_test.py
Labels: ready to be merged

#2800 Update CI software versions
  .github/workflows/compilation.yml
  changelog
  doc/user_guide/transformations.rst
  examples/gocean/eg2/Makefile
  examples/gocean/eg2/README.md
  examples/gocean/eg2/inc_field_mod.f90
  examples/gocean/eg4/Makefile
  examples/gocean/eg4/README.md
  examples/gocean/eg6/inc_field_mod.f90
  examples/gocean/eg7/inc_field_mod.f90
  examples/lfric/scripts/KGOs/nvfortran_acc.mk
  examples/nemo/README.md
  examples/nemo/eg3/Makefile
  examples/nemo/eg3/README.md
  examples/nemo/eg3/kernel_utils.py
  examples/nemo/eg3/kernels_trans.py
  examples/nemo/scripts/Makefile
  lib/profiling/nvidia/README.md
  lib/profiling/nvidia/nvtx_prof.f90
Labels: enhancement, ready to be merged
