Repository stfc/PSyclone, pull requests merged in 2024-02, with the labels that each got.

#2465 (towards 2004) Move same_range functionality to ArrayMixin and other improvements
  changelog
  src/psyclone/psyir/frontend/fortran.py
  src/psyclone/psyir/nodes/array_mixin.py
  src/psyclone/psyir/transformations/arrayrange2loop_trans.py
  src/psyclone/tests/psyir/frontend/fortran_test.py
  src/psyclone/tests/psyir/nodes/array_mixin_test.py
  src/psyclone/tests/psyir/transformations/arrayrange2loop_trans_test.py
Labels: ready to be merged

#2372 (Towards #1960) put WHEREs containing reductions into CodeBlocks and fix non-unity lower-bound bug.
  changelog
  examples/nemo/scripts/process_nemo.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/array_mixin.py
  src/psyclone/psyir/nodes/array_reference.py
  src/psyclone/psyir/nodes/structure_reference.py
  src/psyclone/psyir/transformations/inline_trans.py
  src/psyclone/tests/nemo/transformations/openacc/kernels_directive_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/frontend/fparser2_where_handler_test.py
  src/psyclone/tests/psyir/nodes/array_mixin_test.py
  src/psyclone/tests/psyir/nodes/array_reference_test.py
  src/psyclone/tests/psyir/nodes/operation_test.py
Labels: ready to be merged, NEMO, Release

#2489 (Closes#2488) Updating base loop fusion code towards 2488
  changelog
  doc/user_guide/nemo.rst
  psyclone.pdf
  src/psyclone/domain/nemo/transformations/__init__.py
  src/psyclone/domain/nemo/transformations/nemo_loop_fuse.py
  src/psyclone/psyir/transformations/loop_fuse_trans.py
  src/psyclone/tests/domain/nemo/transformations/nemo_loop_trans_test.py
  src/psyclone/tests/psyir/transformations/loop_fusion_test.py
Labels: ready to be merged

#2423 #2410 splitting and renaming DynStencils to LFRicStencils
  changelog
  psyclone.pdf
  src/psyclone/domain/lfric/__init__.py
  src/psyclone/domain/lfric/kern_call_acc_arg_list.py
  src/psyclone/domain/lfric/kern_call_arg_list.py
  src/psyclone/domain/lfric/kern_stub_arg_list.py
  src/psyclone/domain/lfric/lfric_invoke.py
  src/psyclone/domain/lfric/lfric_kern.py
  src/psyclone/domain/lfric/lfric_stencils.py
  src/psyclone/dynamo0p3.py
  src/psyclone/tests/domain/lfric/lfric_stencil_test.py
Labels: under review, ready to be merged, LFRic

#2501 (Closes #2447) Create release 2.5.0
  LICENSE
  changelog
  doc/developer_guide/conf.py
  doc/reference_guide/doxygen.config
  doc/reference_guide/source/conf.py
  doc/user_guide/conf.py
  examples/gocean/eg3/.gitignore
  psyclone.pdf
  setup.py
  src/psyclone/version.py
Labels: under review, ready to be merged, Release

#2477 #2463 Support namelist in PSyIR (as an UnknownFortranType).
  changelog
  examples/nemo/scripts/acc_kernels_trans.py
  examples/nemo/scripts/acc_loops_trans.py
  examples/nemo/scripts/omp_cpu_trans.py
  examples/nemo/scripts/omp_gpu_trans.py
  examples/nemo/scripts/utils.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/symbols/__init__.py
  src/psyclone/psyir/symbols/interfaces.py
  src/psyclone/tests/psyir/frontend/fparser2_namelist_test.py
  src/psyclone/tests/psyir/symbols/interfaces_test.py
Labels: enhancement, ready to be merged, um_physics

#2367 2296 add routine info
  changelog
  config/psyclone.cfg
  psyclone.pdf
  src/psyclone/configuration.py
  src/psyclone/domain/gocean/transformations/gocean_extract_trans.py
  src/psyclone/domain/lfric/lfric_extract_driver_creator.py
  src/psyclone/domain/lfric/transformations/lfric_extract_trans.py
  src/psyclone/parse/module_info.py
  src/psyclone/parse/module_manager.py
  src/psyclone/psyad/adjoint_visitor.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/nodes/acc_directives.py
  src/psyclone/psyir/nodes/container.py
  src/psyclone/psyir/nodes/extract_node.py
  src/psyclone/psyir/nodes/nan_test_node.py
  src/psyclone/psyir/nodes/read_only_verify_node.py
  src/psyclone/psyir/nodes/routine.py
  src/psyclone/psyir/tools/__init__.py
  src/psyclone/psyir/tools/call_tree_utils.py
  src/psyclone/psyir/tools/dependency_tools.py
  src/psyclone/psyir/transformations/acc_update_trans.py
  src/psyclone/tests/config_test.py
  src/psyclone/tests/conftest.py
  src/psyclone/tests/domain/common/extract_driver_creator_test.py
  src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
  src/psyclone/tests/domain/nemo/test_files/nemo_test.cfg
  src/psyclone/tests/parse/conftest.py
  src/psyclone/tests/parse/module_info_test.py
  src/psyclone/tests/parse/module_manager_test.py
  src/psyclone/tests/psyir/nodes/container_test.py
  src/psyclone/tests/psyir/nodes/routine_test.py
  src/psyclone/tests/psyir/tools/call_tree_utils_test.py
  src/psyclone/tests/psyir/tools/dependency_tools_test.py
  src/psyclone/tests/test_files/dynamo0p3/driver_creation/invoke_kernel_with_imported_symbols.f90
  src/psyclone/tests/test_files/dynamo0p3/driver_creation/invoke_kernel_with_imported_symbols_error.f90
  src/psyclone/tests/test_files/dynamo0p3/driver_creation/module_call_tree_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/driver_creation/module_renaming_external_var_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/driver_creation/module_with_builtin_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/driver_creation/module_with_error_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/driver_creation/module_with_name_clash_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/driver_creation/module_with_var_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/driver_creation/testkern_import_symbols_error_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/driver_creation/testkern_import_symbols_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/driver_creation/testkern_import_symbols_name_clash_mod.f90
  src/psyclone/tests/test_files/gocean1p0/gocean_default.cfg
  tutorial/practicals/LFRic/distributed_memory/2_annexed_dofs/psyclone.cfg
  tutorial/practicals/LFRic/distributed_memory/3_overlapping_comms/psyclone.cfg
  tutorial/practicals/LFRic/single_node/1_openmp/psyclone.cfg
Labels: enhancement, ready to be merged, discussion

#2457 2455 DynDofmaps split & rename
  changelog
  src/psyclone/domain/lfric/__init__.py
  src/psyclone/domain/lfric/lfric_builtins.py
  src/psyclone/domain/lfric/lfric_dofmaps.py
  src/psyclone/domain/lfric/lfric_invoke.py
  src/psyclone/domain/lfric/lfric_kern.py
  src/psyclone/dynamo0p3.py
  src/psyclone/tests/domain/lfric/lfric_dofmaps_test.py
  src/psyclone/tests/dynamo0p3_cma_test.py
Labels: enhancement, ready to be merged, LFRic
