Repository stfc/PSyclone, pull requests merged in 2024-03, with the labels that each got.

#2506 Update CI software dependencies
  .github/workflows/compilation.yml
  .github/workflows/lfric_test.yml
  .github/workflows/nemo_tests.yml
  .github/workflows/python-package.yml
  changelog
  setup.py
  src/psyclone/tests/domain/lfric/lfric_dofmaps_test.py
Labels: ready to be merged

#2508 (Closes #2507) extend InlineTrans to ignore clash between formal arguments
  changelog
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/symbols/symbol_table.py
  src/psyclone/psyir/transformations/inline_trans.py
  src/psyclone/tests/domain/lfric/lfric_dofmaps_test.py
  src/psyclone/tests/psyir/backend/fortran_routine_test.py
  src/psyclone/tests/psyir/symbols/symbol_table_test.py
  src/psyclone/tests/psyir/transformations/inline_trans_test.py
Labels: bug, ready to be merged, CROCO

#2505 (towards #1010) Use the PSyIR Fortran backend for LFRic loops and anything inside them
  changelog
  doc/developer_guide/modules.rst
  doc/user_guide/transformations.rst
  psyclone.pdf
  src/psyclone/domain/lfric/arg_ordering.py
  src/psyclone/domain/lfric/kern_call_arg_list.py
  src/psyclone/domain/lfric/kern_call_invoke_arg_list.py
  src/psyclone/domain/lfric/kern_stub_arg_list.py
  src/psyclone/domain/lfric/kernel_interface.py
  src/psyclone/domain/lfric/lfric_builtins.py
  src/psyclone/domain/lfric/lfric_invoke.py
  src/psyclone/domain/lfric/lfric_kern.py
  src/psyclone/domain/lfric/lfric_loop.py
  src/psyclone/dynamo0p3.py
  src/psyclone/f2pygen.py
  src/psyclone/gocean1p0.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/nodes/loop.py
  src/psyclone/psyir/nodes/nan_test_node.py
  src/psyclone/psyir/nodes/read_only_verify_node.py
  src/psyclone/tests/domain/lfric/builtins/int_to_real_x_test.py
  src/psyclone/tests/domain/lfric/builtins/real_to_int_x_test.py
  src/psyclone/tests/domain/lfric/builtins/real_to_real_x_test.py
  src/psyclone/tests/domain/lfric/builtins/reduction_builtins_test.py
  src/psyclone/tests/domain/lfric/builtins/setval_random_test.py
  src/psyclone/tests/domain/lfric/builtins/sum_x_test.py
  src/psyclone/tests/domain/lfric/builtins/x_innerproduct_x_test.py
  src/psyclone/tests/domain/lfric/builtins/x_innerproduct_y_test.py
  src/psyclone/tests/domain/lfric/lfric_builtins_test.py
  src/psyclone/tests/domain/lfric/lfric_domain_kernels_test.py
  src/psyclone/tests/domain/lfric/lfric_dynamopsy_test.py
  src/psyclone/tests/domain/lfric/lfric_field_codegen_test.py
  src/psyclone/tests/domain/lfric/lfric_integer_builtins_test.py
  src/psyclone/tests/domain/lfric/lfric_kern_test.py
  src/psyclone/tests/domain/lfric/lfric_loop_test.py
  src/psyclone/tests/domain/lfric/lfric_scalar_codegen_test.py
  src/psyclone/tests/domain/lfric/lfric_stencil_test.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/domain/lfric/transformations/lfric_extract_test.py
  src/psyclone/tests/dynamo0p3_basis_test.py
  src/psyclone/tests/dynamo0p3_cma_test.py
  src/psyclone/tests/dynamo0p3_lma_test.py
  src/psyclone/tests/dynamo0p3_multigrid_test.py
  src/psyclone/tests/dynamo0p3_quadrature_test.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/gocean1p0_test.py
  src/psyclone/tests/lfric_ref_elem_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/nodes/acc_directives_test.py
  src/psyclone/tests/psyir/nodes/loop_test.py
  src/psyclone/tests/psyir/transformations/nan_test.py
  src/psyclone/tests/psyir/transformations/profile_test.py
  src/psyclone/tests/psyir/transformations/read_only_verify_trans_test.py
Labels: ready to be merged, LFRic

#2516 Fix all issues flagged by flake8
  .github/workflows/compilation.yml
  .github/workflows/python-package.yml
  changelog
  doc/developer_guide/system_specific_setup.rst
  examples/gocean/eg1/openmp_taskloop_trans.py
  examples/nemo/scripts/utils.py
  setup.cfg
  setup.py
  src/psyclone/domain/lfric/arg_ordering.py
  src/psyclone/domain/lfric/lfric_builtins.py
  src/psyclone/domain/lfric/lfric_kern.py
  src/psyclone/psyGen.py
  src/psyclone/psyad/domain/lfric/lfric_adjoint.py
  src/psyclone/psyad/transformations/adjoint_trans.py
  src/psyclone/psyir/nodes/nan_test_node.py
  src/psyclone/psyir/nodes/read_only_verify_node.py
  src/psyclone/psyir/transformations/intrinsics/maxval2loop_trans.py
  src/psyclone/psyir/transformations/intrinsics/minval2loop_trans.py
  src/psyclone/tests/conftest.py
  src/psyclone/tests/domain/lfric/lfric_types_test.py
  src/psyclone/tests/domain/nemo/transformations/nemo_arrayaccess2loop_trans_test.py
  src/psyclone/tests/f2pygen_test.py
  src/psyclone/tests/nemo/nemo_psy_test.py
  src/psyclone/tests/nemo/transformations/profiling/nemo_profile_test.py
  src/psyclone/tests/psyad/adjoint_visitor_test.py
  src/psyclone/tests/psyir/backend/psyir_openacc_test.py
  src/psyclone/tests/psyir/frontend/fparser2_part_ref_test.py
  src/psyclone/tests/psyir/nodes/node_test.py
  src/psyclone/tests/psyir/nodes/omp_directives_test.py
  src/psyclone/tests/psyir/nodes/range_test.py
  src/psyclone/tests/psyir/symbols/symbol_table_test.py
  src/psyclone/tests/psyir/tools/call_tree_utils_test.py
  tutorial/practicals/LFRic/single_node/3_sequential/loop_fuse.py
  tutorial/practicals/LFRic/single_node/3_sequential/matvec_opt.py
  tutorial/practicals/nemo/1_nemo_psyir/schedule_view_trans.py
  tutorial/practicals/nemo/2_nemo_profiling/README.md
  tutorial/practicals/nemo/3_nemo_openmp/README.md
Labels: ready to be merged

#2512 (towards #11) CodeBlocks have an attached comment with the reason for the CodeBlock
  changelog
  doc/developer_guide/psyir.rst
  psyclone.pdf
  src/psyclone/psyir/backend/visitor.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/domain/gocean/transformations/gocean_opencl_trans_test.py
  src/psyclone/tests/domain/nemo/transformations/acc_update_test.py
  src/psyclone/tests/nemo/transformations/profiling/nemo_profile_test.py
  src/psyclone/tests/psyad/domain/common/test_adjoint_utils.py
  src/psyclone/tests/psyad/domain/lfric/test_lfric_adjoint_harness.py
  src/psyclone/tests/psyad/main_test.py
  src/psyclone/tests/psyad/transformations/test_preprocess.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/frontend/fparser2_do_handler_test.py
  src/psyclone/tests/psyir/frontend/fparser2_main_program_handler_test.py
  src/psyclone/tests/psyir/frontend/fparser2_parameter_stmts_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
Labels: ready to be merged

#2474 #2409 Comments for PSy-Layer Builtins
  changelog
  psyclone.pdf
  src/psyclone/domain/lfric/lfric_builtins.py
  src/psyclone/tests/domain/lfric/builtins/int_to_real_x_test.py
  src/psyclone/tests/domain/lfric/builtins/real_to_int_x_test.py
  src/psyclone/tests/domain/lfric/builtins/real_to_real_x_test.py
  src/psyclone/tests/domain/lfric/builtins/reduction_builtins_test.py
  src/psyclone/tests/domain/lfric/builtins/setval_random_test.py
  src/psyclone/tests/domain/lfric/builtins/sum_x_test.py
  src/psyclone/tests/domain/lfric/builtins/x_innerproduct_x_test.py
  src/psyclone/tests/domain/lfric/builtins/x_innerproduct_y_test.py
  src/psyclone/tests/domain/lfric/lfric_builtins_test.py
  src/psyclone/tests/domain/lfric/lfric_dynamopsy_test.py
  src/psyclone/tests/domain/lfric/lfric_integer_builtins_test.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/domain/lfric/transformations/lfric_extract_test.py
Labels: ready to be merged, LFRic

#2511 (Closes #2510) ArrayRange2Loop transformation no longer allows Character arrays by default.
  changelog
  src/psyclone/domain/nemo/transformations/nemo_allarrayaccess2loop_trans.py
  src/psyclone/domain/nemo/transformations/nemo_allarrayrange2loop_trans.py
  src/psyclone/domain/nemo/transformations/nemo_arrayaccess2loop_trans.py
  src/psyclone/domain/nemo/transformations/nemo_arrayrange2loop_trans.py
  src/psyclone/domain/nemo/transformations/nemo_outerarrayrange2loop_trans.py
  src/psyclone/psyad/transformations/assignment_trans.py
  src/psyclone/psyir/nodes/array_reference.py
  src/psyclone/psyir/transformations/arrayrange2loop_trans.py
  src/psyclone/psyir/transformations/intrinsics/abs2code_trans.py
  src/psyclone/psyir/transformations/intrinsics/array_reduction_base_trans.py
  src/psyclone/psyir/transformations/intrinsics/dotproduct2code_trans.py
  src/psyclone/psyir/transformations/intrinsics/matmul2code_trans.py
  src/psyclone/psyir/transformations/intrinsics/minormax2code_trans.py
  src/psyclone/psyir/transformations/intrinsics/sign2code_trans.py
  src/psyclone/psyir/transformations/replace_induction_variables_trans.py
  src/psyclone/tests/domain/nemo/transformations/nemo_allarrayrange2loop_trans_test.py
  src/psyclone/tests/domain/nemo/transformations/nemo_arrayrange2loop_trans_test.py
  src/psyclone/tests/psyir/nodes/array_reference_test.py
  src/psyclone/tests/psyir/transformations/arrayrange2loop_trans_test.py
Labels: ready to be merged
