Repository stfc/PSyclone, pull requests merged in 2024-05, with the labels that each got.

#2581 (Closes #2576) Truncated the VMware error message to avoid the broken link
  changelog
  psyclone.pdf
  tutorial/practicals/README.md
Labels: ready to be merged

#2571 (Closes #2569) update integration workflows to use python 3.12.3 and nvfortran 24.3
  .github/workflows/compilation.yml
  .github/workflows/lfric_test.yml
  .github/workflows/nemo_tests.yml
  changelog
  examples/gocean/eg5/extract/Makefile
  examples/lfric/eg17/full_example_extract/Makefile
  examples/lfric/eg17/full_example_netcdf/Makefile
  examples/lfric/scripts/KGOs/lfric_gunho_configuration_4its.nml
  examples/lfric/scripts/KGOs/lfric_gunho_configuration_4its_output.txt
  examples/nemo/eg5/Makefile
Labels: ready to be merged

#2567 (Closes #1333) Unary minus parenthesizing
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/tests/psyad/transformations/test_assignment_trans.py
  src/psyclone/tests/psyir/backend/fortran_test.py
Labels: under review

#2579 #2578 Fix missing location update.
  changelog
  psyclone.pdf
  src/psyclone/psyir/nodes/call.py
  src/psyclone/tests/psyir/nodes/call_test.py
Labels: ready to be merged

#2556 #1351 - Support for user-defined kernels that operate on DoFs
  changelog
  doc/user_guide/dynamo0p3.rst
  psyclone.pdf
Labels: ready to be merged, LFRic

#2590 (closes #2589) Update LFRic integration test
  .github/workflows/lfric_test.yml
  .github/workflows/nemo_tests.yml
  changelog
  examples/lfric/scripts/KGOs/lfric_gunho_configuration_4its.nml
  examples/lfric/scripts/KGOs/lfric_gunho_configuration_4its_output.txt
  examples/lfric/scripts/KGOs/lfric_psyclone.cfg
  psyclone.pdf
  src/psyclone/configuration.py
  src/psyclone/tests/config_test.py
Labels: ready to be merged

#2452 2451 DynInvokeSchedule split & rename
  changelog
  doc/user_guide/dynamo0p3_topclasses.dot
  doc/user_guide/dynamo0p3_topclasses.svg
  psyclone.pdf
  src/psyclone/domain/lfric/__init__.py
  src/psyclone/domain/lfric/lfric_builtins.py
  src/psyclone/domain/lfric/lfric_invoke.py
  src/psyclone/domain/lfric/lfric_invoke_schedule.py
  src/psyclone/domain/lfric/lfric_loop.py
  src/psyclone/dynamo0p3.py
  src/psyclone/psyir/nodes/acc_directives.py
  src/psyclone/tests/domain/lfric/dyn_invoke_schedule_test.py
  src/psyclone/tests/domain/lfric/lfric_invoke_schedule_test.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/domain/lfric/transformations/lfric_haloex_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/tools/call_tree_utils_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#2574 (#Closes 2196) Intrinsic implementation for fparser2, container symbol and fortran backend
  changelog
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/symbols/containersymbol.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/symbols/containersymbol_test.py
Labels: ready to be merged

#2566 (Towards #2156) Changes to routine_copy and fortran backend for elemental and impure support
  changelog
  psyclone.pdf
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/routine.py
  src/psyclone/psyir/symbols/routinesymbol.py
  src/psyclone/tests/psyir/backend/fortran_routine_test.py
  src/psyclone/tests/psyir/frontend/fparser2_subroutine_handler_test.py
  src/psyclone/tests/psyir/symbols/routinesymbol_test.py
Labels: ready to be merged

#2572 (Closes #2195) SymbolTable().view() grouping and alpha-ordering
  src/psyclone/psyir/symbols/symbol_table.py
  src/psyclone/tests/psyir/symbols/symbol_table_test.py
Labels: ready to be merged

#2599 Update CI software dependencies
  .github/workflows/compilation.yml
  .github/workflows/nemo_tests.yml
  changelog
Labels: ready to be merged
