Repository stfc/PSyclone, pull requests merged in 2024-01, with the labels that each got.

#2454 (#Closes 2418) Improvements to fix 2418
  changelog
  src/psyclone/psyir/nodes/dynamic_omp_task_directive.py
  src/psyclone/psyir/transformations/omp_task_trans.py
  src/psyclone/tests/psyir/transformations/omp_task_transformations_test.py
Labels: ready to be merged, Task-based

#2443 (Closes #2442) Bug fix for LFRic PSy-layer generation involving CMA operators
  .github/workflows/lfric_test.yml
  changelog
  psyclone.pdf
  src/psyclone/domain/lfric/kern_call_arg_list.py
  src/psyclone/dynamo0p3.py
  src/psyclone/psyir/nodes/array_reference.py
  src/psyclone/tests/dependency_test.py
  src/psyclone/tests/domain/lfric/arg_ordering_test.py
  src/psyclone/tests/domain/lfric/kern_call_acc_arg_list_test.py
  src/psyclone/tests/domain/lfric/kern_call_arg_list_test.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/dynamo0p3_cma_test.py
  src/psyclone/tests/psyir/nodes/array_reference_test.py
Labels: bug, under review, ready to be merged, LFRic

#2481 (Closes #1193) unpin jsonschema
  changelog
  setup.py
Labels: enhancement, ready to be merged

#2470 #2468 Fixed anchor to README
  changelog
  doc/user_guide/conf.py
  doc/user_guide/examples.rst
  doc/user_guide/getting_going.rst
  doc/user_guide/gocean1p0.rst
  doc/user_guide/index.rst
  psyclone.pdf
Labels: ready to be merged

#2420 1786 Adding real-to-real conversion builtin
  changelog
  doc/developer_guide/APIs.rst
  doc/user_guide/dynamo0p3.rst
  psyclone.pdf
  src/psyclone/domain/lfric/kernel/lfric_kernel_metadata.py
  src/psyclone/domain/lfric/lfric_builtins.py
  src/psyclone/parse/lfric_builtins_mod.f90
  src/psyclone/tests/domain/lfric/builtins/int_to_real_x_test.py
  src/psyclone/tests/domain/lfric/builtins/real_to_int_x_test.py
  src/psyclone/tests/domain/lfric/builtins/real_to_real_x_test.py
  src/psyclone/tests/domain/lfric/lfric_builtins_test.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/test_files/dynamo0p3/15.10.3_real_to_int_X_builtin.f90
  src/psyclone/tests/test_files/dynamo0p3/15.10.8_real_to_real_X_builtin.f90
  src/psyclone/tests/test_files/dynamo0p3/15.28.2_int_to_real_X_builtin.f90
Labels: enhancement, under review, ready to be merged, LFRic, Release

#2480 Update .gitignore rules for generated example code (for #2479)
  changelog
  examples/lfric/eg14/.gitignore
  examples/psyad/lfric/adjoint/.gitignore
  examples/psyad/lfric/adjoint_partial/.gitignore
  psyclone.pdf
Labels: bug, ready to be merged, LFRic, Release

#2484 (towards #2062) Add Node.origin_string method to retrieve original filename and line number information
  changelog
  psyclone.pdf
  src/psyclone/psyir/frontend/fortran.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/node.py
  src/psyclone/psyir/nodes/scoping_node.py
  src/psyclone/tests/psyir/nodes/node_test.py
Labels: ready to be merged

#2439 (closes #2105) Use maxval2loop and atomics to parallelise NEMO stpctl.f90
  changelog
  examples/nemo/scripts/omp_gpu_trans.py
  examples/nemo/scripts/utils.py
  psyclone.pdf
  src/psyclone/psyir/nodes/reference.py
  src/psyclone/psyir/symbols/symbol.py
  src/psyclone/psyir/symbols/typed_symbol.py
  src/psyclone/psyir/transformations/intrinsics/array_reduction_base_trans.py
  src/psyclone/psyir/transformations/intrinsics/maxval2loop_trans.py
  src/psyclone/psyir/transformations/intrinsics/minval2loop_trans.py
  src/psyclone/psyir/transformations/intrinsics/product2loop_trans.py
  src/psyclone/psyir/transformations/intrinsics/sum2loop_trans.py
  src/psyclone/tests/psyir/symbols/symbol_test.py
  src/psyclone/tests/psyir/transformations/intrinsics/array_reduction_base_trans_test.py
  src/psyclone/tests/psyir/transformations/intrinsics/maxval2loop_trans_test.py
  src/psyclone/tests/psyir/transformations/intrinsics/minval2loop_trans_test.py
Labels: ready to be merged

#2493 (Closes #2492) nemoouterarrayrange bug
  changelog
  examples/nemo/scripts/utils.py
  src/psyclone/domain/nemo/transformations/nemo_outerarrayrange2loop_trans.py
  src/psyclone/tests/domain/nemo/transformations/nemo_outerarrayrange2loop_trans_test.py
Labels: ready to be merged
