Repository stfc/PSyclone, pull requests merged in 2024-10, with the labels that each got.

#2725 (closes #717) Remove unused code
  changelog
  examples/nemo/scripts/acc_kernels_trans.py
  examples/nemo/scripts/acc_loops_trans.py
  examples/nemo/scripts/omp_cpu_trans.py
  examples/nemo/scripts/omp_gpu_trans.py
  examples/nemo/scripts/passthrough.py
  examples/nemo/scripts/utils.py
  psyclone.pdf
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/transformations/intrinsics/dotproduct2code_trans.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
Labels: ready to be merged

#2733 (closes #2730) OpenMP offloading for LFRic
  .github/workflows/lfric_test.yml
  changelog
  examples/lfric/scripts/KGOs/lfric_3269_nvidia.patch
  examples/lfric/scripts/KGOs/nvfortran_acc.mk
  examples/lfric/scripts/Makefile
  examples/lfric/scripts/acc_parallel.py
  examples/lfric/scripts/gpu_offloading.py
  psyclone.pdf
  src/psyclone/f2pygen.py
  src/psyclone/psyir/nodes/omp_directives.py
  src/psyclone/tests/psyir/nodes/omp_directives_test.py
  src/psyclone/tests/psyir/transformations/kernel_transformation_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#2743 (Closes #2742) Sort the ordering of function spaces in LFRic algorithms
  changelog
  psyclone.pdf
  src/psyclone/domain/lfric/algorithm/lfric_alg.py
  src/psyclone/tests/domain/lfric/algorithm/lfric_alg_test.py
Labels: ready to be merged, adjoint

#2746 Update CI software versions
  .github/workflows/compilation.yml
  .github/workflows/lfric_test.yml
  .github/workflows/nemo_tests.yml
  .github/workflows/python-package.yml
  changelog
  doc/developer_guide/.readthedocs.yaml
  doc/developer_guide/working_practises.rst
  doc/psyad/user_guide/.readthedocs.yaml
  doc/reference_guide/.readthedocs.yaml
  doc/user_guide/.readthedocs.yaml
  doc/user_guide/getting_going.rst
  examples/gocean/eg5/extract/Makefile
  examples/nemo/eg5/Makefile
  psyclone.pdf
  src/psyclone/tests/psyad/main_test.py
  tutorial/practicals/nemo/2_nemo_profiling/Makefile
Labels: ready to be merged

#2748 Revert to Python 3.12 for all RTD builds
  changelog
  doc/developer_guide/.readthedocs.yaml
  doc/psyad/user_guide/.readthedocs.yaml
  doc/reference_guide/.readthedocs.yaml
  doc/user_guide/.readthedocs.yaml
Labels: ready to be merged

#2707 257 verify loop fusion
  changelog
  psyclone.pdf
  src/psyclone/core/symbolic_maths.py
  src/psyclone/psyir/backend/sympy_writer.py
  src/psyclone/psyir/tools/dependency_tools.py
  src/psyclone/psyir/transformations/loop_fuse_trans.py
  src/psyclone/tests/psyir/backend/sympy_writer_test.py
  src/psyclone/tests/psyir/tools/dependency_tools_test.py
  src/psyclone/tests/psyir/transformations/loop_fusion_test.py
Labels: ready to be merged

#2752 Add `is_literal_assignment` method for `Assignment` node
  changelog
  src/psyclone/psyir/nodes/assignment.py
  src/psyclone/tests/psyir/nodes/assignment_test.py
Labels: ready to be merged, NG-ARCH

#2753 Add `is_character` method for `DataNode`
  changelog
  src/psyclone/psyir/nodes/assignment.py
  src/psyclone/psyir/nodes/datanode.py
  src/psyclone/tests/psyir/nodes/datanode_test.py
Labels: ready to be merged, NG-ARCH
