Repository stfc/PSyclone, pull requests merged in 2024-04, with the labels that each got.

#2521 Fix line-length example
  changelog
  examples/line_length/runme.py
Labels: ready to be merged

#2539 (Closes #2538) Added a preprocessor interface
  changelog
  doc/user_guide/psyir.rst
  psyclone.pdf
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/symbols/__init__.py
  src/psyclone/psyir/symbols/interfaces.py
  src/psyclone/tests/psyir/backend/fortran_gen_decls_test.py
  src/psyclone/tests/psyir/symbols/interfaces_test.py
Labels: ready to be merged

#2540 (Closes #2537) Added exact_name requirement to the symbol_table find_and_create_tag …
  changelog
  src/psyclone/psyir/symbols/symbol_table.py
  src/psyclone/tests/psyir/symbols/symbol_table_test.py
Labels: ready to be merged

#2497 2496 use psyir in access info
  changelog
  doc/developer_guide/dependency.rst
  examples/gocean/eg1/runme.py
  examples/gocean/eg1/runme_loop_fuse.py
  examples/gocean/eg6/backends_transform.py
  psyclone.pdf
  src/psyclone/domain/lfric/transformations/lfric_loop_fuse_trans.py
  src/psyclone/gocean1p0.py
  src/psyclone/psyir/tools/dependency_tools.py
  src/psyclone/psyir/transformations/loop_fuse_trans.py
  src/psyclone/tests/dependency_test.py
  src/psyclone/tests/domain/gocean/kernel/gokern_test.py
  src/psyclone/tests/dynamo0p3_test.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/psyir/tools/dependency_tools_test.py
  src/psyclone/tests/psyir/transformations/transformations_test.py
  src/psyclone/tests/test_files/dynamo0p3/loop_fuse_trans.py
  src/psyclone/tests/test_files/gocean1p0/kernel_stencil_not_parallel.f90
  src/psyclone/tests/test_files/gocean1p0/test31_stencil_not_parallel.f90
Labels: bug, ready to be merged, GOcean, PSyIR

#2549 (Closes #2548) switch GHA to use v4 of codecov action
  .github/workflows/python-package.yml
  changelog
Labels: enhancement, ready to be merged

#2396 (Closes #2229) PSyIR support for select type
  changelog
  doc/developer_guide/psyir.rst
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/if_block.py
  src/psyclone/tests/psyir/frontend/fparser2_select_type_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
Labels: in progress, ready to be merged, LFRic, PSyIR, NEMOVAR

#2545 #2544 Accept -c as shortcut for --config on command line.
  changelog
  doc/user_guide/conf.py
  doc/user_guide/psyclone_command.rst
  doc/user_guide/psyclone_kern.rst
  src/psyclone/generator.py
  src/psyclone/kernel_tools.py
  src/psyclone/tests/generator_test.py
Labels: ready to be merged

#2529 (towards #1779) Generalise NemoArrayAccess2Loop transformation to ArrayAcces2Loop
  changelog
  doc/user_guide/nemo.rst
  doc/user_guide/transformations.rst
  examples/nemo/eg4/sir_trans_all.py
  examples/nemo/eg4/sir_trans_loop.py
  psyclone.pdf
  src/psyclone/configuration.py
  src/psyclone/domain/nemo/transformations/__init__.py
  src/psyclone/psyir/backend/sir.py
  src/psyclone/psyir/transformations/__init__.py
  src/psyclone/psyir/transformations/allarrayaccess2loop_trans.py
  src/psyclone/psyir/transformations/arrayaccess2loop_trans.py
  src/psyclone/tests/psyir/transformations/allarrayaccess2loop_trans_test.py
  src/psyclone/tests/psyir/transformations/arrayaccess2loop_trans_test.py
Labels: ready to be merged

#2517 (Closes #2515) fix bugs in symbol-table merge
  changelog
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/nodes/call.py
  src/psyclone/psyir/symbols/interfaces.py
  src/psyclone/psyir/symbols/symbol_table.py
  src/psyclone/psyir/transformations/inline_trans.py
  src/psyclone/tests/psyir/backend/fortran_routine_test.py
  src/psyclone/tests/psyir/frontend/fparser2_fortran_use_test.py
  src/psyclone/tests/psyir/symbols/containersymbol_test.py
  src/psyclone/tests/psyir/symbols/interfaces_test.py
  src/psyclone/tests/psyir/symbols/symbol_table_test.py
  src/psyclone/tests/psyir/transformations/inline_trans_test.py
Labels: ready to be merged

#2553 (Towards #2499) Initial implementation of next_access function on Reference
  changelog
  src/psyclone/psyir/nodes/reference.py
  src/psyclone/tests/psyir/nodes/reference_test.py
Labels: ready to be merged

#2557 (towards #2543) Update README and User's Guide PSyclone intro
  README.md
  changelog
  doc/logo/psyclone_v1.0.png
  doc/user_guide/index.rst
Labels: ready to be merged
