Repository stfc/PSyclone, pull requests merged in 2024-06, with the labels that each got.

#2564 (Closes #2462) generalise ModuleManager
  changelog
  doc/developer_guide/index.rst
  doc/developer_guide/module_manager.rst
  doc/developer_guide/psy_data.rst
  src/psyclone/domain/lfric/lfric_extract_driver_creator.py
  src/psyclone/parse/__init__.py
  src/psyclone/parse/algorithm.py
  src/psyclone/parse/file_info.py
  src/psyclone/parse/module_info.py
  src/psyclone/parse/module_manager.py
  src/psyclone/psyir/nodes/container.py
  src/psyclone/psyir/symbols/containersymbol.py
  src/psyclone/psyir/tools/call_tree_utils.py
  src/psyclone/tests/domain/gocean/transformations/globalstoargs_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean1p0_transformations_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean_opencl_trans_test.py
  src/psyclone/tests/domain/lfric/algorithm/lfric_alg_test.py
  src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
  src/psyclone/tests/parse/algorithm_test.py
  src/psyclone/tests/parse/file_info_test.py
  src/psyclone/tests/parse/module_info_test.py
  src/psyclone/tests/parse/module_manager_test.py
  src/psyclone/tests/psyir/nodes/container_test.py
  src/psyclone/tests/psyir/symbols/containersymbol_test.py
  src/psyclone/tests/psyir/symbols/symbol_table_test.py
  src/psyclone/tests/psyir/symbols/symbol_test.py
  src/psyclone/tests/psyir/tools/call_tree_utils_test.py
  src/psyclone/tests/test_files/gocean1p0/kernel_with_use_mod.f90
  src/psyclone/tests/test_files/gocean1p0/model_mod.f90
  src/psyclone/transformations.py
Labels: enhancement, ready to be merged

#2598 (towards #2543) Refresh PSyKAl documentation
  changelog
  doc/developer_guide/dynamo0p3_topclasses.png
  doc/developer_guide/index.rst
  doc/developer_guide/psykal.rst
  doc/user_guide/algorithm_layer.rst
  doc/user_guide/api.rst
  doc/user_guide/built_ins.rst
  doc/user_guide/distributed_memory.rst
  doc/user_guide/dynamo0p3.rst
  doc/user_guide/getting_going.rst
  doc/user_guide/index.rst
  doc/user_guide/introduction.rst
  doc/user_guide/introduction_to_psykal.rst
  doc/user_guide/kernel_layer.rst
  doc/user_guide/psy_layer.rst
  doc/user_guide/psyclone_command.rst
  doc/user_guide/psyir.rst
  doc/user_guide/psyke.rst
  psyclone.pdf
Labels: ready to be merged

#2611 Switch to HPC-X from OpenMPI w/ the Nvidia HPC SDK
  changelog
  examples/nemo/scripts/Makefile
Labels: ready to be merged

#2614 (towards #2604) Fix broken tutorials links
  changelog
  psyclone.pdf
  tutorial/practicals/LFRic/building_code/1_simple_kernels/part1/README.md
  tutorial/practicals/LFRic/building_code/2_built_ins/README.md
  tutorial/practicals/LFRic/building_code/background/LFRic_structure.md
  tutorial/practicals/nemo/1_nemo_psyir/README.md
Labels: ready to be merged

#2602 (Closes #1596) exclude assumed-size character variables from ACC kernels regions.
  .github/workflows/nemo_tests.yml
  changelog
  doc/user_guide/transformations.rst
  examples/lfric/eg14/acc_parallel.py
  examples/nemo/eg3/kernel_utils.py
  examples/nemo/scripts/KGOs/run.stat.bench.orca1.1mpi.10steps
  examples/nemo/scripts/KGOs/run.stat.bench.orca2.4mpi.10steps
  examples/nemo/scripts/acc_kernels_trans.py
  src/psyclone/psyir/nodes/array_mixin.py
  src/psyclone/psyir/nodes/intrinsic_call.py
  src/psyclone/psyir/transformations/__init__.py
  src/psyclone/psyir/transformations/acc_kernels_trans.py
  src/psyclone/tests/domain/gocean/transformations/gocean1p0_transformations_test.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/domain/nemo/transformations/acc_update_test.py
  src/psyclone/tests/domain/nemo/transformations/enter_data_test.py
  src/psyclone/tests/dynamo0p3_multigrid_test.py
  src/psyclone/tests/nemo/transformations/openacc/data_directive_test.py
  src/psyclone/tests/nemo/transformations/openacc/loop_directive_test.py
  src/psyclone/tests/psyir/backend/psyir_openacc_test.py
  src/psyclone/tests/psyir/nodes/acc_directives_test.py
  src/psyclone/tests/psyir/nodes/array_mixin_test.py
  src/psyclone/tests/psyir/transformations/acc_kernels_trans_test.py
  src/psyclone/tests/psyir/transformations/profile_test.py
  src/psyclone/transformations.py
  tutorial/notebooks/nemo/nemo_example4.ipynb
  tutorial/practicals/LFRic/single_node/2_openacc/acc_parallel.py
  tutorial/practicals/LFRic/single_node/2_openacc/solutions/acc_parallel.py
  tutorial/practicals/nemo/4_nemo_openacc/README.md
  tutorial/practicals/nemo/4_nemo_openacc/kernels_trans.py
  tutorial/practicals/nemo/4_nemo_openacc/solutions/collapse_trans.py
  tutorial/practicals/nemo/4_nemo_openacc/solutions/kernels_trans.py
Labels: ready to be merged

#2615 2610 fix full extract warnings
  changelog
  psyclone.pdf
  src/psyclone/psyir/tools/call_tree_utils.py
  src/psyclone/tests/psyir/tools/call_tree_utils_test.py
Labels: ready to be merged

#2609 (Closes #2407) acc routine clauses
  changelog
  src/psyclone/psyir/nodes/acc_directives.py
  src/psyclone/tests/domain/gocean/transformations/gocean1p0_transformations_test.py
  src/psyclone/tests/psyir/nodes/acc_directives_test.py
  src/psyclone/tests/psyir/transformations/acc_routine_trans_test.py
  src/psyclone/tests/psyir/transformations/kernel_transformation_test.py
  src/psyclone/transformations.py
Labels: ready to be merged, NG-ARCH

#2626 (Closes #2622) Add convenient methods `SymbolTable.insert_argument` and `.append_argument`.
  changelog
  psyclone.pdf
  src/psyclone/psyir/symbols/symbol_table.py
  src/psyclone/tests/psyir/symbols/symbol_table_test.py
Labels: ready to be merged

#2575 (Towards #2201) Implementation enabling FileContainer's to have information about routines outside of modules.
  .github/workflows/nemo_tests.yml
  changelog
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/psyir/backend/fortran_routine_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/frontend/fparser2_program_handler_test.py
Labels: ready to be merged

#2632 (Closes #2116) 'existing-code' practical update
  changelog
  tutorial/practicals/README.md
  tutorial/practicals/nemo/1_nemo_psyir/Makefile
  tutorial/practicals/nemo/1_nemo_psyir/README.md
  tutorial/practicals/nemo/1_nemo_psyir/tra_adv.F90
  tutorial/practicals/nemo/2_nemo_profiling/README.md
  tutorial/practicals/nemo/2_nemo_profiling/tra_adv_mod.F90
  tutorial/practicals/nemo/3_nemo_openmp/README.md
  tutorial/practicals/nemo/3_nemo_openmp/omp_trans.py
  tutorial/practicals/nemo/3_nemo_openmp/tra_adv_mod.F90
  tutorial/practicals/nemo/4_nemo_openacc/README.md
  tutorial/practicals/nemo/4_nemo_openacc/tra_adv_mod.F90
  tutorial/practicals/nemo/README.md
Labels: ready to be merged, NG-ARCH
