Repository stfc/PSyclone, pull requests merged in 2024-07, with the labels that each got.

#2639 (Closes #2638) add new linkspector workflow
  .github/linkspector.yml
  .github/workflows/linkcheck.yml
  .github/workflows/mlc_config.json
  .github/workflows/python-package.yml
  changelog
  doc/developer_guide/working_practises.rst
Labels: enhancement, under review

#2583 (towards #2577) Add support for pointer assignments
  changelog
  examples/nemo/scripts/utils.py
  psyclone.pdf
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/assignment.py
  src/psyclone/psyir/transformations/arrayassignment2loops_trans.py
  src/psyclone/psyir/transformations/inline_trans.py
  src/psyclone/psyir/transformations/loop_trans.py
  src/psyclone/psyir/transformations/reference2arrayrange_trans.py
  src/psyclone/tests/domain/common/transformations/kernel_module_inline_trans_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean_opencl_trans_test.py
  src/psyclone/tests/domain/lfric/algorithm/lfric_alg_test.py
  src/psyclone/tests/psyad/domain/lfric/test_lfric_adjoint_harness.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/frontend/fparser2_derived_type_test.py
  src/psyclone/tests/psyir/frontend/fparser2_pointer_test.py
  src/psyclone/tests/psyir/nodes/assignment_test.py
  src/psyclone/tests/psyir/transformations/loop_trans_test.py
  src/psyclone/tests/psyir/transformations/reference2arrayrange_trans_test.py
Labels: ready to be merged

#2445 2444 use dash instead of colon
  changelog
  doc/user_guide/examples.rst
  doc/user_guide/profiling.rst
  examples/gocean/eg5/profile/README.md
  examples/lfric/eg14/README.md
  psyclone.pdf
  src/psyclone/psyir/nodes/psy_data_node.py
  src/psyclone/psyir/transformations/psy_data_trans.py
  src/psyclone/tests/domain/common/extract_driver_creator_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean1p0_transformations_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean_extract_test.py
  src/psyclone/tests/domain/lfric/transformations/lfric_extract_test.py
  src/psyclone/tests/psyir/nodes/extract_node_test.py
  src/psyclone/tests/psyir/nodes/psy_data_node_test.py
  src/psyclone/tests/psyir/transformations/profile_test.py
  src/psyclone/tests/psyir/transformations/psy_data_trans_test.py
  tutorial/practicals/LFRic/building_code/4_psydata/README.md
Labels: ready to be merged

#2646 2641 incorrect module names in psydata
  changelog
  doc/user_guide/profiling.rst
  examples/gocean/eg5/profile/README.md
  examples/gocean/eg5/profile/test.x90
  psyclone.pdf
  src/psyclone/psyir/nodes/psy_data_node.py
  src/psyclone/tests/psyir/nodes/profile_node_test.py
  src/psyclone/tests/psyir/nodes/psy_data_node_test.py
  tutorial/practicals/nemo/2_nemo_profiling/README.md
Labels: ready to be merged

#2647 1992 mpi support for extraction
  changelog
  doc/user_guide/psyke.rst
  examples/gocean/eg5/extract/.gitignore
  examples/gocean/eg5/extract/Makefile
  examples/gocean/eg5/extract/test.X90
  examples/lfric/eg17/full_example_extract/.gitignore
  examples/lfric/eg17/full_example_extract/Makefile
  examples/lfric/eg17/full_example_extract/README.md
  examples/lfric/eg17/full_example_extract/main.X90
  lib/extract/netcdf/.gitignore
  lib/extract/netcdf/Makefile
  lib/extract/netcdf/README.md
  lib/extract/netcdf/dl_esm_inf/Makefile
  lib/extract/netcdf/dl_esm_inf/README.md
  lib/extract/netcdf/extract_netcdf_base.jinja
  lib/extract/netcdf/lfric/Makefile
  lib/extract/netcdf/lfric/README.md
  lib/extract/netcdf/nemo/Makefile
  lib/extract/netcdf/nemo/README.md
  lib/extract/netcdf/read_kernel_data_mod.f90
  lib/extract/netcdf/read_kernel_data_mod.jinja
  lib/extract/standalone/.gitignore
  lib/extract/standalone/Makefile
  lib/extract/standalone/dl_esm_inf/Makefile
  lib/extract/standalone/dl_esm_inf/README.md
  lib/extract/standalone/extract_standalone_base.jinja
  lib/extract/standalone/lfric/Makefile
  lib/extract/standalone/lfric/README.md
  lib/extract/standalone/nemo/Makefile
  lib/extract/standalone/nemo/README.md
  lib/extract/standalone/read_kernel_data_mod.f90
  lib/extract/standalone/read_kernel_data_mod.jinja
  psyclone.pdf
  src/psyclone/domain/common/extract_driver_creator.py
  src/psyclone/domain/lfric/lfric_extract_driver_creator.py
  src/psyclone/psyir/transformations/extract_trans.py
  src/psyclone/psyir/transformations/region_trans.py
  src/psyclone/tests/domain/common/extract_driver_creator_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean_extract_test.py
  src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
  src/psyclone/tests/domain/lfric/transformations/lfric_extract_test.py
  src/psyclone/tests/psyir/nodes/extract_node_test.py
  src/psyclone/tests/psyir/transformations/acc_kernels_trans_test.py
  src/psyclone/tests/psyir/transformations/extract_trans_test.py
  src/psyclone/tests/psyir/transformations/omp_target_trans_test.py
  src/psyclone/tests/psyir/transformations/region_trans_test.py
  src/psyclone/tests/psyir/transformations/transformations_test.py
Labels: ready to be merged

#2637 (Closes #2138) add support for expressions in array bound definitions
  changelog
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/array_mixin.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/frontend/fparser2_where_handler_test.py
  src/psyclone/tests/psyir/nodes/array_mixin_test.py
Labels: ready to be merged

#2649 (Towards #2586) Add support for object-oriented `var =[>] this[%...]%procedure(...)` assignment
  changelog
  psyclone.pdf
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
Labels: ready to be merged

#2640 (closes #1796) Refactor LFRic builtins tests
  src/psyclone/domain/lfric/lfric_builtins.py
  src/psyclone/tests/domain/lfric/builtins/int_to_real_x_test.py
  src/psyclone/tests/domain/lfric/builtins/real_to_int_x_test.py
  src/psyclone/tests/domain/lfric/builtins/real_to_real_x_test.py
  src/psyclone/tests/domain/lfric/builtins/reduction_builtins_test.py
  src/psyclone/tests/domain/lfric/builtins/setval_random_test.py
  src/psyclone/tests/domain/lfric/builtins/sum_x_test.py
  src/psyclone/tests/domain/lfric/builtins/x_innerproduct_x_test.py
  src/psyclone/tests/domain/lfric/builtins/x_innerproduct_y_test.py
  src/psyclone/tests/domain/lfric/lfric_builtins_test.py
  src/psyclone/tests/domain/lfric/lfric_integer_builtins_test.py
Labels: under review

#2645 (Closes #2585) Add an optional, 'default' argument to SymbolTable.lookup()
  changelog
  src/psyclone/psyir/symbols/symbol_table.py
  src/psyclone/tests/psyir/symbols/symbol_table_test.py
Labels: enhancement, ready to be merged

#2633 (Closes #2125) Fix bugs in SymbolTable deep copy and InlineTrans when array bounds reference formal arg
  changelog
  doc/developer_guide/psyir.rst
  doc/developer_guide/psyir_symbols.rst
  src/psyclone/domain/lfric/lfric_constants.py
  src/psyclone/domain/lfric/lfric_extract_driver_creator.py
  src/psyclone/domain/lfric/lfric_types.py
  src/psyclone/psyir/backend/visitor.py
  src/psyclone/psyir/nodes/literal.py
  src/psyclone/psyir/nodes/loop.py
  src/psyclone/psyir/nodes/node.py
  src/psyclone/psyir/nodes/reference.py
  src/psyclone/psyir/nodes/scoping_node.py
  src/psyclone/psyir/symbols/data_type_symbol.py
  src/psyclone/psyir/symbols/datasymbol.py
  src/psyclone/psyir/symbols/datatypes.py
  src/psyclone/psyir/symbols/generic_interface_symbol.py
  src/psyclone/psyir/symbols/interfaces.py
  src/psyclone/psyir/symbols/routinesymbol.py
  src/psyclone/psyir/symbols/symbol.py
  src/psyclone/psyir/symbols/symbol_table.py
  src/psyclone/psyir/symbols/typed_symbol.py
  src/psyclone/psyir/transformations/inline_trans.py
  src/psyclone/tests/psyir/backend/c_test.py
  src/psyclone/tests/psyir/frontend/fparser2_subroutine_handler_test.py
  src/psyclone/tests/psyir/nodes/array_of_structures_reference_test.py
  src/psyclone/tests/psyir/nodes/literal_test.py
  src/psyclone/tests/psyir/nodes/loop_test.py
  src/psyclone/tests/psyir/nodes/reference_test.py
  src/psyclone/tests/psyir/nodes/scoping_node_test.py
  src/psyclone/tests/psyir/symbols/datasymbol_test.py
  src/psyclone/tests/psyir/symbols/datatype_test.py
  src/psyclone/tests/psyir/symbols/generic_interface_symbol_test.py
  src/psyclone/tests/psyir/symbols/interfaces_test.py
  src/psyclone/tests/psyir/symbols/routinesymbol_test.py
  src/psyclone/tests/psyir/symbols/symbol_table_test.py
  src/psyclone/tests/psyir/symbols/symbol_test.py
  src/psyclone/tests/psyir/symbols/typed_symbol_test.py
  src/psyclone/tests/psyir/transformations/inline_trans_test.py
Labels: under review

#2660 (closes #1370) Adds 'collapse' and 'ignore_dependencies_for' options to parallel_loop_trans
  changelog
  examples/nemo/scripts/omp_gpu_trans.py
  examples/nemo/scripts/utils.py
  psyclone.pdf
  src/psyclone/psyir/tools/dependency_tools.py
  src/psyclone/psyir/transformations/omp_target_trans.py
  src/psyclone/psyir/transformations/parallel_loop_trans.py
  src/psyclone/tests/nemo/transformations/openacc/loop_directive_test.py
  src/psyclone/tests/psyir/transformations/omp_target_trans_test.py
  src/psyclone/tests/psyir/transformations/parallel_loop_trans_test.py
  src/psyclone/tests/psyir/transformations/transformations_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#2673 (Closes #2652) remove lfric.utils.get_metadata_name_from_module() utility and query PSyIR instead
  changelog
  src/psyclone/domain/lfric/utils.py
  src/psyclone/psyad/domain/lfric/lfric_adjoint.py
  src/psyclone/tests/domain/lfric/test_utils.py
  src/psyclone/tests/psyad/domain/lfric/test_lfric_adjoint.py
Labels: enhancement, ready to be merged, LFRic

#2651 #2617 Support generic functions.
  changelog
  psyclone.pdf
  src/psyclone/psyir/tools/call_tree_utils.py
  src/psyclone/tests/psyir/tools/call_tree_utils_test.py
  src/psyclone/tests/test_files/dynamo0p3/driver_creation/module_call_tree_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/driver_creation/module_calling_generic_function.f90
Labels: ready to be merged
