Repository stfc/PSyclone, pull requests merged in 2024-12, with the labels that each got.

#2811 Added sphinx sphinx-autodoc-typehints
  changelog
  doc/developer_guide/conf.py
  doc/psyad/user_guide/conf.py
  doc/reference_guide/source/conf.py
  doc/user_guide/conf.py
  psyclone.pdf
  setup.py
  src/psyclone/psyir/nodes/call.py
Labels: ready to be merged

#2809 (towards #2737) update OMP section of docs
  changelog
  doc/user_guide/transformations.rst
Labels: enhancement, ready to be merged, Release

#2815 (Closes #2636) LFRic: get nlayers from first field/op argument to each kernel
  changelog
  doc/user_guide/dynamo0p3.rst
  psyclone.pdf
  src/psyclone/domain/lfric/kern_call_arg_list.py
  src/psyclone/domain/lfric/lfric_cell_iterators.py
  src/psyclone/dynamo0p3.py
  src/psyclone/tests/domain/lfric/arg_ordering_test.py
  src/psyclone/tests/domain/lfric/kern_call_arg_list_test.py
  src/psyclone/tests/domain/lfric/lfric_domain_kernels_test.py
  src/psyclone/tests/domain/lfric/lfric_field_codegen_test.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/dynamo0p3_basis_test.py
  src/psyclone/tests/dynamo0p3_cma_test.py
  src/psyclone/tests/dynamo0p3_multigrid_test.py
  src/psyclone/tests/dynamo0p3_test.py
Labels: under review, ready to be merged, LFRic, Release

#2818 #2724 Updated version number to be 3.0.1-dev.
  src/psyclone/version.py
Labels: ready to be merged

#2827 Update Zenodo reference
  README.md
  changelog
Labels: ready to be merged

#2807 (closes #2806) Import external module symbol information in the frontend
  changelog
  doc/user_guide/transformations.rst
  examples/nemo/scripts/acc_kernels_trans.py
  examples/nemo/scripts/acc_loops_trans.py
  examples/nemo/scripts/omp_cpu_trans.py
  examples/nemo/scripts/omp_gpu_trans.py
  examples/nemo/scripts/utils.py
  psyclone.pdf
  src/psyclone/generator.py
  src/psyclone/psyir/frontend/fortran.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/symbols/generic_interface_symbol.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/symbols/generic_interface_symbol_test.py
Labels: ready to be merged, NG-ARCH

#2821 (Closes #1247) Keep comments (and directives) in the frontend
  changelog
  doc/developer_guide/psyir.rst
  src/psyclone/generator.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/backend/visitor.py
  src/psyclone/psyir/commentable_mixin.py
  src/psyclone/psyir/frontend/fortran.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/container.py
  src/psyclone/psyir/nodes/routine.py
  src/psyclone/psyir/nodes/statement.py
  src/psyclone/psyir/symbols/data_type_symbol.py
  src/psyclone/psyir/symbols/datasymbol.py
  src/psyclone/psyir/symbols/datatypes.py
  src/psyclone/psyir/symbols/symbol.py
  src/psyclone/psyir/symbols/typed_symbol.py
  src/psyclone/tests/psyir/backend/fortran_gen_decls_test.py
  src/psyclone/tests/psyir/backend/fortran_unsupported_declns_test.py
  src/psyclone/tests/psyir/commentable_mixin_test.py
  src/psyclone/tests/psyir/frontend/fortran_test.py
  src/psyclone/tests/psyir/frontend/fparser2_comment_test.py
  src/psyclone/tests/psyir/frontend/fparser2_derived_type_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/symbols/datatype_test.py
Labels: ready to be merged
