Repository stfc/PSyclone, pull requests merged in 2025-05, with the labels that each got.

#2980 (closes #2976) Remove jsonschema dependency
  setup.py
Labels: under review

#2964 Add instructions for Conda install
  changelog
  setup.py
Labels: ready to be merged

#2983 (closes #2978) Ignore redundant return statements
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/transformations/inline_trans.py
  src/psyclone/tests/nemo/transformations/profiling/nemo_profile_test.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/transformations/inline_trans_test.py
Labels: ready for review

#2989 Update CI dependencies
  .github/workflows/compilation.yml
  .github/workflows/lfric_test.yml
  .github/workflows/nemo_tests.yml
  examples/nemo/eg3/Makefile
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/Makefile
Labels: under review

#2970 (towards #2966) Add `--enble-cache` psyclone command flag
  doc/user_guide/psyclone_command.rst
  doc/user_guide/user_scripts.rst
  examples/nemo/scripts/acc_kernels_trans.py
  examples/nemo/scripts/acc_loops_trans.py
  examples/nemo/scripts/omp_cpu_trans.py
  examples/nemo/scripts/omp_gpu_trans.py
  examples/nemo/scripts/utils.py
  src/psyclone/generator.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
Labels: under review

#2931 (#closes 2244) LFRic colour-tiling
  .github/workflows/lfric_test.yml
  doc/developer_guide/APIs.rst
  doc/developer_guide/psyir.rst
  examples/lfric/scripts/gpu_offloading.py
  examples/lfric/scripts/tiledcolouring_and_omp.py
  src/psyclone/domain/lfric/kern_call_arg_list.py
  src/psyclone/domain/lfric/lfric_constants.py
  src/psyclone/domain/lfric/lfric_kern.py
  src/psyclone/domain/lfric/lfric_loop.py
  src/psyclone/domain/lfric/lfric_loop_bounds.py
  src/psyclone/dynamo0p3.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/nodes/array_reference.py
  src/psyclone/tests/domain/lfric/lfric_kern_test.py
  src/psyclone/tests/domain/lfric/lfric_loop_test.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/nodes/array_reference_test.py
  src/psyclone/tests/psyir/nodes/node_test.py
  src/psyclone/tests/psyir/tools/dependency_tools_test.py
  src/psyclone/tests/psyir/transformations/loop_colour_test.py
  src/psyclone/transformations.py
Labels: ready for review, LFRic

#2995 (Towards #2551) abs_position improvements
  changelog
  src/psyclone/psyir/nodes/acc_directives.py
  src/psyclone/psyir/nodes/node.py
  src/psyclone/tests/psyir/nodes/node_test.py
Labels: enhancement, ready to be merged, PSyIR

#2987 (Towards #11) Initialised logging infrastructure
  .github/workflows/compilation.yml
  changelog
  doc/developer_guide/coding-style.rst
  doc/user_guide/psyclone_command.rst
  src/psyclone/generator.py
  src/psyclone/psyGen.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/psyGen_test.py
Labels: ready to be merged

#2993 Instructions for converting from options= to keyword arguments
  changelog
  doc/developer_guide/transformations.rst
  setup.cfg
  src/psyclone/psyir/transformations/loop_trans.py
  src/psyclone/psyir/transformations/parallel_loop_trans.py
Labels: ready to be merged

#2999 (Closes #2988) Fixed the unneccessary failure when 3 arguments provided to Structure…
  src/psyclone/psyir/symbols/datatypes.py
  src/psyclone/tests/psyir/symbols/datatype_test.py
Labels: ready to be merged

#3001 (Closes #2929) omploop docs improvement.
  src/psyclone/psyir/transformations/omp_loop_trans.py
Labels: ready to be merged

#3002 (Closes #2838) Linkspector should now work with ubuntu-latest
  .github/workflows/compilation.yml
  .github/workflows/linkcheck.yml
  .github/workflows/nemo_tests.yml
  changelog
  examples/gocean/eg2/Makefile
  examples/lfric/eg14/Makefile
  lib/profiling/nvidia/README.md
Labels: ready to be merged

#2994 (Closes #2992) fix bug in LFRicKern.all_updates_are_writes
  .github/workflows/lfric_test.yml
  changelog
  examples/lfric/scripts/KGOs/lfric_psyclone_no_annexed.cfg
  examples/lfric/scripts/does_nothing.py
  src/psyclone/domain/lfric/lfric_kern.py
  src/psyclone/domain/lfric/lfric_loop.py
  src/psyclone/lfric.py
  src/psyclone/tests/domain/lfric/lfric_field_mdata_test.py
  src/psyclone/tests/domain/lfric/lfric_kern_test.py
  src/psyclone/tests/domain/lfric/lfric_loop_test.py
  src/psyclone/tests/test_files/lfric/15.1.11_builtin_and_op_kernel_invoke.f90
  src/psyclone/tests/test_files/lfric/dg_matrix_vector_kernel_mod.F90
Labels: bug, ready to be merged, LFRic

#3000 (Closes #2973) Improves handling of pure subroutines in definition use chains for 2973
  src/psyclone/psyir/tools/definition_use_chains.py
  src/psyclone/tests/psyir/tools/definition_use_chains_backward_dependence_test.py
  src/psyclone/tests/psyir/tools/definition_use_chains_forward_dependence_test.py
Labels: under review
