Repository stfc/PSyclone, pull requests merged in 2025-07, with the labels that each got.

#2977 (towards #2971) move omp taskloop trans
  changelog
  doc/user_guide/transformations.rst
  examples/gocean/eg1/openmp_taskloop_trans.py
  src/psyclone/psyir/transformations/__init__.py
  src/psyclone/psyir/transformations/omp_taskloop_trans.py
  src/psyclone/tests/psyir/backend/psyir_openmp_test.py
  src/psyclone/tests/psyir/nodes/omp_directives_test.py
  src/psyclone/tests/psyir/transformations/omp_taskloop_trans_test.py
  src/psyclone/tests/psyir/transformations/transformations_test.py
  src/psyclone/transformations.py
Labels: ready to be merged

#3043 Bring back python 3.9 in the integration tests
  .github/workflows/python-package.yml
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/symbols/datatypes.py
  src/psyclone/tests/psyir/transformations/transformations_test.py
Labels: under review

#3037 (closes #3036) Remove AccessType location and is_accessed_before method
  doc/developer_guide/dependency.rst
  src/psyclone/core/single_variable_access_info.py
  src/psyclone/core/variables_access_map.py
  src/psyclone/domain/lfric/lfric_builtins.py
  src/psyclone/domain/lfric/lfric_kern.py
  src/psyclone/gocean1p0.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/nodes/assignment.py
  src/psyclone/psyir/nodes/call.py
  src/psyclone/psyir/nodes/if_block.py
  src/psyclone/psyir/nodes/loop.py
  src/psyclone/psyir/nodes/while_loop.py
  src/psyclone/psyir/transformations/hoist_trans.py
  src/psyclone/tests/core/single_variable_access_info_test.py
  src/psyclone/tests/core/variables_access_map_test.py
  src/psyclone/tests/dependency_test.py
  src/psyclone/tests/domain/lfric/kern_call_arg_list_test.py
  src/psyclone/tests/psyir/nodes/call_test.py
  src/psyclone/tests/psyir/tools/call_tree_utils_test.py
Labels: under review

#3046 (closes #3045) Replace eval with getattr
  changelog
  src/psyclone/psyir/backend/visitor.py
Labels: ready to be merged

#3014 (Towards #2384) directive codeblocks
  doc/user_guide/psyclone_command.rst
  examples/gocean/eg6/Makefile
  examples/lfric/eg17/full_example/Makefile
  examples/nemo/eg5/Makefile
  src/psyclone/domain/common/transformations/alg_invoke_2_psy_call_trans.py
  src/psyclone/domain/common/transformations/raise_psyir_2_alg_trans.py
  src/psyclone/domain/lfric/transformations/raise_psyir_2_lfric_alg_trans.py
  src/psyclone/generator.py
  src/psyclone/parse/utils.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/codeblock.py
  src/psyclone/tests/domain/common/transformations/alg_invoke_2_psy_call_trans_test.py
  src/psyclone/tests/domain/common/transformations/raise_psyir_2_alg_trans_test.py
  src/psyclone/tests/domain/lfric/transformations/raise_psyir_2_lfric_alg_trans_test.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/parse/utils_test.py
  src/psyclone/tests/psyir/frontend/fortran_test.py
  src/psyclone/tests/psyir/frontend/fparser2_comment_test.py
  src/psyclone/tests/psyir/nodes/codeblock_test.py
  src/psyclone/tests/test_files/lfric/1_single_invoke_with_omp_dir.f90
Labels: under review, ready to be merged

#3065 (closes #3064) Add a pytest.ini to fix existing pytest issues and warnings
  pytest.ini
Labels: under review

#3053 (closes #3052) Fix missing psylayer openmp symbols
  src/psyclone/psyir/nodes/psy_data_node.py
  src/psyclone/tests/psyir/transformations/profile_test.py
Labels: under review, LFRic, NG-ARCH

#3055 Duplicated async statements in OpenACC
  src/psyclone/psyir/nodes/acc_directives.py
  src/psyclone/psyir/nodes/acc_mixins.py
  src/psyclone/tests/psyir/nodes/acc_directives_test.py
Labels: under review

#2173 #1312: metadata for read-only arrays
  doc/user_guide/lfric.rst
  src/psyclone/domain/lfric/kernel/__init__.py
  src/psyclone/domain/lfric/kernel/scalar_array_arg_metadata.py
  src/psyclone/domain/lfric/lfric_arg_descriptor.py
  src/psyclone/domain/lfric/lfric_constants.py
  src/psyclone/tests/domain/constants_test.py
  src/psyclone/tests/domain/lfric/kernel/common_meta_arg_metadata_test.py
  src/psyclone/tests/domain/lfric/kernel/scalar_array_arg_metadata_test.py
  src/psyclone/tests/domain/lfric/lfric_array_mdata_test.py
Labels: enhancement, under review, LFRic

#3040 (Closes #3038) catch parse error in frontend and test
  changelog
  src/psyclone/generator.py
  src/psyclone/parse/kernel.py
  src/psyclone/psyir/frontend/fortran.py
  src/psyclone/tests/domain/lfric/lfric_constants_test.py
  src/psyclone/tests/generator_test.py
  src/psyclone/tests/psyad/adjoint_visitor_test.py
  src/psyclone/tests/psyad/tl2ad_test.py
  src/psyclone/tests/psyir/frontend/fortran_test.py
Labels: enhancement, ready to be merged, NG-ARCH
