Repository stfc/PSyclone, pull requests merged in 2025-02, with the labels that each got.

#2880 #2723 Add some support for dependency analysis involving array ranges.
  changelog
  src/psyclone/psyir/tools/dependency_tools.py
  src/psyclone/tests/psyir/tools/dependency_tools_test.py
Labels: ready to be merged

#2885 Update CI dependencies
  .github/workflows/compilation.yml
  .github/workflows/lfric_test.yml
  .github/workflows/nemo_tests.yml
  changelog
Labels: ready to be merged

#2799 Implement split element orders
  changelog
  doc/user_guide/psyclone_kern.rst
  doc/user_guide/transformations.rst
  examples/lfric/code/gw_mixed_schur_preconditioner_alg_mod.x90
  examples/lfric/eg13/kernel_constants.py
  examples/lfric/eg14/main.x90
  examples/lfric/eg17/full_example/README.md
  examples/lfric/eg17/full_example/main.x90
  examples/lfric/eg17/full_example_extract/main.X90
  examples/lfric/eg17/full_example_netcdf/README.md
  examples/lfric/eg17/full_example_netcdf/main.x90
  examples/lfric/eg4/solver_mod.x90
  examples/lfric/eg5/alg.f90
  examples/lfric/eg9/advective_inc_alg_mod.x90
  examples/lfric/scripts/KGOs/lfric_gungho_configuration_4its.nml
  psyclone.pdf
  src/psyclone/domain/lfric/algorithm/lfric_alg.py
  src/psyclone/tests/domain/lfric/algorithm/lfric_alg_test.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/psyad/domain/lfric/test_lfric_adjoint_harness.py
  src/psyclone/tests/test_files/dynamo0p3/10.1_operator_nofield.f90
  src/psyclone/tests/test_files/dynamo0p3/10.3_operator_different_spaces.f90
  src/psyclone/tests/test_files/dynamo0p3/10.5_operator_no_field_different_space.f90
  src/psyclone/tests/test_files/dynamo0p3/10.6_operator_no_field_scalar.f90
  src/psyclone/tests/test_files/dynamo0p3/10.7_operator_read.f90
  src/psyclone/tests/test_files/dynamo0p3/10.9_operator_first.f90
  src/psyclone/tests/test_files/dynamo0p3/10_operator.f90
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/field/field_parent_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/function_space/fs_continuity_mod.F90
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/function_space/fs_continuity_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/function_space/function_space_constructor_helper_functions_mod.F90
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/function_space/function_space_constructor_helper_functions_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/function_space/function_space_mod.F90
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/function_space/function_space_mod.f90
  src/psyclone/tests/test_files/dynamo0p3/infrastructure/operator/columnwise_operator_mod.f90
  src/psyclone/transformations.py
  tutorial/practicals/LFRic/building_code/1_simple_kernels/README.md
  tutorial/practicals/LFRic/building_code/1_simple_kernels/part1/simple_kernels_alg_mod.x90
  tutorial/practicals/LFRic/building_code/1_simple_kernels/part1/simple_kernels_driver.f90
  tutorial/practicals/LFRic/building_code/1_simple_kernels/part1/solutions/simple_kernels_alg_mod.x90
  tutorial/practicals/LFRic/building_code/1_simple_kernels/part2/simple_kernels_alg_mod.x90
  tutorial/practicals/LFRic/building_code/1_simple_kernels/part2/simple_kernels_driver.f90
  tutorial/practicals/LFRic/building_code/1_simple_kernels/part2/solutions/simple_kernels_alg_mod.x90
  tutorial/practicals/LFRic/building_code/2_built_ins/builtins_alg_mod.x90
  tutorial/practicals/LFRic/building_code/2_built_ins/builtins_driver.f90
  tutorial/practicals/LFRic/building_code/2_built_ins/solutions/builtins_alg_mod.x90
  tutorial/practicals/LFRic/building_code/3_time_evolution/configuration.nml
  tutorial/practicals/LFRic/building_code/3_time_evolution/solutions/configuration.nml
  tutorial/practicals/LFRic/building_code/3_time_evolution/time_evolution_driver.f90
  tutorial/practicals/LFRic/building_code/4_psydata/configuration.nml
  tutorial/practicals/LFRic/building_code/4_psydata/time_evolution_driver.f90
  tutorial/practicals/LFRic/building_code/gungho_lib/finite_element_config_mod.f90
  tutorial/practicals/LFRic/single_node/3_sequential/kernel_constants.py
Labels: enhancement, under review, ready to be merged, LFRic, adjoint

#2883 (#Closes 2875) Implementation to handle elemental functions in wheres
  changelog
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/psyir/frontend/fparser2_where_handler_test.py
Labels: ready to be merged

#2890 2399 handle partially written fields in driver
  changelog
  psyclone.pdf
  src/psyclone/domain/gocean/transformations/gocean_extract_trans.py
  src/psyclone/domain/lfric/transformations/lfric_extract_trans.py
  src/psyclone/tests/domain/common/extract_driver_creator_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean_extract_test.py
  src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
  src/psyclone/tests/domain/lfric/transformations/lfric_extract_test.py
  src/psyclone/tests/psyir/nodes/extract_node_test.py
Labels: ready to be merged, Release, NG-ARCH, PSyKE

#2901 (closes #2900) Fix lfric integration tests
  .github/workflows/lfric_test.yml
  .github/workflows/nemo_tests.yml
  changelog
  examples/lfric/scripts/KGOs/configuration_c16_10it.nml
  examples/lfric/scripts/KGOs/gungho_model_c16_10it-checksums.txt
  examples/lfric/scripts/KGOs/lfric_gungho_configuration_4its.nml
  examples/lfric/scripts/KGOs/lfric_gungho_configuration_4its_checksums.txt
  examples/lfric/scripts/KGOs/lfric_nvidia.patch
  examples/lfric/scripts/KGOs/nvc++.mk
  examples/lfric/scripts/KGOs/nvfortran_acc.mk
  examples/lfric/scripts/KGOs/psyclone.mk
  examples/lfric/scripts/everything_everywhere_all_at_once.py
Labels: under review, ready to be merged

#2859 (closes #2787) Add NEMOv5 GPU tests in the integration test and guarantee full reproducibility
  .github/workflows/nemo_tests.yml
  .github/workflows/nemo_v5_tests.yml
  changelog
  examples/nemo/scripts/KGOs/namelist_cfg_bench_small
  examples/nemo/scripts/KGOs/run.stat.bench.gfortran.small.100steps
  examples/nemo/scripts/KGOs/run.stat.bench.gfortran.small.10steps
  examples/nemo/scripts/KGOs/run.stat.bench.nvhpc.small.100steps
  examples/nemo/scripts/KGOs/run.stat.bench.nvhpc.small.10steps
  examples/nemo/scripts/KGOs/run.stat.bench.oneapi.small.100steps
  examples/nemo/scripts/KGOs/run.stat.bench.oneapi.small.10steps
  examples/nemo/scripts/KGOs/run.stat.nemo4.splitz12.nvhpc.10steps
  examples/nemo/scripts/KGOs/run.stat.orca1.nvhpc.10steps
  examples/nemo/scripts/KGOs/run.stat.orca2.nvhpc.10steps
  examples/nemo/scripts/Makefile
  examples/nemo/scripts/omp_cpu_trans.py
  examples/nemo/scripts/omp_gpu_trans.py
  examples/nemo/scripts/passthrough.py
  examples/nemo/scripts/utils.py
  psyclone.pdf
  src/psyclone/psyir/nodes/__init__.py
  src/psyclone/psyir/nodes/intrinsic_call.py
  src/psyclone/psyir/nodes/omp_directives.py
  src/psyclone/psyir/transformations/hoist_trans.py
  src/psyclone/psyir/transformations/omp_loop_trans.py
  src/psyclone/tests/psyir/nodes/intrinsic_call_test.py
  src/psyclone/tests/psyir/nodes/omp_directives_test.py
  src/psyclone/tests/psyir/transformations/transformations_test.py
Labels: ready to be merged, Release

#2897 #2892 Allow user-defined DoF kernels to act on field vectors
  changelog
  doc/user_guide/dynamo0p3.rst
  psyclone.pdf
  src/psyclone/domain/lfric/kern_call_arg_list.py
  src/psyclone/domain/lfric/lfric_kern_metadata.py
  src/psyclone/tests/domain/lfric/dofkern_test.py
  src/psyclone/tests/test_files/dynamo0p3/1.14_single_invoke_dofs.f90
  src/psyclone/tests/test_files/dynamo0p3/4.17_multikernel_invokes_cell_dof_builtin.f90
  src/psyclone/tests/test_files/dynamo0p3/testkern_dofs_mod.f90
Labels: bug, enhancement, ready to be merged, LFRic, Release

#2899 2889 extract non alloc arrays
  changelog
  lib/extract/netcdf/read_kernel_data_mod.f90
  lib/extract/netcdf/read_kernel_data_mod.jinja
  lib/extract/standalone/.gitignore
  lib/extract/standalone/lfric/read_kernel_data_mod.f90
  lib/extract/standalone/read_kernel_data_mod.jinja
  psyclone.pdf
  src/psyclone/domain/lfric/lfric_extract_driver_creator.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/symbols/datatypes.py
  src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
  src/psyclone/tests/psyir/symbols/datatype_test.py
  src/psyclone/tests/psyir/tools/call_tree_utils_test.py
  src/psyclone/tests/test_files/dynamo0p3/driver_creation/module_with_var_mod.f90
Labels: bug, in progress, ready to be merged, Release, PSyKE

#2906 #2744 update version to 3.1.0
  changelog
  doc/reference_guide/doxygen.config
  psyclone.pdf
  src/psyclone/version.py
Labels: under review, ready to be merged, Release

#2563 (Closes #2499) scalarization transformation implementation
  .github/workflows/nemo_tests.yml
  changelog
  doc/user_guide/transformations.rst
  examples/nemo/scripts/omp_cpu_trans.py
  examples/nemo/scripts/utils.py
  src/psyclone/core/symbolic_maths.py
  src/psyclone/psyir/nodes/node.py
  src/psyclone/psyir/nodes/reference.py
  src/psyclone/psyir/tools/definition_use_chains.py
  src/psyclone/psyir/transformations/__init__.py
  src/psyclone/psyir/transformations/scalarisation_trans.py
  src/psyclone/tests/core/symbolic_maths_test.py
  src/psyclone/tests/psyir/nodes/node_test.py
  src/psyclone/tests/psyir/nodes/reference_test.py
  src/psyclone/tests/psyir/tools/definition_use_chains_backward_dependence_test.py
  src/psyclone/tests/psyir/tools/definition_use_chains_forward_dependence_test.py
  src/psyclone/tests/psyir/transformations/scalarisation_trans_test.py
  src/psyclone/version.py
Labels: ready to be merged
