Repository stfc/PSyclone, pull requests merged in 2025-09, with the labels that each got.

#3128 #3123 Updated lfric file forgotten in 2878.
  changelog
  lib/extract/binary/lfric/README.md
  lib/extract/binary/lfric/compare_variables_mod.F90
Labels: ready to be merged

#3094 (closes #2851, #3082) Remove unecessary firstprivate
  changelog
  doc/developer_guide/dependency.rst
  doc/user_guide/psyir.rst
  src/psyclone/psyir/nodes/data_sharing_attribute_mixin.py
  src/psyclone/psyir/nodes/loop.py
  src/psyclone/psyir/nodes/node.py
  src/psyclone/psyir/nodes/reference.py
  src/psyclone/psyir/nodes/routine.py
  src/psyclone/psyir/symbols/symbol_table.py
  src/psyclone/psyir/tools/definition_use_chains.py
  src/psyclone/psyir/transformations/async_trans_mixin.py
  src/psyclone/psyir/transformations/increase_rank_loop_arrays_trans.py
  src/psyclone/psyir/transformations/intrinsics/abs2code_trans.py
  src/psyclone/psyir/transformations/intrinsics/minormax2code_trans.py
  src/psyclone/psyir/transformations/omp_minimise_sync_trans.py
  src/psyclone/psyir/transformations/scalarisation_trans.py
  src/psyclone/tests/domain/lfric/transformations/lfric_transformations_test.py
  src/psyclone/tests/parse/kernel_test.py
  src/psyclone/tests/psyir/nodes/dynamic_omp_task_directive_test.py
  src/psyclone/tests/psyir/nodes/loop_test.py
  src/psyclone/tests/psyir/nodes/node_test.py
  src/psyclone/tests/psyir/nodes/omp_directives_test.py
  src/psyclone/tests/psyir/nodes/reference_test.py
  src/psyclone/tests/psyir/tools/definition_use_chains_backward_dependence_test.py
  src/psyclone/transformations.py
Labels: under review, ready to be merged

#3095 (Closes #2916) import pure routine fix
  changelog
  src/psyclone/psyir/nodes/call.py
  src/psyclone/psyir/symbols/data_type_symbol.py
  src/psyclone/psyir/symbols/datasymbol.py
  src/psyclone/psyir/symbols/generic_interface_symbol.py
  src/psyclone/psyir/symbols/routinesymbol.py
  src/psyclone/psyir/symbols/symbol.py
  src/psyclone/psyir/symbols/symbol_table.py
  src/psyclone/psyir/symbols/typed_symbol.py
  src/psyclone/tests/psyir/nodes/call_test.py
  src/psyclone/tests/psyir/symbols/data_type_symbol_test.py
  src/psyclone/tests/psyir/symbols/datasymbol_test.py
  src/psyclone/tests/psyir/symbols/generic_interface_symbol_test.py
  src/psyclone/tests/psyir/symbols/routinesymbol_test.py
  src/psyclone/tests/psyir/symbols/symbol_test.py
  src/psyclone/tests/psyir/symbols/typed_symbol_test.py
  src/psyclone/tests/psyir/transformations/omp_task_transformations_test.py
Labels: ready to be merged, PSyIR

#3153 (Closes #3151) small case-related fixes to HoistLocalArraysTrans and Call.replace_named_arg()
  changelog
  src/psyclone/psyir/nodes/call.py
  src/psyclone/psyir/transformations/hoist_local_arrays_trans.py
  src/psyclone/tests/psyir/nodes/call_test.py
  src/psyclone/tests/psyir/transformations/hoist_local_arrays_trans_test.py
Labels: bug, ready to be merged

#3160 (Closes #3159, #3140) bug fixes for parameter declaration handling
  changelog
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/tests/psyir/backend/fortran_gen_decls_test.py
  src/psyclone/tests/psyir/frontend/fparser2_kind_params_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
Labels: bug, ready to be merged, CROCO, NAME
