Repository stfc/PSyclone, pull requests merged in 2025-06, with the labels that each got.

#2959 Update spack and enable NEMO multi-gpu
  .github/workflows/lfric_test.yml
  .github/workflows/nemo_v5_tests.yml
  doc/developer_guide/index.rst
  doc/developer_guide/integration-test.rst
  examples/gocean/eg2/acc_transform.py
  examples/lfric/scripts/KGOs/lfric_nvidia.patch
  examples/lfric/scripts/KGOs/nvidia_lfric_core.patch
  examples/nemo/scripts/KGOs/run.stat.orca1.nvhpc.10steps
  examples/nemo/scripts/omp_gpu_trans.py
  examples/nemo/scripts/utils.py
  lib/extract/standalone/lfric/Makefile
  src/psyclone/generator.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/intrinsic_call.py
  src/psyclone/tests/psyir/frontend/fparser2_select_case_test.py
  src/psyclone/tests/psyir/nodes/intrinsic_call_test.py
Labels: under review

#3029 (Closes #3026) bug with RegionTrans.get_node_list
  changelog
  doc/developer_guide/transformations.rst
  doc/user_guide/transformations.rst
  src/psyclone/psyir/transformations/region_trans.py
  src/psyclone/tests/psyir/transformations/region_trans_test.py
  src/psyclone/tests/psyir/transformations/transformations_test.py
Labels: bug, ready to be merged

#2962 (Towards #2935) Fix lbound bug when passing array arguments to routines.
  changelog
  doc/developer_guide/sympy.rst
  src/psyclone/psyad/adjoint_visitor.py
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/backend/sympy_writer.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/frontend/sympy_reader.py
  src/psyclone/psyir/transformations/inline_trans.py
  src/psyclone/psyir/transformations/reference2arrayrange_trans.py
  src/psyclone/tests/core/symbolic_maths_test.py
  src/psyclone/tests/psyir/backend/sympy_writer_test.py
  src/psyclone/tests/psyir/frontend/fparser2_where_handler_test.py
  src/psyclone/tests/psyir/frontend/sympy_reader_test.py
  src/psyclone/tests/psyir/transformations/intrinsics/minval2loop_trans_test.py
  src/psyclone/tests/psyir/transformations/reference2arrayrange_trans_test.py
Labels: bug, ready to be merged

#3034 (Closes #2837) update python versions used in testing
  .github/workflows/python-package.yml
  changelog
  doc/developer_guide/working_practises.rst
  src/psyclone/docstring_parser.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/symbols/datatypes.py
  src/psyclone/tests/parse/utils_test.py
  src/psyclone/tests/psyir/transformations/transformations_test.py
Labels: enhancement, ready to be merged

#2732 (Closes #2716) Add support for module-inlining calls to polymorphic kernels/routines
  changelog
  doc/developer_guide/transformations.rst
  examples/gocean/eg3/ocl_trans.py
  examples/lfric/eg15/matvec_opt.py
  examples/lfric/eg19/Makefile
  examples/lfric/scripts/gpu_offloading.py
  examples/lfric/scripts/kernel_print.py
  examples/xdsl/backend/xdsl.py
  src/psyclone/domain/common/transformations/kernel_module_inline_trans.py
  src/psyclone/domain/gocean/transformations/gocean_move_iteration_boundaries_inside_kernel_trans.py
  src/psyclone/domain/gocean/transformations/gocean_opencl_trans.py
  src/psyclone/domain/lfric/lfric_kern.py
  src/psyclone/gocean1p0.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/nodes/call.py
  src/psyclone/psyir/nodes/container.py
  src/psyclone/psyir/nodes/intrinsic_call.py
  src/psyclone/psyir/nodes/routine.py
  src/psyclone/psyir/transformations/intrinsics/matmul2code_trans.py
  src/psyclone/psyir/transformations/omp_task_trans.py
  src/psyclone/tests/domain/common/transformations/kernel_module_inline_trans_test.py
  src/psyclone/tests/domain/gocean/kernel/gokern_test.py
  src/psyclone/tests/domain/gocean/transformations/globalstoargs_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean1p0_transformations_test.py
  src/psyclone/tests/domain/gocean/transformations/gocean_move_iteration_boundaries_inside_kernel_trans_test.py
  src/psyclone/tests/domain/lfric/lfric_kern_test.py
  src/psyclone/tests/domain/lfric/transformations/lfric_transformations_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/frontend/fparser2_find_or_create_symbol_test.py
  src/psyclone/tests/psyir/nodes/call_test.py
  src/psyclone/tests/psyir/nodes/container_test.py
  src/psyclone/tests/psyir/nodes/routine_test.py
  src/psyclone/tests/psyir/transformations/inline_trans_test.py
  src/psyclone/tests/psyir/transformations/kernel_transformation_test.py
  src/psyclone/tests/test_files/lfric/3.5_multi_polymorphic_kernels_multi_invokes.f90
  src/psyclone/transformations.py
  tutorial/practicals/LFRic/single_node/3_sequential/matvec_opt.py
Labels: ready to be merged, NG-ARCH

#2972 (towards #2971) move parallel region trans
  changelog
  src/psyclone/psyir/transformations/__init__.py
  src/psyclone/psyir/transformations/parallel_region_trans.py
  src/psyclone/tests/psyir/transformations/parallel_region_trans_test.py
  src/psyclone/tests/psyir/transformations/transformations_test.py
  src/psyclone/transformations.py
Labels: ready to be merged
