Repository stfc/PSyclone, pull requests merged in 2025-01, with the labels that each got.

#2840 Raise error if `ignore_directives=False` but `ignore_comments=True`
  changelog
  psyclone.pdf
  src/psyclone/psyir/frontend/fortran.py
  src/psyclone/tests/psyir/frontend/fortran_test.py
Labels: bug, ready to be merged, NG-ARCH

#2832 #2831 Reorder arguments to parser for consistency
  changelog
  src/psyclone/generator.py
Labels: ready to be merged

#2810 Add file caching features to FileInfo
  .gitignore
  changelog
  doc/developer_guide/module_manager.rst
  doc/user_guide/configuration.rst
  psyclone.pdf
  src/psyclone/configuration.py
  src/psyclone/parse/__init__.py
  src/psyclone/parse/file_info.py
  src/psyclone/parse/module_info.py
  src/psyclone/parse/module_manager.py
  src/psyclone/psyir/nodes/call.py
  src/psyclone/tests/config_test.py
  src/psyclone/tests/parse/file_info_test.py
  src/psyclone/tests/parse/module_info_test.py
  src/psyclone/tests/parse/module_manager_test.py
  src/psyclone/tests/psyir/tools/call_tree_utils_test.py
  utils/run_flake8.sh
Labels: under review, ready to be merged

#2814 2704 backward accesses
  changelog
  doc/developer_guide/dependency.rst
  src/psyclone/psyir/nodes/reference.py
  src/psyclone/psyir/tools/definition_use_chains.py
  src/psyclone/tests/psyir/nodes/reference_test.py
  src/psyclone/tests/psyir/tools/definition_use_chains_backward_dependence_test.py
  src/psyclone/tests/psyir/tools/definition_use_chains_forward_dependence_test.py
Labels: ready to be merged

#2862 (Closes #2858) Stores and then reproduces explicit parenthesis over binary operations
  changelog
  examples/nemo/scripts/utils.py
  examples/psyir/create.py
  psyclone.pdf
  src/psyclone/psyir/backend/fortran.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/operation.py
  src/psyclone/psyir/transformations/intrinsics/minormax2code_trans.py
  src/psyclone/tests/psyad/transformations/test_assignment_trans.py
  src/psyclone/tests/psyir/backend/fortran_test.py
  src/psyclone/tests/psyir/frontend/fparser2_test.py
  src/psyclone/tests/psyir/nodes/operation_test.py
Labels: ready to be merged, NG-ARCH

#2855 #2853 Allow setting of the Fortran standard in the config file.
  changelog
  config/psyclone.cfg
  doc/user_guide/configuration.rst
  psyclone.pdf
  src/psyclone/configuration.py
  src/psyclone/domain/gocean/kernel/psyir.py
  src/psyclone/domain/lfric/kernel/common_metadata.py
  src/psyclone/parse/file_info.py
  src/psyclone/parse/kernel.py
  src/psyclone/parse/utils.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/frontend/fortran.py
  src/psyclone/psyir/frontend/fparser2.py
  src/psyclone/psyir/nodes/psy_data_node.py
  src/psyclone/psyir/symbols/datatypes.py
  src/psyclone/tests/configuration_test.py
Labels: bug, ready to be merged

#2857 (Closes #2854) exclude char assignments from ACC KERNELS regions
  changelog
  psyclone.pdf
  src/psyclone/psyir/nodes/structure_reference.py
  src/psyclone/psyir/symbols/datatypes.py
  src/psyclone/psyir/transformations/acc_kernels_trans.py
  src/psyclone/psyir/transformations/arrayassignment2loops_trans.py
  src/psyclone/tests/psyir/nodes/structure_reference_test.py
  src/psyclone/tests/psyir/symbols/datatype_test.py
  src/psyclone/tests/psyir/transformations/acc_kernels_trans_test.py
Labels: ready to be merged, NG-ARCH

#2829 #2826 Add config option to PSyAD
  changelog
  doc/psyad/user_guide/implementation.rst
  doc/psyad/user_guide/psyad_command.rst
  psyclone.pdf
  src/psyclone/psyad/main.py
  src/psyclone/tests/psyad/main_test.py
Labels: ready to be merged, LFRic, adjoint
