Repository stfc/PSyclone, pull requests merged in 2025-04, with the labels that each got.

#2953 (closes #2952) Gracefully fail resolving transitive type
  src/psyclone/psyir/symbols/symbol.py
  src/psyclone/tests/psyir/symbols/symbol_test.py
Labels: under review

#2930 (Towards #714) Initial implementation of ChecksumTrans with test
  doc/user_guide/transformations.rst
  src/psyclone/psyir/transformations/__init__.py
  src/psyclone/psyir/transformations/debug_checksum_trans.py
  src/psyclone/tests/psyir/transformations/debug_checksum_trans_test.py
Labels: under review, NG-ARCH

#2956 (closes #1206) Create a instrumentation doc section in the docs and other reorganisations
  README.md
  changelog
  doc/bibliography/zz_bibliography.rst
  doc/conf.py
  doc/developer_guide/APIs.rst
  doc/developer_guide/dependency.rst
  doc/developer_guide/psy_data.rst
  doc/developer_guide/psykal.rst
  doc/developer_guide/transformations.rst
  doc/index.rst
  doc/psyad/index.rst
  doc/psyad/pip_requirements.txt
  doc/psyad/psyad_command.rst
  doc/reference_guide/index.rst
  doc/references.bib
  doc/tutorials_and_examples/examples_intro.rst
  doc/tutorials_and_examples/gocean_examples.rst
  doc/tutorials_and_examples/index.rst
  doc/tutorials_and_examples/lfric_examples.rst
  doc/tutorials_and_examples/nemo_examples.rst
  doc/tutorials_and_examples/psyir_examples.rst
  doc/tutorials_and_examples/tutorials.rst
  doc/user_guide/dynamo0p3.rst
  doc/user_guide/fortran_naming_conventions.rst
  doc/user_guide/getting_going.rst
  doc/user_guide/gocean1p0.rst
  doc/user_guide/index.rst
  doc/user_guide/introduction_to_psykal.rst
  doc/user_guide/libraries.rst
  doc/user_guide/line_length.rst
  doc/user_guide/psy_data.rst
  doc/user_guide/psyad.rst
  doc/user_guide/psyclone_command.rst
  doc/user_guide/psyclone_kern.rst
  doc/user_guide/psyir.rst
  doc/user_guide/psyke.rst
  doc/user_guide/transformations.rst
  doc/user_guide/tutorials_and_examples.rst
  doc/user_guide/user_scripts.rst
  examples/Makefile
  examples/README.md
  examples/line_length/Makefile
  examples/line_length/README.md
  examples/line_length/longlines.f90
  examples/line_length/runme.py
  examples/line_length/testkern_qr_mod.F90
  src/psyclone/line_length.py
Labels: ready to be merged

#2877 (Towards #2668) Implementation of keyword arguments to transformations instead of options dict.
  .github/workflows/compilation.yml
  .github/workflows/python-package.yml
  changelog
  doc/user_guide/transformations.rst
  src/psyclone/docstring_parser.py
  src/psyclone/errors.py
  src/psyclone/psyGen.py
  src/psyclone/psyir/transformations/loop_trans.py
  src/psyclone/psyir/transformations/omp_loop_trans.py
  src/psyclone/psyir/transformations/omp_task_trans.py
  src/psyclone/psyir/transformations/parallel_loop_trans.py
  src/psyclone/tests/docstring_parser_test.py
  src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
  src/psyclone/tests/psyGen_test.py
  src/psyclone/tests/psyir/transformations/loop_trans_test.py
  src/psyclone/tests/psyir/transformations/omp_taskloop_transformations_test.py
  src/psyclone/tests/psyir/transformations/parallel_loop_trans_test.py
  src/psyclone/tests/psyir/transformations/transformations_test.py
  src/psyclone/tests/utils_test.py
  src/psyclone/transformations.py
  src/psyclone/utils.py
Labels: ready to be merged
